### ISSUE TITLE
Visual mode turning back to default when I have it on disabled whenever I open up something in fullscreen

### ISSUE THREAD

**Issue by laughingstar101** [seerge/g-helper#3386] opened 2024-11-17 03:20 UTC
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I have the visual mode set on disabled, and whenever I open up something in full screen, like fullscreening a video or playing a game in fullscreen, the visual mode turns back to default abrubtly. But when i open up ghelper again, it fixes itself, as in it switches back to disabled visual mode. but if i close ghelper, after some time the visual mode will turn back to default.

### How to reproduce the bug?

1. Go to anything that is full screen- a YouTube video or a video game works 
2. Turn visual mode on G-Helper to disabled
3. Close G-Helper

### Logs

[log.txt](https://github.com/user-attachments/files/17788731/log.txt)

### Device and Model

Asus Zephyrus GA401QH

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.197.0

### OS

Windows 11 23H2

**Comment by seerge** [comment] 2024-11-17 09:22
@laughingstar101 hello, this is a duplicate of a very similar issue https://github.com/seerge/g-helper/issues/3334

Please check my answer and explanation of why is that so there.

Main advice is to use AMD drivers from Asus here ;)

Thanks

**Closed** 2024-11-17 09:22 UTC
Labels: duplicate, answered

**Comment by laughingstar101** [comment] 2024-11-17 12:52
Hi, so reinstalling drivers from the Updates section seems to have fixed the problem.
Thanks!
