### ISSUE TITLE
keyboard brightness issue

### ISSUE THREAD

**Issue by yesnt10** [seerge/g-helper#502] opened 2023-06-01 12:24 UTC
The keyboard dims the brightness when running on battery, but the brightness does not return when I plug it in.

![image](https://github.com/seerge/g-helper/assets/114935167/5082f233-c2c4-40ea-bfb0-4649ec70f551)

**Comment by seerge** [comment] 2023-06-01 12:35
@yesnt10 if you manually adjusted brightness while being on battery (with hotkeys for example), it will remember that as normal setting - and therefore won't increase it more, when you plug in.

**Comment by seerge** [comment] 2023-06-01 12:38
@yesnt10 can you try to reproduce it again and post a log here from %appdata%\ghelper ?

**Comment by seerge** [comment] 2023-06-01 12:52
@yesnt10 

It asks you to update cause it runs 0.69 (From the log). I assume you forgot old exe in some other folder, and it runs on startup? :) If so - manually run a never version, and uncheck-check run on startup checkbox. It will re-create a startup task pointing to the latest version you run.

As for the brightness, I see that it tries to set brightness when laptop is powered back.

Can you just unplug it (to see if brightness goes down) and then plug back to see if it goes up ?

**Comment by yesnt10** [comment] 2023-06-01 13:00
Update issue resolved. Thanks. But now the brightness does not dim when I take it off the charge.

**Comment by yesnt10** [comment] 2023-06-01 13:17
Yeah. it does support that 3 level of brightness. And thank you it worked!!!!

**Comment by seerge** [comment] 2023-06-01 13:17
@yesnt10 in both ways?

**Comment by seerge** [comment] 2023-06-01 13:20
Ok, great. Closing as solved then :)

**Closed by seerge** 2023-06-01 13:20 UTC

**Comment by TheBestPessimist** [comment] 2023-06-02 07:08
@seerge looking at the [fix](https://github.com/seerge/g-helper/commit/314d25c751b532c22ed9da1cfdb6518b5f784035) , can we make it a little smarter?
Can GHelper remember keyboard brightness level when on battery and brightness level when in AC? just like it does for power modes? 
For example, what i do is use max brightness in AC and min (not off) on battery.

**Comment by seerge** [comment] 2023-06-02 11:20
@TheBestPessimist i was also thinking about this before. You can check this build - it should remember backlight brightness independently for battery / power : 
[GHelper.zip](https://github.com/seerge/g-helper/files/11634740/GHelper.zip)

**Comment by yesnt10** [comment] 2023-06-02 11:35
I turn off the brightness while on battery. And I'm charging it. But when I take it off the charger, it starts the brightness from the lowest level. @seerge

**Comment by seerge** [comment] 2023-06-02 11:39
@yesnt10 it will remember brightness on battery. So set to off (while being on battery), and next time it will remember that

**Comment by yesnt10** [comment] 2023-06-02 11:41
it is not remember exactly @seerge

**Comment by seerge** [comment] 2023-06-02 11:42
@yesnt10 can you check https://github.com/seerge/g-helper/releases/tag/v0.76 and if it still not remembering - post a log here ?

**Comment by yesnt10** [comment] 2023-06-02 11:52
yes i use that build. 
[log.txt](https://github.com/seerge/g-helper/files/11634990/log.txt)

**Comment by seerge** [comment] 2023-06-02 12:01
[GHelper.zip](https://github.com/seerge/g-helper/files/11635038/GHelper.zip)
Try this one instead. (but repeat whole procedure again, set brightness to 0 on battery, then try to plug again, and unplug in a few seconds)

**Comment by seerge** [comment] 2023-06-02 13:24
I think i know the reason. If you have asus optimization service running- please stop and disable it.

And then just restart g-helper :)

**Comment by yesnt10** [comment] 2023-06-02 13:43
Yes. worked. but this time the nvidia graphics card does not turn on again :/

**Comment by yesnt10** [comment] 2023-06-02 13:52
i just restart and it worked. idk but this is asus job. I hate asus. asus should hire you instead of those useless guys. thank you.

**Comment by seerge** [comment] 2023-06-02 14:28
@yesnt10 I think GPU was tired of constant On/Off cycles (since you had optimized mode on - and plugged / unplugged laptop all the time while testing keyboard)

**Comment by yesnt10** [comment] 2023-06-02 16:16
No one has been able to solve my this problem. I also wanted to ask you. When the computer is in sleep mode, it wakes up by itself. Keyboard and mouse lights turn on and off. I made the necessary settings for the mouse from the device manager. But it still does this. Do you have any idea about that issue?

**Comment by seerge** [comment] 2023-06-02 17:23
@yesnt10 i don't know ) try to reset power plan setttings / any other power settings in windows mb ?

**Comment by TheBestPessimist** [comment] 2023-06-03 06:23
@yesnt10 I had the same issue.

For me the solution was convoluted: disable s0 sleep (so much trial and error here!) and use hibernate every time, then disable all wake triggers because the laptop randomly woke up even from hibernate.
