### ISSUE TITLE
Keyboard still flashing while device is sleeping

### ISSUE THREAD

**Issue by s4-Liuzhuang** [seerge/g-helper#2137] opened 2024-02-29 02:15 UTC
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

option for sleep laptop backlight is turned off, keyboard lights up during sleep mode

### How to reproduce the bug?

Put device to sleep

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14441980/log.txt)

### Device and Model

Asus Zephyrus M16

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.154.0

### OS

Windows 11 23H2

**Comment by seerge** [comment] 2024-02-29 08:54
@s4-Liuzhuang hello, the USB command it turn sleeping animation is same for all Asus devices. And it's set in the log

```
2/24/2024 4:20:23 PM: USB 19B6: 5D-BD-01-5D-1F-FF-FF-FF
```

What happens to your backlight in sleep ? Does it turn on sleeping "blinking" animation ? or it just stays ON ? if it's stays ON - it means your laptop is not sleeping in a first place, and you should look into windows why it's not happening.

**Comment by s4-Liuzhuang** [comment] 2024-02-29 17:01
It lights up for about 1 second once in a while

**Comment by seerge** [comment] 2024-02-29 17:03
@s4-Liuzhuang once in a while is how often? Sleeping animation is a constant blinking (every 1 or 2 seconds each).

**Comment by s4-Liuzhuang** [comment] 2024-02-29 17:04
Like after several minutes? it does look different from the sleeping animation

**Comment by seerge** [comment] 2024-02-29 17:05
@s4-Liuzhuang well, then it's probably windows doing some weird stuff and waking up from from it's broken sleep :)

I'm afraid it's not related to the app.

**Comment by s4-Liuzhuang** [comment] 2024-02-29 17:06
But I did turn off the keyboard lighting as a whole, it shouldn't light up even awake

**Comment by seerge** [comment] 2024-02-29 17:07
@s4-Liuzhuang it shouldn't :) and g-helper doesn't do that. Do you have Dynamic Lighting turned on in windows ? Turn it off

**Comment by s4-Liuzhuang** [comment] 2024-02-29 17:08
I will try with dynamic lighting off, thanks!

**Comment by seerge** [comment] 2024-02-29 17:10
@s4-Liuzhuang g-helper puts all it's commands it sends to keyboard to the log. Backlight brightness is ``5D-BA-C5-C4-[LEVEL]``. 

And ALL records is 0 in your log :) so it has never even tried to turn it on.

**Comment by seerge** [comment] 2024-03-01 13:15
@s4-Liuzhuang any updates?

**Comment by EmpressPENG** [comment] 2024-03-04 03:27
I think Armoury Crate is taking over the PC while sleeping and G-helper won't work. Because my G16 also have a flashing keyboard while device is sleeping. The light mode of the keyboard is the same setting of Armoury Crate but not G-helper.

**Comment by AudreyAP** [comment] 2024-03-05 05:00
This is caused by modern standby waking up to check the network.

I confirmed this by disabling modern standby - the blinking goes away.

**Comment by s4-Liuzhuang** [comment] 2024-03-05 05:40
> This is caused by modern standby waking up to check the network.
> 
> I confirmed this by disabling modern standby - the blinking goes away.
> 
> Tested on GU604VI

How do you disable modern standby? is it adding PlatformAoAcOverride to regedit, that method crashes my device

**Comment by seerge** [comment] 2024-03-07 00:10
@s4-Liuzhuang you can try this mb (to turn off network) https://www.elevenforum.com/t/enable-or-disable-modern-standby-network-connectivity-in-windows-11.3286/

Anyway, it's not G-Helper's fault here. As what you see is not a sleeping animation (that is turned off), but some hiccups between broken windows sleep and laptop firmware.

I'm closing this as not planned, as I can't fix anything here and wishing you good luck :)

**Closed by seerge** 2024-03-07 00:10 UTC
Labels: question, answered
