### ISSUE TITLE
Extra Menu is missing

### ISSUE THREAD

**Issue by MckenzieDavis** [seerge/g-helper#908] opened 2023-07-27 12:11 UTC
On Zephyrus G14 GA401IU, the extra menu under keyboard is now missing
![Screenshot 2023-07-27 200521](https://github.com/seerge/g-helper/assets/82803124/0be97439-adaa-4175-b4a3-e53eb7d0e6d2)

**Comment by seerge** [comment] 2023-07-27 12:57
@MckenzieDavis hello, this is a duplicate of https://github.com/seerge/g-helper/issues/895 just redownload 0.102 :)

**Closed by seerge** 2023-07-27 12:57 UTC

**Comment by MckenzieDavis** [comment] 2023-07-30 07:06
> @MckenzieDavis hello, this is a duplicate of #895 just redownload 0.102 :)

Still not available on GA401IU after redownload

**Comment by seerge** [comment] 2023-07-30 11:39
@MckenzieDavis that's strange, can you check this build : ?

[GHelper.zip](https://github.com/seerge/g-helper/files/12209069/GHelper.zip)

**Comment by MckenzieDavis** [comment] 2023-07-30 11:45
Now it works! Thanks!
