### ISSUE TITLE
Will be for desktop PC motherboards too? 

### ISSUE THREAD

**Issue by seba2282** [seerge/g-helper#2918] opened 2024-08-03 19:33 UTC
Hello, will be for PC too? 
I have Z790 Plus D4 and without armoury crate - [ ] can't normally download drivers without combinations. With AC he let's download drivers but it much install unwanted programs too. About update bios still only can manually with and without AC. .

**Comment by seerge** [comment] 2024-08-03 20:49
@seba2282 hello, this is a duplicate of https://github.com/seerge/g-helper/issues/2541 and others. Please check my response there

**Closed by seerge** 2024-08-03 20:49 UTC
Labels: duplicate
