### ISSUE TITLE
Sceen mode Auto won't switch to 144Hz if laptop is powered down while on battery

### ISSUE THREAD

**Issue by toomuchsalt** [seerge/g-helper#387] opened 2023-05-15 14:23 UTC
**Describe the bug**

**Clear scenario to Reproduce**
1. Set screen mode to Auto
2. Unplug the laptop ( screen switches to 60hz )
3. Power down / wait for discharge
4. Plug in and start the laptop

**Expected behavior**
Screen is in 144Hz mode or switches quickly after GHelper is started

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11478635/log.txt)

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/3951558/01a13d41-b453-4048-b3e7-ebfd8b6d4c56)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - G15 2021 (GA503QM)

**Asus software**
- Armoury crate services intalled but disabled
- MyASUS installed
- ASUSOptimization

**Comment by seerge** [comment] 2023-05-15 14:27
@toomuchsalt i didn't get it. You start laptop plugged and it goes to 144hz (and it's also visible in a log : ``15/05/2023 18:04:28: Screen = 144Hz : OK``), 

Do you by any chance have Asus smart display control running ? if so - uninstall it

**Comment by toomuchsalt** [comment] 2023-05-15 15:29
Log shows it, but the screen is in 60Hz mode, visible on the screenshot( took it right after booting )

Asus smart display control isn't installed

**Comment by seerge** [comment] 2023-05-21 12:58
@toomuchsalt any updates? I still don't have scenario to reproduce here

**Comment by toomuchsalt** [comment] 2023-05-21 18:55
Just updated to the 0.65. Still facing the same issue

Here's the log part just before shutting down and after boot

```
21/05/2023 22:52:45: ------------
21/05/2023 22:52:45: App launched: ROG Zephyrus G15 GA503QM_GA503QM :0.66.0.0
21/05/2023 22:52:45: NVAPI_API_NOT_INITIALIZED
21/05/2023 22:52:45: AutoSetting for Online
21/05/2023 22:52:45: PerformanceMode = 0 : OK
21/05/2023 22:52:45: Boost 0
21/05/2023 22:52:45: Eco flag : 1
21/05/2023 22:52:45: Mux flag : -65536
21/05/2023 22:52:45: Screen = 144Hz : OK
21/05/2023 22:52:45: ScreenOverdrive = 1 : OK
21/05/2023 22:52:46: Monitor Power On
21/05/2023 22:53:03: WMI event 87
21/05/2023 22:53:04: Windows - Power Mode Changed
21/05/2023 22:53:04: AutoSetting for Offline
21/05/2023 22:53:04: PerformanceMode = 0 : OK
21/05/2023 22:53:04: WMI event 123
21/05/2023 22:53:04: Boost 0
21/05/2023 22:53:04: Eco flag : 1
21/05/2023 22:53:04: Mux flag : -65536
21/05/2023 22:53:04: Screen = 60Hz : OK
21/05/2023 22:53:04: ScreenOverdrive = 0 : OK
21/05/2023 22:54:04: ------------
21/05/2023 22:54:05: App launched: ROG Zephyrus G15 GA503QM_GA503QM :0.66.0.0
21/05/2023 22:54:05: NVAPI_API_NOT_INITIALIZED
21/05/2023 22:54:05: AutoSetting for Online
21/05/2023 22:54:05: PerformanceMode = 0 : OK
21/05/2023 22:54:05: Boost 0
21/05/2023 22:54:05: Eco flag : 1
21/05/2023 22:54:05: Mux flag : -65536
21/05/2023 22:54:05: Screen = 144Hz : -1
21/05/2023 22:54:05: ScreenOverdrive = 1 : OK
21/05/2023 22:54:05: Monitor Power On
```

Suppose `Screen = 144Hz : -1` indicates that switching to 144Hz failed somehow

**Comment by seerge** [comment] 2023-05-21 19:32
@toomuchsalt what happened on last app launch ? Did you just boot your laptop?

**Comment by seerge** [comment] 2023-05-21 19:45
@toomuchsalt try this build with verbose logging and post a log here again 
[GHelper.zip](https://github.com/seerge/g-helper/files/11525392/GHelper.zip)

**Comment by toomuchsalt** [comment] 2023-05-22 10:08
>  what happened on last app launch ? Did you just boot your laptop?
Yes. Regular boot.


[log.txt](https://github.com/seerge/g-helper/files/11529762/log.txt)

Here's the log. The same process. 
- Start GHelper
- Enable Auto Mode
- Unplug ( screen changes to 60Hz )
- Shutdown
- Plug in( while powered down )
- Boot up ( screen remains in 60 Hz )

At this moment, changing screen to "144Hz + OD" from Auto successfully changes screen mode to 144Hz. Restarting the GHelper also changes the screen mode just fine. It seems like GHelper tries to change refresh rate too early and fails.

**Comment by seerge** [comment] 2023-05-22 10:41
@toomuchsalt it could be indeed, as from log it clearly identifies display correctly (and even reads max resolution to set).

It looks more like a hickup specific to your system (as it takes soo long to initialize display after laptop boot). But I can add some workaround, like a second attempt to set refresh rate 1 sec or so.

**Comment by seerge** [comment] 2023-05-22 15:36
@toomuchsalt can you check this build? it will re-try to set refresh rate second time if first fails

[GHelper.zip](https://github.com/seerge/g-helper/files/11533179/GHelper.zip)

**Comment by toomuchsalt** [comment] 2023-05-22 19:37
Clean startup(fast boot enabled). GHelper starts from own task( run on startup is enabled )

**Comment by seerge** [comment] 2023-05-22 19:38
@toomuchsalt i think i can offer more "universal" solution, since your screen wakes up so slowly.

In windows Task Scheduler - find G-Helper task, and just modify it to delay for 5 seconds (or so )

![Screenshot 2023-05-22 213654](https://github.com/seerge/g-helper/assets/5920850/f71d697c-2f02-4dcd-8376-d6f6b05cc888)

**Comment by toomuchsalt** [comment] 2023-05-22 20:17
For some reason the shortest delay available on my system was 30 seconds( anything shorter gets removed from trigger as if I'd disabled delay completely ). With 30 seconds delay it works. I guess I'll have to hack a bat file to launch it with lower delay.

I still wonder what's going on, since the screen is definitely woken up by the time I log in( even tried to disable fingerprint reader to avoid early login ).

Nevermind then. Since noone else is experiencing this, it must be something wrong/funny with my OS/HW

**Comment by seerge** [comment] 2023-05-22 20:19
@toomuchsalt true, but you can literally type "5 seconds" there (and it will save it)

**Comment by seerge** [comment] 2023-05-23 20:16
Closing as it seems to be solved ;)

**Closed by seerge** 2023-05-23 20:16 UTC
Labels: not reproducible
