### ISSUE TITLE
Disable/Enable Asus Boot Sound in Extra

### ISSUE THREAD

**Issue by ButterCCM** [seerge/g-helper#1045] opened 2023-08-10 05:03 UTC
**Is your feature request related to a problem? Please describe.**
Not a serious issue but I had liked in armoury crate the easy access to switching the boot sound on and off. Sometimes I would turn it on when bringing the laptop to people that didn't see it before to really show off or when in my room. Then I would turn it off if I was going to work or classes for example. 

**Describe the solution you'd like**
A toggle in the extras section to allow for the sound to be enabled and disabled without needing to go into the BIOS for it.

**Describe alternatives you've considered**
Default it to be off when using GHelper as I would image the majority of people don't want the boot sound but at the same time I don't think this is best.

**Additional context**
None needed

**Comment by seerge** [comment] 2023-08-10 07:32
@ButterCCM hello,

This is a duplicate of https://github.com/seerge/g-helper/issues/355 and https://github.com/seerge/g-helper/issues/261

I don’t know endpoint responsible for that :)

**Closed by seerge** 2023-08-10 07:32 UTC

**Comment by ButterCCM** [comment] 2023-09-13 06:04
> @ButterCCM added in https://github.com/seerge/g-helper/releases/tag/v0.120

Awesome, thank you so much!
