### ISSUE TITLE
Slow / Sustained sPPT / SPL CPU power sliders are reversed or labelled incorrectly

### ISSUE THREAD

**Issue by elite-NSX** [seerge/g-helper#1885] opened 2024-01-10 21:28 UTC
v141 and v144 the fast / slow power sliders are reversed / labelled incorrectly

adj. fast slider then used ryzenadj command prompt and slow CPU wattage moves and vice versa 

plz fix soon cheers and thank you for the awesome tool

**Comment by seerge** [comment] 2024-01-10 21:39
@elite-NSX i don't think that's the case.

Post a log from the app as it was clearly asked in issue template. Also please attach screenshots from HWinfo showing limits.

**Comment by elite-NSX** [comment] 2024-01-10 22:13
![image](https://github.com/seerge/g-helper/assets/29660985/4c52a9e7-3b98-45ad-a493-ec8f9038d103)

srry its the slow limit and sustained limits that mayb incorrect, how /where do i get the log if image isnt enough

**Comment by elite-NSX** [comment] 2024-01-10 22:16
[log.txt](https://github.com/seerge/g-helper/files/13895092/log.txt)

**Comment by elite-NSX** [comment] 2024-01-10 22:16
srry again for not following issue template

**Comment by seerge** [comment] 2024-01-10 22:30
Looks like they can be indeed swapped for AMD

@IceStormNG  can you please check on your Intel device, if PL1 and PL2 sliders actually are swapped ? 

You can just set different values and run cinebench23 and monitor in hwinfo if it uses higher value first, and then goes to lower

**Comment by seerge** [comment] 2024-01-10 22:53
@elite-NSX this build should have SPL / SPPT swapped

[GHelper.zip](https://github.com/seerge/g-helper/files/13895337/GHelper.zip)

**Comment by elite-NSX** [comment] 2024-01-10 23:26
confirmed issue in my old build then used same method for new build issue was fixed the slider adj. correct values now cheers thx man

is that new build based off v145 pre release or 144 latest ''stable''

**Comment by seerge** [comment] 2024-01-10 23:27
@elite-NSX 145 is same as 144. This change is not published yet, as I want to verify if PL1/PL2 values for Intel are also swapped or not (they are set by same "endpoints" in asus driver)

**Comment by elite-NSX** [comment] 2024-01-10 23:30
ok but i can jus use the build u provided in the mean time and i edited the title of issue so no confusion

**Comment by elite-NSX** [comment] 2024-01-10 23:36
if their set in asus driver and not in AMD driver then this might be a one off case im not on latest drivers and dont plan on updating mayb ask some1 with flow x13 GV302XU whos on latest drivers and windows updates to confirm swapped values

cheers man and thank again

**Comment by seerge** [comment] 2024-01-10 23:38
@elite-NSX it's set in BIOS via Asus driver (that servers just as a proxy-layer)

This is same method as Armoury sets values, so i'm 99% sure it doesn't change from version to  version as otherwise it would break Armoury as well :)

**Comment by seerge** [comment] 2024-01-10 23:45
@IceStormNG i checked Asus Control Interface DSDT dump for how it's set there, and it looks like it's also swapped for Intel

```
        Method (SPLX, 2, Serialized)
        {
            If ((FANM == 0x04))
            {
                SECC (0x46, One)
                Switch (Arg0)
                {
                    Case (0x001200A0) <---- this endpoint was called PL1 before
                    {
                        M6F1 = Arg1
                    }
                    Case (0x001200A3) <---- this endpoint was called PL2 before
                    {
                        M6F0 = Arg1
                    }
                    Case (0x001200B0)
                    {
                        M6EC = Arg1
                    }
                    Case (0x001200B1)
                    {
                        M6F1 = Arg1
                    }
                    Default
                    {
                        SECC (0x46, Zero)
                    }

                }
            }
        }
```

While in reality 

``0x001200A3`` assigns something called ``M6F0`` 
``0x001200A0`` assigns something called ``M6F1`` 

Judging from names of those variables, looks like F0 is sustained limit (i.e. PL1) and F1 is boost limit (i.e. PL2)

**Comment by elite-NSX** [comment] 2024-01-10 23:47
ok i am on the latest bios version v311 if that helps

**Comment by elite-NSX** [comment] 2024-01-10 23:49
im glad i could help

**Comment by seerge** [comment] 2024-01-11 12:49
@Kikimahe i think you also have Intel, can you test if Pl1 and PL2 are swapped ? set something like PL1 30 and PL 2 60 and run cinebench, to see on what power consumption it starts to run? :)

**Comment by IceStormNG** [comment] 2024-01-11 14:38
> @IceStormNG i checked Asus Control Interface DSDT dump for M16 2023 and how it's set there, and it looks like it's also swapped for Intel

I just tested with 0.144 and yes, PL1 and PL2 are swapped. PL1 slider sets the burst limit and PL2 slider the sustained limit for me.

**Comment by seerge** [comment] 2024-01-11 14:40
@IceStormNG great, thanks for confirmation! 🙇 

I have swapped them and pushed live already as 0.146.

Can you check if 146 works correctly ?

**Comment by IceStormNG** [comment] 2024-01-11 15:03
@seerge with the current repo state, it works fine judged by a quick test.

**Comment by seerge** [comment] 2024-01-11 15:05
@IceStormNG great, closing as completed then

**Closed by seerge** 2024-01-11 15:05 UTC
Labels: question

**Comment by Kikimahe** [comment] 2024-01-11 17:52
> @Kikimahe i think you also have Intel, can you test if Pl1 and PL2 are swapped ? set something like PL1 30 and PL 2 60 and run cinebench, to see on what power consumption it starts to run? :)

Hi Seerge, 
I apologize for not helping you today. I was very busy with work. ;'(

**Comment by seerge** [comment] 2024-01-11 19:32
@Kikimahe great, thanks for confirming that 0.146 works as intended.
