### ISSUE TITLE
Let GHelper control audio settings

### ISSUE THREAD

**Issue by GBroad** [seerge/g-helper#589] opened 2023-06-09 20:16 UTC
**Is your feature request related to a problem? Please describe.**
Armoury crate has recently completely broken all audio input for many devices, even once uninstalled

See here: https://rog-forum.asus.com/t5/armoury-crate/armory-crate-freeze-when-opening-audio-tab/td-p/934136

**Describe the solution you'd like**
It would be great if GHelper could control and remove these issues so audio can function properly again, and so the audio components of the device could be controlled in general

**Additional context**
The AI noise cancelling feature in armoury crate is extremely buggy in general, with enabling and disabling not working very often, and also providing other problems when trying to control audio input in other ways. A lot of the time programs think the AI noise cancelling utility is on even when it isn't in AC.

**Comment by seerge** [comment] 2023-06-09 20:26
@GBroad hello,

I didn’t get what you want to be honest. Fix some abstract not working audio settings caused by other application? :) that i can’t even reproduce?

Try to to completely uninstall and delete all audio devices and then reinstall back .

It’s absolutely out of scope

**Closed by seerge** 2023-06-09 20:26 UTC

**Comment by GBroad** [comment] 2023-06-09 20:28
> @GBroad hello,
> 
> I didn’t get what you want to be honest. Fix some abstract not working audio settings caused by other application? :) that i can’t even reproduce?
> 
> Try to to completely uninstall and delete all audio devices and then reinstall back .
> 
> It’s absolutely out of scope

Hi, I was wondering if GHelper could provide control for the AI noise cancelling utility provided in many ROG laptops. Is that in scope?

**Comment by seerge** [comment] 2023-06-09 20:46
@GBroad that is (partially) covered in this issue https://github.com/seerge/g-helper/issues/18 

In short - it's proprietary software, and there is no information on how to access / enable / disable it. If you know - please contribute :)

**Comment by LeyendaV** [comment] 2025-07-08 22:24
Sorry to revive this, but would be nice if, at least, FN+C and FN+V actually work to remap them into, for example, muting/unmuting the system. 
Doesn't work by selecting the option from the drop menu, nor choosing Custom and writing the value in the action box.

**Comment by seerge** [comment] 2025-07-08 22:26
@LeyendaV if they are not supported on the device (which is the case for many TUF models) - they can't be remapped to anything

**Comment by LeyendaV** [comment] 2025-07-08 22:44
Already fixed this issue using PowerToys.
