### ISSUE TITLE
screen glitches on system start up

### ISSUE THREAD

**Issue by q1-ko** [seerge/g-helper#3400] opened 2024-11-23 13:37 UTC
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I've encountered this issue only when using the _disable_ visual mode, and it happens only on startup, after a system shut down.
The glitch is persistent across the system, even from the user login screen, the color look all funny :), I've included a photo (quality is not the best, but it get the idea)
![20241121_164754](https://github.com/user-attachments/assets/960ba196-c012-4eb0-843e-5d2882b87119)

to get read of the glitch i change the visual mode to something else than disable, and turn back to normal, after that I can also set it back to disable with out any glitches

### How to reproduce the bug?

1. set visual mode to disable
2. shut down system
3. and power it on

### Logs

[log.txt](https://github.com/user-attachments/files/17879892/log.txt)

### Device and Model

Asus Zephyrus G15 GA503QM

### Armoury Crate

Uninstalled

### Asus Services

7

### Version

0.199.0

### OS

Windows 11 home 24H2

**Comment by seerge** [comment] 2024-11-23 13:48
@q1-ko hello, this is a duplicate of a very similar issue https://github.com/seerge/g-helper/issues/3334

Please check my answer and explanation of why is that so there.

Main advice is to use AMD drivers from Asus here ;)

Thanks

**Closed** 2024-11-28 12:45 UTC
Labels: duplicate, answered
