### ISSUE TITLE
Add Color Gamut ICC change PLZ

### ISSUE THREAD

**Issue by Aragamiz** [seerge/g-helper#1833] opened 2024-01-01 13:49 UTC
Need a WAY to change screen color space when left Asus software , thk~!

**Comment by seerge** [comment] 2024-01-01 13:52
@Aragamiz https://github.com/seerge/g-helper/wiki/FAQ#how-do-i-set-different-visual-styles

**Comment by Aragamiz** [comment] 2024-01-02 09:09
> @Aragamiz https://github.com/seerge/g-helper/wiki/FAQ#how-do-i-set-different-visual-styles

I made a mistake in describing it. I apologize for the inconvenience.
That GameVisual is the only way that change the Color Gamut to p3 or srgb. GameVisual UWP can't do this. Like this.

![屏幕截图 2024-01-02 153703](https://github.com/seerge/g-helper/assets/20516214/8436a7f9-db7d-432f-bf5f-305af16973bf)

**Comment by seerge** [comment] 2024-01-02 09:34
@Aragamiz it's still a duplicate of https://github.com/seerge/g-helper/issues/38

Check that topic for advices

**Closed by seerge** 2024-01-02 09:34 UTC

**Comment by seerge** [comment] 2024-03-07 23:09
Added in latest release https://github.com/seerge/g-helper/releases
