### ISSUE TITLE
After using Ghelper, scar 16 4080's back light bar doesn't glow

### ISSUE THREAD

**Issue by rnylx** [seerge/g-helper#872] opened 2023-07-24 07:40 UTC
[log.txt](https://github.com/seerge/g-helper/files/12143035/log.txt)

**Comment by seerge** [comment] 2023-07-24 10:48
@rnylx this is direct duplicate of https://github.com/seerge/g-helper/issues/858 , try build with a fix from there

**Closed by seerge** 2023-07-24 10:48 UTC

**Comment by rnylx** [comment] 2023-07-24 11:55
thx, problem solved
