### ISSUE TITLE
keyboard effects "heatmap,GPU mode,ambient" can't work

### ISSUE THREAD

**Issue by ride-donkey** [seerge/g-helper#1769] opened 2023-12-21 15:09 UTC
[log.txt](https://github.com/seerge/g-helper/files/13743230/log.txt)
 
these keyboard effect didn't make any difference when they are chosed after my PC wakes up from hibernation.
But when I restart my computer they go work correctly.

system:windows 11  22H2 22621.2861
PC: ROG Strix G713PV_G713PV

only installed my asus, all the asus services are banned.

**Comment by seerge** [comment] 2023-12-21 15:12
@ride-donkey hello, I think I have addressed that already in latest release https://github.com/seerge/g-helper/releases/tag/v0.140 did you try that ?

**Comment by ride-donkey** [comment] 2023-12-22 10:07
[log.txt](https://github.com/seerge/g-helper/files/13751348/log.txt)
well, it doesn't seem to work.

**Comment by seerge** [comment] 2023-12-22 10:09
@ride-donkey i see that you also changed modes to others after wake up, did it help? does it help if you would set it to Static and then to Ambient again ?

**Comment by nday76** [comment] 2023-12-22 15:58
Ambient isn't working on 1.40 update.

it worked on ver 1.37 but it had a problem where the keyboard will become unresponsive for certain amount of time.

1.38 showed the same symptom if i recall.


Zephyrus M16 2023, 4080 model. GU604VZ
Windows 11 Version 10.0.22621 Build 22621

**Comment by seerge** [comment] 2023-12-22 16:08
@nday76 do you mind to post a log from 0.140

**Comment by nday76** [comment] 2023-12-22 16:16
> @nday76 do you mind to post a log from 0.140?

[log.txt](https://github.com/seerge/g-helper/files/13754188/log.txt)

this is a log from 2 days ago

and this is what I get when i switch to ambient, gpu, and heatmap mode.

12/22/2023 8:14:14 AM: NE160QDM-NM4 HDR: False
12/22/2023 8:14:17 AM: AuraMode: AMBIENT
12/22/2023 8:14:17 AM: USB 19B6: 5D-B9
12/22/2023 8:14:17 AM: USB 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
12/22/2023 8:14:17 AM: USB 19B6: 5D-05-20-31-00-1A
12/22/2023 8:14:19 AM: AuraMode: GPUMODE
12/22/2023 8:14:19 AM: USB 19B6: 5D-B9
12/22/2023 8:14:19 AM: USB 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
12/22/2023 8:14:19 AM: USB 19B6: 5D-05-20-31-00-1A
12/22/2023 8:14:22 AM: AuraMode: HEATMAP
12/22/2023 8:14:22 AM: USB 19B6: 5D-B9
12/22/2023 8:14:22 AM: USB 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
12/22/2023 8:14:22 AM: USB 19B6: 5D-05-20-31-00-1A

**Comment by seerge** [comment] 2023-12-22 16:43
@nday76 oke, but ambient mode doesn't work at all, correct ? Not only after waking up?

If so - can you check if https://openrgb.org/ is able to set colors on your device using "Direct" mode there ? 

> it worked on ver 1.37 but it had a problem where the keyboard will become unresponsive for certain amount of time.

This is the reason i tried to change it in 0.140. My assumption that on some devices, keyboards have hardware issue, when you set color all the time it also becomes unresponsive, so i tried different approach here

**Comment by nday76** [comment] 2023-12-22 16:49
> @nday76 oke, but ambient mode doesn't work at all, correct ? Not only after waking up?
> 
> If so - can you check if https://openrgb.org/ is able to set colors on your device using "Direct" mode there ?
> 
> > it worked on ver 1.37 but it had a problem where the keyboard will become unresponsive for certain amount of time.
> 
> This is the reason i tried to change it in 0.140. My assumption that on some devices, keyboards have hardware issue, when you set color all the time it also becomes unresponsive, so i tried different approach here

Doesn't seem to work. It wouldn't change anything on "Direct" mode. 
and when I use other modes from the openrgb, it turns off the lighting entirely that I have to use ghelper to reengage the lighting.

**Comment by seerge** [comment] 2023-12-22 17:58
@nday76 that's bad news :) it means that there is no open source information on how direct RGB works on M16 2023, and apparently it's different from other models ...

**Comment by mthoth** [comment] 2023-12-22 19:08
> Ambient isn't working on 1.40 update.
> 
> it worked on ver 1.37 but it had a problem where the keyboard will become unresponsive for certain amount of time.
> 
> 1.38 showed the same symptom if i recall.
> 
> Zephyrus M16 2023, 4080 model. GU604VZ Windows 11 Version 10.0.22621 Build 22621

so the unresponsive keyboard was because of g-helper i was trying for the life of me for a week straight trying to figure out why my keyboard would become unresponsive sometimes

**Comment by seerge** [comment] 2023-12-22 19:11
@mthoth that's just an assumption and only related to ambient mode (that may sets color all the time), i see few topics on reddit where people complain about same thing with aura creator. It could be just specific of the keyboard, that doesn't handle constant color changes (via commands). 

As any other mode outside of ambient don't communicate with keyboard anyhow. It's set and forget.

What model do you have and what mode did you use ?

**Comment by mthoth** [comment] 2023-12-22 19:12
> @mthoth that's just an assumption and only related to ambient mode (that may set color all the time), i see few topics on reddit where people complain about same thing with aura creator. It could be just specific of the keyboard, that doesn't handle constant color changes (via commands).
> 
> As any other mode outside of ambient don't communicate with keyboard anyhow. It's set and forget.
> 
> What model do you have and what mode did you use ?

i have the zephyrus g16 and i have ambient mode on all the time

**Comment by seerge** [comment] 2023-12-22 19:13
@mthoth does ambient mode work in 0.140 for you ? cause i have changed way color is set. And if it does - how does keyboard behave ?

**Comment by mthoth** [comment] 2023-12-22 19:14
> @mthoth does ambient mode work in 0.140 for you ? cause i have changed way color is set. And if it does - how does keyboard behave ?

when i updated ambient, heatmap and gpu mode didnt work at all i just updated a few minutes ago so idk how my keyboard behaved

**Comment by mthoth** [comment] 2023-12-22 19:19
>  i see few topics on reddit where people complain about same thing with aura creator. It could be just specific of the keyboard, that doesn't handle constant color changes (via commands).

i did switch back to aura creator briefly and set it ambient mode yesterday and my unresponsiveness did go away

**Comment by seerge** [comment] 2023-12-22 19:45
@nday76 @mthoth 

Ok, I had to debug what Armoury sends to keyboard for it's "dynamic" modes (such as ambient , etc) using my G14 2022. And did some changes. 

Try this build please, and let me know if Ambient works
[GHelper.zip](https://github.com/seerge/g-helper/files/13756325/GHelper.zip)

**Comment by mthoth** [comment] 2023-12-22 20:44
> @nday76 @mthoth
> 
> Ok, I had to debug what Armoury sends to keyboard for it's "dynamic" modes (such as ambient , etc) using my G14 2022. And did some changes.
> 
> Try this build please, and let me know if Ambient works [GHelper.zip](https://github.com/seerge/g-helper/files/13756329/GHelper.zip)

i just downloaded it and they work ill need a bit of time to determine if they still become unresponsive though

**Comment by seerge** [comment] 2023-12-22 20:49
@mthoth good to know :) but please keep in mind that if you have armoury / aura stuff running in the background, it may override settings and interfere, so it's better to stop them for a clear experiment

@nday76 can you check the build as well?

**Comment by mthoth** [comment] 2023-12-22 21:01
> @mthoth good to know :) but please keep in mind that if you have armoury / aura stuff running in the background, it may override settings and interfere, so it's better to stop them for a clear experiment

dont worry i got rid of them again 👍

**Comment by nday76** [comment] 2023-12-22 22:33
> @mthoth good to know :) but please keep in mind that if you have armoury / aura stuff running in the background, it may override settings and interfere, so it's better to stop them for a clear experiment
> 
> @nday76 can you check the build as well?

Ambient, GPU, Heatmap are all working well. :D
However, like what mthoth said, it will take time to test out the keyboard unresponsiveness.
I had a whole day or two without a problem on 1.37 until I had the problem when using Ambient.

**Comment by seerge** [comment] 2023-12-22 22:37
@nday76 well, new "method" is exactly same as Asus Aura does to set colors in real-time (i literally debugged it's protocol), so it should be identical.

It's live in 0.141 now

**Comment by nday76** [comment] 2023-12-22 23:21
> @nday76 @mthoth
> 
> Ok, I had to debug what Armoury sends to keyboard for it's "dynamic" modes (such as ambient , etc) using my G14 2022. And did some changes.
> 
> Try this build please, and let me know if Ambient works [GHelper.zip](https://github.com/seerge/g-helper/files/13756329/GHelper.zip)

Just confirmed unresponsive keyboard while using Ambient. :(

[
[log.txt](https://github.com/seerge/g-helper/files/13757266/log.txt)
](url)

**Comment by seerge** [comment] 2023-12-22 23:28
@nday76 well, then my guess is that this is how keyboard reacts when it gets commands to change color all the time (which is the whole sense of ambient) :) i assume it would be same in AC/Aura.

I don't experience it tho on my G14

**Comment by seerge** [comment] 2023-12-22 23:41
@nday76 what I can "propose" is to refresh color in ambient less frequently (every 0.5seconds instead of every 0.1)

You can try this build, it's less smooth tho :) 
[GHelper.zip](https://github.com/seerge/g-helper/files/13757310/GHelper.zip)

**Comment by nday76** [comment] 2023-12-22 23:56
> Do you have any specific scenario / conditions for that ?
It feels like it's just random. It has happened during a game(LoL, Cyberpunk, Hogwarts Legacy) and also happened when watching youtube or just idling)


>You can try this build, it's less smooth tho :)

Ill test it outt. Thanks :D

**Comment by mthoth** [comment] 2023-12-23 10:27
> @nday76 @mthoth
> 
> Ok, I had to debug what Armoury sends to keyboard for it's "dynamic" modes (such as ambient , etc) using my G14 2022. And did some changes.
> 
> Try this build please, and let me know if Ambient works [GHelper.zip](https://github.com/seerge/g-helper/files/13756329/GHelper.zip)

after some time i also got unresponsiveness with ambient mode i checked the logs too and the logs didnt write anything when the unresponsiveness happened

**Comment by seerge** [comment] 2023-12-23 10:28
@mthoth well, you can also try a build with a lower update rate :)

**Comment by mthoth** [comment] 2023-12-23 10:56
> @mthoth well, you can also try a build with a lower update rate :)

i still got the unresponsivness with the lower update rate 😓

**Comment by seerge** [comment] 2023-12-23 10:59
@mthoth may be reason is somewhere else then? :)

**Comment by nday76** [comment] 2023-12-23 11:31
> @nday76 what I can "propose" is to refresh color in ambient less frequently (every 0.5seconds instead of every 0.1)
> 
> You can try this build, it's less smooth tho :) [GHelper.zip](https://github.com/seerge/g-helper/files/13757310/GHelper.zip)

After a about 5 hours of usage, I finally got the unresponsive keyboard again. :)
I was playing Red Dead Remption 2 and became unresponsive when I went for a bathroom break.

I have theorized that the keyboard becomes unresponsive when I do not use the keyboard for a while which did happen multiple times in Cyberpunk and LoL loading screens.

**Comment by seerge** [comment] 2023-12-23 11:34
@nday76 @mthoth 

Well, it seems like you really have to try hard for that in a first place

I did one small tweak, that app would re-establish connection with keyboard every couple of minutes, mb that will "help" you somehow.

Try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/13758894/GHelper.zip)

**Comment by mthoth** [comment] 2023-12-23 17:00
> @nday76 @mthoth
> 
> Well, it seems like you really have to try hard for that in a first place
> 
> I did one small tweak, that app would re-establish connection with keyboard every couple of minutes, mb that will "help" you somehow.
> 
> Try this build [GHelper.zip](https://github.com/seerge/g-helper/files/13758894/GHelper.zip)

sad to say issue is still there 😭 i realize both me and @nday76 have 2023 models maybe that has something to do with it

**Comment by seerge** [comment] 2023-12-23 17:16
@mthoth well, i don't have any more ideas atm :) do you have backlight timeouts enabled under ``Extra`` ? if so - try to set them off (0 to both)

And also try to test armoury's aura's "ambient mode" with same fierce as you test g-helper :)

**Comment by mthoth** [comment] 2023-12-23 17:56
> @mthoth well, i don't have any more ideas atm :) do you have backlight timeouts enabled under `Extra` ? if so - try to set them off (0 to both)
> 
> And also try to test armoury's aura's "ambient mode" with same fierce as you test g-helper :)

ill try that also ill redownload amoury crate tomorrow and test it out

**Comment by naixx** [comment] 2023-12-24 01:08
I experience the same issues with ROG S17 2021, heatmap and ambient don't work

**Comment by mthoth** [comment] 2023-12-24 15:02
> And also try to test armoury's aura's "ambient mode" with same fierce as you test g-helper :)

iv been using armoury's aura's ambient mode for a good bit now and i havent had any unresponsivness. But also armoury's ambient mode is a bit broken for my model, it only takes color from top left of my screen and the colors of the keyboard are very dull

**Comment by seerge** [comment] 2023-12-24 15:11
> I experience the same issues with ROG S17 2021, heatmap and ambient don't work

@naixx don't work in what build and in what conditions ?

**Comment by naixx** [comment] 2023-12-24 16:29
@seerge yeah, sorry. I've tried 134 - there I can observe that the lightning is constant but noticeable flickering. 141 - just a plain constant color for the full keyboard no matter what is on the screen. That is ambient behavior. Heatmap - seems fine, ignore that.

**Comment by seerge** [comment] 2023-12-24 19:53
@mthoth ok. Does changing aura mode reset your keyboard "unresponsivness" ? :)

**Comment by mthoth** [comment] 2023-12-24 19:56
> @mthoth ok. Does changing aura mode reset your keyboard "unresponsivness" ? :)

while its being unresponsive and i switch it doesnt do anything i still have to wait for it come back on its own

**Comment by mthoth** [comment] 2023-12-24 21:22
> @mthoth i assume restarting app also doesn't have any effect ?

correct :(

**Comment by seerge** [comment] 2023-12-24 21:39
@mthoth well, then you can just stick to backlight modes that are working on hardware level in your case :) like all others

**Comment by mthoth** [comment] 2023-12-24 21:47
> @mthoth well, then you can just stick to backlight modes that are working on hardware level in your case :) like all others

its not ideal but thats what im gonna.

**Comment by seerge** [comment] 2023-12-25 10:05
@mthoth one more thing, that you can try - is to start Asus services (from ``Extra``) and test ambient mode after. Does it make any difference ?

**Comment by seerge** [comment] 2023-12-25 22:18
@mthoth I have one more idea, can you try this build ? 
[GHelper.zip](https://github.com/seerge/g-helper/files/13767388/GHelper.zip)

**Comment by mthoth** [comment] 2023-12-26 09:44
> @mthoth one more thing, that you can try - is to start Asus services (from `Extra`) and test ambient mode after. Does it make any difference ?

i didnt try this but im gonna test out the new build you gave now

**Comment by nday76** [comment] 2023-12-26 10:03
> @nday76 @mthoth
> 
> Well, it seems like you really have to try hard for that in a first place
> 
> I did one small tweak, that app would re-establish connection with keyboard every couple of minutes, mb that will "help" you somehow.
> 
> Try this build [GHelper.zip](https://github.com/seerge/g-helper/files/13758894/GHelper.zip)

So it has been 3 days I've been using the attached build. 
I got a unresponsive keyboard almost immediately but I wanted give another try and I haven't gotten unresponsive keyboard again yet.

**Comment by nday76** [comment] 2023-12-26 10:04
> @mthoth I have one more idea, can you try this build ? [GHelper.zip](https://github.com/seerge/g-helper/files/13767388/GHelper.zip)

I will also give this one a try.

**Comment by nday76** [comment] 2023-12-26 13:17
> @mthoth I have one more idea, can you try this build ? [GHelper.zip](https://github.com/seerge/g-helper/files/13767388/GHelper.zip)

I got unresponsive keyboard quite immediately. :(

I went back to the one that I had no problem for 3 days for now.

**Comment by seerge** [comment] 2023-12-26 13:23
@nday76 which one is that ? one with low refresh rate ?

**Comment by seerge** [comment] 2023-12-26 13:26
@nday76 try one more build
[GHelper-one-more.zip](https://github.com/seerge/g-helper/files/13771819/GHelper-one-more.zip)

**Comment by naixx** [comment] 2023-12-26 15:13
I've compiled the project and tried to debug. So the color is calculated correctly, then the results are passed to `ApplyDirect` but keyboard doesn't show any ambient color as it should from params passed. Just a fixed color. But the interesting part is that when I put a breakpoint in one place, then continued - ambient color worked! The code was not changed, only a breakpoint was set. So could it be some race condition when writing to ApplyDirect? I'm not very proficient in all that stuff, so trying to reproduce in a more stable way

**Comment by seerge** [comment] 2023-12-26 15:19
@naixx it could be that on old models payload is different, or protocol requires some additional steps, or quirks, like always sending 64 bytes, etc.

You can try to add your model here https://github.com/seerge/g-helper/blob/2bd6791edf6819c85a58131ab7624cec395a58dd/app/USB/Aura.cs#L536C25-L536C25 

This is an fall-back method for old devices, that just sets Static mode every time

**Comment by nday76** [comment] 2023-12-26 15:30
> @nday76 try one more build [GHelper-one-more.zip](https://github.com/seerge/g-helper/files/13771819/GHelper-one-more.zip)

It was the one with low refreshrate and the “ re-establish connection with keyboard every couple of minutes”

ill give the new one try!

**Comment by naixx** [comment] 2023-12-26 16:16
@seerge that works, but 1. there is a noticeable flickering, 2. only one zone/color (as expected from fallback)
But when it worked after hitting a breakpoint, it was multizone ambient color (as expected)

**Comment by nday76** [comment] 2023-12-26 16:52
> @nday76 try one more build [GHelper-one-more.zip](https://github.com/seerge/g-helper/files/13771819/GHelper-one-more.zip)

oof, got unresponsive in just an hour.

**Comment by seerge** [comment] 2023-12-26 20:21
@nday76 then you can just set different aura refresh rate for yourself, if you had better experience with low refresh before

Just open ``config.json`` and add following line to the beginning, save and restart app

```
"aura_refresh" : 1000,
```

It's time between refreshes in milliseconds. 1000 - is refresh once in a second, you can try that  or 500.
``Heatmap`` refreshes once in 2 seconds (and apparently it doesn't cause any troubles for your "responsiveness" ? 

Same applies to @naixx. If setting a breakpoint in aura-refreshes helped you, mb your device is just not comfortable with frequent updates

**Comment by seerge** [comment] 2023-12-26 21:45
And @nday76, guy you have replied on reddit uses Armoury for example and experiences same issues https://www.reddit.com/r/ZephyrusM16/comments/18r2tt2/comment/kezs9rt/

**Comment by nday76** [comment] 2023-12-27 10:58
> And @nday76, guy you have replied on reddit uses Armoury for example and experiences same issues https://www.reddit.com/r/ZephyrusM16/comments/18r2tt2/comment/kezs9rt/
> 
> P.S. Actually it's 2 users with Armoury : ![Screenshot 2023-12-26 224546]

So it must be M16 2023 model's bug I guess?

Should I request a support to Asus forum for this problem?

**Comment by seerge** [comment] 2023-12-27 10:59
@nday76 well, you can check with the if you want to :)

**Comment by seerge** [comment] 2023-12-28 19:26
@nday76 I just realised (from reddit topic), that you have replaced some internals in your laptop, and definetely disconnected battery / etc. It could be that there is some firmware glitch in your case. 

Did you also try doing [hardware reset](https://github.com/seerge/g-helper/wiki/Troubleshooting#hardware-reset--cmos-reset) ?

**Comment by nday76** [comment] 2023-12-28 23:42
> @nday76 I just realised (from reddit topic), that you have replaced some internals in your laptop, and definetely disconnected battery / etc. It could be that there is some firmware glitch in your case.
> 
> Did you also try doing [hardware reset](https://github.com/seerge/g-helper/wiki/Troubleshooting#hardware-reset--cmos-reset) ?

It was happening before the repaste unfortunately.
I haven’t tried a hardware reset but I will give it a try.

**Comment by naixx** [comment] 2024-01-02 04:35
@seerge I've tried `auto_refresh` interval, that didn't help. Still can't figure out how did I manage to make ambient light work as intended (like half of keyboard in color), fallback colorizes full keyboard only in solid color

**Comment by seerge** [comment] 2024-01-03 10:49
@naixx then it must be some differences in actual payload that is needed for your model. 

You can try to check what AC sends to keyboard in your case, using https://www.hhdsoftware.com/device-monitoring-studio  :)

**Comment by seerge** [comment] 2024-01-11 09:31
Closing this as abandoned

**Closed by seerge** 2024-01-11 09:31 UTC
Labels: question

**Comment by seerge** [comment] 2024-02-13 11:54
@nday76, @mthoth  hello, if you are still there. I was experimenting with ways to send USB commands and had one idea to test. 

Can you please check this build and see if it by any accident solves your problem ?

[GHelper.zip](https://github.com/seerge/g-helper/files/14251199/GHelper.zip)

**Comment by nday76** [comment] 2024-02-13 12:16
> @nday76, @mthoth hello, if you are still there. I was experimenting with ways to send USB commands and had one idea to test.
> 
> Can you please check this build and see if it by any accident solves your problem ?
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/14251199/GHelper.zip)

Ill try it now and give you an update.

I'll try to see if the unresponsive keyboard problem still occurs.

**Comment by nday76** [comment] 2024-02-13 13:45
> @nday76, @mthoth hello, if you are still there. I was experimenting with ways to send USB commands and had one idea to test.
> 
> Can you please check this build and see if it by any accident solves your problem ?
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/14251199/GHelper.zip)

I haven't had any issue so far past hours of trying to replicate the problem. 
(which usually just not using keyboard for few seconds to minutes triggered unresponsiveness)
 
Ill keep on testing for next few days.

may I ask what the idea was? :D

Thank you for you hard work as always!

**Comment by seerge** [comment] 2024-02-13 13:53
@nday76 "tweak" was in sending aura payload data as USB "feature" instead of USB writing (just a type of usb packet). But I tried that before in this thread.

Next to that - I have set refresh interval to 500ms (0.5s) for M16 only (also tried before)

And last - I have added a special command to Flush USB buffer after each color change (didn't try before)

I have no idea if it's combination of them , or something specific had effect. If it still goes well after some time for you, I can try to turn off first 2 "tweaks" to see if last one is the reason.

**Comment by nday76** [comment] 2024-02-13 18:21
> @nday76 "tweak" was in sending aura payload data as USB "feature" instead of USB writing (just a type of usb packet). But I tried that before in this thread.
> 
> Next to that - I have set refresh interval to 500ms (0.5s) for M16 only (also tried before)
> 
> And last - I have added a special command to Flush USB buffer after each color change (didn't try before)
> 
> I have no idea if it's combination of them , or something specific had effect. If it still goes well after some time for you, I can try to turn off first 2 "tweaks" to see if last one is the reason.

I have tested past 6 hours in every different scenarios where I experienced the unresponsiveness that I was able to replicate in other builds within an hour. So far so good. 

I can try testing the one without the first two tweaks.

Ill keep on testing since I maybe 6 hours lucky.

**Comment by seerge** [comment] 2024-02-13 18:22
@nday76 may be, cause user with a similar issue, says it still happens to him https://github.com/seerge/g-helper/issues/1911#issuecomment-1942089203

**Comment by nday76** [comment] 2024-02-13 18:42
> @nday76 may be, cause user with a similar issue, says it still happens to him [#1911 (comment)](https://github.com/seerge/g-helper/issues/1911#issuecomment-1942089203)

Man that is very sad to hear. Nevertheless, Ill keep on testing, and will give you an update if I experience a problem.

**Comment by nday76** [comment] 2024-02-13 19:37
> @nday76 may be, cause user with a similar issue, says it still happens to him [#1911 (comment)](https://github.com/seerge/g-helper/issues/1911#issuecomment-1942089203)

alright I was playing "lethal company" on steam.
my keyboard went unresponsive when I died in game and went idle for few seconds.

**Comment by seerge** [comment] 2024-02-13 19:46
@nday76 oke. So it doesn't seem to help still.

Can you try one thing - set backlight brightness to 0, but keep ambient mode ON and check if unresponsiveness happens when you go idle ?

**Comment by seerge** [comment] 2024-02-13 20:00
@nday76 this build should just stop Ambient mode changes 10 seconds after windows thinks input devices are inactive

[GHelper.zip](https://github.com/seerge/g-helper/files/14271529/GHelper.zip)

**Comment by nday76** [comment] 2024-02-14 12:02
> @nday76 this build should just stop Ambient mode changes 10 seconds after windows thinks input devices are inactive
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/14271529/GHelper.zip)

thank you!
I'am testing it now.

**Comment by nday76** [comment] 2024-02-15 08:57
> @nday76 this build should just stop Ambient mode changes 10 seconds after windows thinks input devices are inactive
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/14271529/GHelper.zip)

just got unresponsive keyboard while watching youtube on this build.
I was only idle for a minute too.

> @seerge Can you try one thing - set backlight brightness to 0, but keep ambient mode ON and check if unresponsiveness happens when you go idle ?
>

Ill test this out now

**Comment by nday76** [comment] 2024-02-15 09:36
> Can you try one thing - set backlight brightness to 0, but keep ambient mode ON and check if unresponsiveness happens when you go idle ?
> 

I set to ambient mode, turned off backlight brightness to 0 
And I immediately got unresponsive keyboard while trying to play league of legends.
I went idle during the loading screen and when the game started, keyboard didn't work :D

That was a fast easy one to test at least :P

**Comment by seerge** [comment] 2024-02-15 09:39
@nday76 ok, so looks like if backlight is OFF and you still send aura commands to it - it starts acting. Strange that build with timeout didn't help.

Do you have any asus services running in background by any chance?

**Comment by nday76** [comment] 2024-02-15 09:44
> @nday76 ok, so looks like if backlight is OFF and you still send aura commands to it - it starts acting. Strange that build with timeout didn't help.
> 
> Do you have any asus services running in background by any chance?

When I did the fresh install of windows 11, I disabled armoury crate update from BIOS, I never installed armoury crate, and disabled every asus services through Ghelper.

Only background processes that is running are Asus Hotplug Controller, and Asus Monitor Control.

**Comment by seerge** [comment] 2024-02-15 11:35
@nday76 oke, so there is no asus services trying to set backlight next to G-Helper.

Can you try this build, I have added an extra check for all color aura-commands, and they will do nothing if backlight brightness is OFF

[GHelper.zip](https://github.com/seerge/g-helper/files/14296223/GHelper.zip)

**Comment by nday76** [comment] 2024-02-15 11:58
> @nday76 oke, so there is no asus services trying to set backlight next to G-Helper.
> 
> Can you try this build, I have added an extra check for all color aura-commands, and they will do nothing if backlight brightness is OFF
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/14296223/GHelper.zip)

on it!

i just want to make sure if my testing method is correct.
I've been only switching off the exe file.
do I need to remove all files in the original folder and the appdata folder?(json file and such?)
or do they not matter as long as exe file is different?

**Comment by seerge** [comment] 2024-02-15 12:01
@nday76 no, you just replace EXE with a new one, that's it :)

**Comment by seerge** [comment] 2024-02-15 12:02
@nday76 actually, better use this build. I have added one more brightness check here ...
[GHelper.zip](https://github.com/seerge/g-helper/files/14296477/GHelper.zip)

**Comment by nday76** [comment] 2024-02-15 12:05
> @nday76 actually, better use this build instead. I have added one more brightness check here ... [GHelper.zip](https://github.com/seerge/g-helper/files/14296477/GHelper.zip)

Got it. Finding another victims while I restart my laptop and disconnect league of legends during heated teamfight as my keyboard dies! >:)

**Comment by seerge** [comment] 2024-02-15 13:28
@nday76 i'm sorry but can you use this build instead. I have found one more situation when color command would be sent to device while backlight is off.

It's actually a moment when you RETURN back to keyboard, so it would consider input being active (and start spamming colors for Ambient) but before it actually was setting backlight ON.

This build should tackle that case as well

[GHelper.zip](https://github.com/seerge/g-helper/files/14297413/GHelper.zip)

**Comment by nday76** [comment] 2024-02-15 16:41
> @nday76 i'm sorry but can you use this build instead. I have found one more situation when color command would be sent to device while backlight is off.
> 
> It's actually a moment when you RETURN back to keyboard, so it would consider input being active (and start spamming colors for Ambient) but before it actually was setting backlight ON.
> 
> This build should tackle that case as well
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/14297413/GHelper.zip)

cool. I'm testing with this one now!
I'm gonna play lethal company for a bit and see if I can trigger the problem again by purposely going idle.

**Comment by seerge** [comment] 2024-02-16 15:03
@nday76 did you manage to catch unresponsiveness with this build ? :)

**Comment by nday76** [comment] 2024-02-16 15:14
> @nday76 did you manage to catch unresponsiveness with this build ? :)

Unfortunately? Fortunately? Dont know which? Lol
But I haven’t experienced any un responsive keyboard past 12 hours playing mutilple different games and tasks. :D

**Comment by seerge** [comment] 2024-02-16 15:16
@nday76 oke! Please keep using it then

I will probably include this change in next release anyway. As it's good for all. It literally stops Ambient / Heatmap modes when backlight is off, and preserves resources for calculation.

**Comment by nday76** [comment] 2024-02-17 13:16
> @nday76 oke! Please keep using it then
> 
> I will probably include this change in next release anyway. As it's good for all. It literally stops Ambient / Heatmap modes when backlight is off, and preserves resources for calculation.

right as I was going to type, i haven't gotten a problem yet, I got the unresponsive keyboard :D

**Comment by seerge** [comment] 2024-02-17 13:18
@nday76 oke, but I assume it happens very rarely now ?

**Comment by nday76** [comment] 2024-02-17 13:39
> @nday76 oke, but I assume it happens very rarely now ?

It only happened once so I can’t say much.

**Comment by seerge** [comment] 2024-02-17 14:08
@nday76 oke! But this change is already live in https://github.com/seerge/g-helper/releases/tag/v0.154

Cause as I have mentioned, it doesn't harm anyone, only improves and saves a bit of resources.

So you can just use latest rease
