### ISSUE TITLE
Keyboard RGB not working on new 0.29 preview version (TUF A15)

### ISSUE THREAD

**Issue by LJGJM** [seerge/g-helper#88] opened 2023-03-17 08:48 UTC
Keyboard rgb doesnt work on my Asus TUF A15 2021 FA506IHRB (gtx 1650 + ryzen 5 4600h) included specs just in case. it works with a uwp app named "TUF Aura Core"

**Comment by seerge** [comment] 2023-03-17 11:35
Well, TUF Aura Core is asus own app, i would be surprised if it won't work there :) It could be that in older TUF models, way to set RGB is completely different from G14.

**Comment by LJGJM** [comment] 2023-03-17 13:10
i could do the way you wanted volunteers to test for ppt, but for this laptop and for this keyboard

https://github.com/seerge/g-helper/issues/38

**Comment by nsilvias** [comment] 2023-03-17 23:48
> Keyboard rgb doesnt work on my Asus TUF A15 2021 FA506IHRB (gtx 1650 + ryzen 5 4600h) included specs just in case. it works with a uwp app named "TUF Aura Core"

you can try using openrgb experimental branch if you dont want to use asus software. it worked for me on the asus tuf a15 2020 model.

**Comment by LJGJM** [comment] 2023-03-18 04:04
it doesnt work for me, but TUF Aura core works for me. i just want to make it work with GHelper (note: openrgb worked until i reinstalled my os)

**Comment by sklynic** [comment] 2023-03-18 04:27
Confirmed openrgb experimental working on my TUF A15 FA507RM (last time I tried stable version but don't work).

Maybe this feature could introduced by intergrating openrgb's implementation (or just package the whole openrgb-sdk?) into g-helper (if it works with most of tuf keyboard)

**Comment by LJGJM** [comment] 2023-03-18 04:44
doesnt work for me (using experimental)
![image](https://user-images.githubusercontent.com/88922474/226085161-f6f8eedb-ecbf-4f5f-b9d9-05c097a35a7d.png)
also i changed the ui of TUF Aura Core (https://github.com/LJGJM/armory-crate-replacement-for-asus-tuf-a15-f15/releases/tag/3.0)

**Comment by LJGJM** [comment] 2023-03-18 04:45
also new UI looks amazing thanks seerge

**Comment by nsilvias** [comment] 2023-03-18 05:00
> doesnt work for me (using experimental) ![image](https://user-images.githubusercontent.com/88922474/226085161-f6f8eedb-ecbf-4f5f-b9d9-05c097a35a7d.png) also i changed the ui of TUF Aura Core (https://github.com/LJGJM/armory-crate-replacement-for-asus-tuf-a15-f15/releases/tag/3.0)

go to settings > supported devices and search for asus tuf and see if they are enabled. i think i had to manually enable support.

**Comment by LJGJM** [comment] 2023-03-18 05:40
> 

nope, didnt work

**Comment by LJGJM** [comment] 2023-03-18 05:58
Please make these into GHelper performance modes

Power Saving (silent): powercfg.exe /setactive a1841308-3541-4fab-bc81-f71556f20b4a

Balanced (obvious): powercfg.exe /setactive 381b4222-f694-41f0-9685-ff5bb260df2e

High Performance (turbo): powercfg.exe /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c

**Comment by seerge** [comment] 2023-03-18 14:11
> Power Saving (silent): powercfg.exe /setactive a1841308-3541-4fab-bc81-f71556f20b4a
> 
> Balanced (obvious): powercfg.exe /setactive 381b4222-f694-41f0-9685-ff5bb260df2e
> 
> High Performance (turbo): powercfg.exe /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c

@LJGJM , that's absolutely irrelevant to a topic of RGB. And app already applies correct power schemes with each mode. You can read about them here https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/customize-power-slider

**Comment by seerge** [comment] 2023-03-19 23:45
Based on what I have found, Asus TUF has absolutely different keyboard control method. It uses WMI (same what G-Helper uses to set all performance related stuff)
https://gitlab.com/CalcProgrammer1/OpenRGB/-/blob/master/Controllers/AsusTUFLaptopController/RGBController_AsusTUFLaptopWMI.cpp

If someone who has TUF laptop and willing to extend current https://github.com/seerge/g-helper/blob/main/app/ASUSWmi.cs class with another method sending payload (from OpenRGB) to your laptop - you are free to do a fork and extend an app :)

I'm simply not able to test it anyhow as I don't have a device, and blind development is not a good idea.

So I'm closing this topic for now.

**Comment by seerge** [comment] 2023-03-24 15:28
Hello everyone,

@sklynic @LJGJM  @nsilvias I have implemented a WMI method that could potentially work for TUF laptops. Can someone volunteer and check ?

With this build. Thanks.
[GHelper.zip](https://github.com/seerge/g-helper/files/11063842/GHelper.zip)

**Comment by nsilvias** [comment] 2023-03-24 18:36
> Hello everyone,
> 
> @sklynic @LJGJM @nsilvias I have implemented a WMI method that could potentially work for TUF laptops. Can someone volunteer and check ?
> 
> With this build. Thanks.
> 
> ## [GHelper.zip](https://github.com/seerge/g-helper/files/11065265/GHelper.zip)

tried it out and after i tried to change the color of the backlight the keyboard immediately shutoff and wouldnt react even using fn + up/down to turn back on. restarted the computer and not even that got it to turn back on to give me control until i opened openrgb and used that to wake it up after which everything went back to normal. 

if anyone tries it and cant get the keyboard working again like i did i recommend disconnecting your battery as that should reset your keyboard backlight back to stock settings as thats what happens everytime i do maintence on my asus tuf a15.

**Comment by seerge** [comment] 2023-03-24 18:54
@nsilvias Ok, it's clear that it's not working as intended :) i really need access to a physical device, as doing something blind is difficult

**Comment by seerge** [comment] 2023-03-24 19:31
@nsilvias if you are still feeling adventurous tho, you can try one more build. I have adjusted some things - it may help 👍 
**[GHelper.zip](https://github.com/seerge/g-helper/files/11065989/GHelper.zip)**

**Comment by sklynic** [comment] 2023-03-25 03:34
The first build got same result as @nsilvias said. The second build change the aura mode (Static,Breathe,etc.) successfully except the RGB color.
Glad to have some progress here:)

**Comment by nsilvias** [comment] 2023-03-25 08:09
same as sklynic.

**Comment by seerge** [comment] 2023-03-25 08:51
@nsilvias @sklynic good news, can you try this build then ?

[GHelper.zip](https://github.com/seerge/g-helper/files/11068430/GHelper.zip)

**Comment by nsilvias** [comment] 2023-03-25 09:35
choosing a basic color now works. i can't choose a custom color tho.

**Comment by seerge** [comment] 2023-03-25 09:38
@nsilvias  What is "custom color"? does rainbow / strobe work ? what other modes did you guys had in armory?

**Comment by nsilvias** [comment] 2023-03-25 10:02
ghelper has an option below basic colors for custom colors and that can't be changed. 

rainbow doesnt work. dingding flashes in a single color like a turn signal on a car (i dont know if thats what its supposed to do). strobe fades into other colors while lightly changing the brightness up and down.

armoury crate had a way to choose colors using custom hex values or a color wheel that you'd drag a point around to choose your color and shade. armoury crate also had a function that controls whether the keyboard backlight was on while sleeping, turned on during boot before you entered windows, or turned on when shutting down.

**Comment by nsilvias** [comment] 2023-03-25 10:12
ok, so i tried openrgb and dingding does what strobing does in openrgb. 
color cycle in openrgb does what ghelper does in strobing mode.

openrgb also lets you control the speed of these lights in all modes so they flash much faster than in ghelper

**Comment by seerge** [comment] 2023-03-25 12:19
- Custom colors, is just a setting in a default windows colorpicker that it was using. I have unlocked that button.
 
- Modes - so actual difference is in naming. I have added a speed dropdown. And reordered/reorganized mode names, so they should match between ROG / TUF.

- As for sleeping / booting / etc settings - that's a separate topic, I also don't know how to set them even for ROG (at least for now)

You can try new build

[GHelper.zip](https://github.com/seerge/g-helper/files/11068855/GHelper.zip)

**Comment by nsilvias** [comment] 2023-03-25 12:52
everything seems to be working well except for i cant turn the backlight white anymore whether i choose from the list or use custom colors but the other colors seem to all work fine.

**Comment by seerge** [comment] 2023-03-25 15:23
Ok

- Fixed white color
- Added support for boot / awake / sleep / shutdown keyboard lightning (under Extra)
- Moved speed to Extra as well (to keep main window cleaner, as it always was for ROG keyboards)

[GHelper.zip](https://github.com/seerge/g-helper/files/11069251/GHelper.zip)

**Comment by nsilvias** [comment] 2023-03-25 16:05
> Added support for boot / awake / sleep / shutdown keyboard lightning (under Extra)

these dont seem to work. when i click any of them my backlight turns red and if press additional ones it just chnages the brightness of the red backlight slighty. i tried sleep/shutdown/fresh boot and it didnt seem to work

**Comment by seerge** [comment] 2023-03-25 16:10
Does "awake" turn off backlight completely if you check it off ?

**Comment by nsilvias** [comment] 2023-03-25 16:14
no, it just turns the backlight red

**Comment by seerge** [comment] 2023-03-25 16:20
Ok, can you try this one then ?

[GHelper.zip](https://github.com/seerge/g-helper/files/11069384/GHelper.zip)

**Comment by nsilvias** [comment] 2023-03-25 16:41
they all work now.

**Comment by seerge** [comment] 2023-03-25 16:43
Great, so now everything seem to work ?

**Comment by nsilvias** [comment] 2023-03-25 16:44
yeah, i dont see any issues

**Comment by seerge** [comment] 2023-03-25 17:06
Ok, great. It's live as https://github.com/seerge/g-helper/releases/tag/v0.39

Closing this issue then :)

**Closed by seerge** 2023-03-25 17:06 UTC

**Comment by LJGJM** [comment] 2023-03-25 19:14
Thanks seerge, just one issue, rainbow option does not do anything

**Comment by seerge** [comment] 2023-03-25 19:26
@LJGJM i know :) but it does on ROG laptops

**Comment by LJGJM** [comment] 2023-03-27 09:21
> @LJGJM i know :) but it does on ROG laptops

oh that makes sense, could you remove it on tuf laptops?
