### ISSUE TITLE
Add an option to match keyboard color with Windows accent one

### ISSUE THREAD

**Issue by kastentop2005** [seerge/g-helper#1807] opened 2023-12-29 10:23 UTC
**Is this feature request related to a problem:**
No

**Solution:**
Implement this option

**Comment by seerge** [comment] 2023-12-29 10:25
It's a duplicate of https://github.com/seerge/g-helper/issues/1130 :)

**Closed by seerge** 2023-12-29 10:25 UTC
Labels: out-of-scope

**Comment by kastentop2005** [comment] 2023-12-29 10:26
Oh alright
