### ISSUE TITLE
Charge Limit Not Working

### ISSUE THREAD

**Issue by Cmonriyu** [seerge/g-helper#2933] opened 2024-08-06 13:33 UTC
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The Charge Limit is not working with G-Helper and other applications. No Asus services are running and I've uninstalled AC and MyAsus. Smart Charging says its on but it does not stop the charging.

### How to reproduce the bug?

1. Have battery lower then set %
2. Set Charge Limit
3. Plug in

### Logs

[log.txt](https://github.com/user-attachments/files/16510870/log.txt)

### Device and Model

ASUS TUF A16 FA617NT

### Additional information.

Things Ive tried:

Disabling all Asus services using Task Manager, Task Scheduler, Msconfig and the extra on Ghelper

Doing a hardware reset where I hold the power button down for a minute or so

Going into Ghelper config and making sure that the battery limit is at 80. As well as try every point on the slider.

Use Myasus alone and close Ghelper in task manager

Use Myasus and Ghelper at the same time both at the 80%

Uninstall MyAsus and Close out Ghelper and use Asus Battery Health App instead.

Even used some random third party app to try to limit it.

Multiple Restarts along the way.
![a](https://github.com/user-attachments/assets/206dfc28-2dae-4461-84c2-90a69a9fcdb3)

### Armoury Crate

Uninstalled

### Asus Services

none

### Version

0.181

### OS

Windows 11 Home 22H2

**Comment by seerge** [comment] 2024-08-06 15:11
@Cmonriyu hello,

Does charge limit work if you would set it in MyASUS (make sure to enable all Asus services, as they are needed for MyASUS to work) and without G-Helper at all ? If not - then it's most likely something not working on firmware level in your device.

As both apps just set one setting in a same way in firware to keep this limit.

Does it keep charging to 100% or stops somewhere in-between (as it could be that battery is simply miss calibrated, and windows doesn't report actual charge correctly, like it shows 82% while in reality it's 80%).

**Comment by seerge** [comment] 2024-08-06 21:19
@Cmonriyu then it looks like it's just not working on your device in general, independently from MyASUS or G-Helper :) 

I'm afraid I can't fix that, as it's not a problem in the app. Did it ever work before ?

**Comment by seerge** [comment] 2024-08-06 21:27
@Cmonriyu try to check if there is a new BIOS updates available, that may fix charge limiter (potentially).

Closing this as the problem is not specific to G-Helper anyway.

Thanks and good luck

**Closed by seerge** 2024-08-06 21:27 UTC
Labels: question
