### ISSUE TITLE
Uncontrollable fan speed

### ISSUE THREAD

**Issue by Magniflex99** [seerge/g-helper#174] opened 2023-03-31 12:50 UTC
**Platform: Asus G532LWS 
Windows 11 Home 
GHelper version 0.44 (pre-release) 
BUG: Fan speed not controllable.** 
After selecting the TURBO mode, in which the fans are set to 100%, there is no way to decrease their rotation, selecting the other modes. I had to restart to fix the problem. To my delight or I could however 'notice that' has been added the temperature of the GPU.

https://user-images.githubusercontent.com/121835112/229124229-bb5675e0-d170-44fd-9fb1-080998784f1b.mp4

**Comment by seerge** [comment] 2023-03-31 12:58
As i understand you have applied your custom fan profiles?

Do fans work ok if you set them to something like 98% from max?

**Comment by Magniflex99** [comment] 2023-03-31 14:03
> Puoi anche provare questa build, limiterà il profilo dei fan al 99% massimo (invece di 100)
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/11122330/GHelper.zip)

I really don't think I'm having problems with my Notebook's BIOS. The only BUG that I have ever returned (even with the official software Armoury Crate) and 'that the transition from one mode' to another, the rotation curve of the fans, the fan of the CPU or GPU, suddenly stopped spinning, and then slowly resume rotation, until you get to the predetermined value, based on the temperature. I could take a look in the BIOS, I have many settings about it.

**Comment by seerge** [comment] 2023-03-31 14:05
Ok :) 

Please let me know if you are willing to do more testing and answer the question that I have asked (twice) or if I need to close this issue due to inability to reproduce. 

Thanks

**Comment by TomBonnot** [comment] 2023-04-03 01:34
I don’t want to open another ticket, but my GPU fans are going way too slow for the actual temps 
![image](https://user-images.githubusercontent.com/35734114/229392314-5942dcb5-031b-41a9-93b2-f6b299419110.png)
This way, my cpu is kinda over heating (normally I have 75-80C on my CPU and 70-75 on my GPU with the same load (Mass Effect 3))  
This is the last version

**Comment by Magniflex99** [comment] 2023-04-03 15:28
> Ok :) 
> 
> Please let me know if you are willing to do more testing and answer the question that I have asked (twice) or if I need to close this issue due to inability to reproduce. 
> 
> Thanks

With the latest version, 0.46, the previous problem has been solved for me! Profiles now all have their own fan rotation curve that works when each profile is selected. I have only one doubt left: when I select the Turbo profile, although the fan curve has all the points on both the CPU and the GPU, at most, the fans do not reach maximum rotation.

**Comment by seerge** [comment] 2023-04-03 15:32
I have limited them to 99% (since you didn't react anyhow on proposed test build to you / didn't answer my question) I still made assumption that 100% could cause incorrect bios behavior on _your_ device. 

However I'm not aware what is "maximum" rotation in your understanding, and how do you measure it :)

**Comment by Magniflex99** [comment] 2023-04-03 16:52
> Li ho limitati al 99% (dal momento che non hai reagito comunque alla build di test proposta per te / non hai risposto alla mia domanda) ho comunque ipotizzato che il 100% potrebbe causare un comportamento errato del bios sul _tuo_ dispositivo.
> 
> Tuttavia non sono a conoscenza di quale sia la rotazione "massima" nella tua comprensione e come la misuri :)?

You're right, sorry if I didn't answer you about the previous test build, which you advised me to try. I haven't let you know anything since I haven't discovered anything new these days, except that from the bios of the Notebook, unfortunately there isn't a specific option to change the management of fan rotation... I hope that the data that I will provide you now is more sufficient, in which case ask me for more information.
According to Armory Crate, my Notebook (G532LWS), has a maximum speed (100%) in rpm on the CPU of 6400 rpm, on the GPU of 6200 rpm. Activating the Turbo mode, in GHelper, despite the curve being set at 100%, the maximum rpm of the fans are not reached. 
I hope I didn't do anything wrong, in which case I apologize in advance!
It's strange, because in balanced mode, the curve works very well, and the fans add maximum rotation to them.

https://user-images.githubusercontent.com/121835112/229575780-0a200821-68b9-4a41-bab6-850a0b46d0be.mp4

**Comment by seerge** [comment] 2023-04-03 17:27
Looking at your video you have selected turbo mode, but fan profiles **are not applied** this time (auto not checked / manual "apply" button not clicked) so your fans spin according to default curve (whatever it is hardcoded in your bios / asus driver).

**Comment by Magniflex99** [comment] 2023-04-03 17:47
> Looking at your video you have selected turbo mode, but fan profiles **are not applied** this time (auto not checked / manual "apply" button not clicked) so your fans spin according to default curve (whatever it is hardcoded in your bios / asus driver) for appropriate temps (42C)

So every time I select a profile, I also have to manually apply (via the appropriate button) the relative fan curve? Am I doing this wrong?

**Comment by Magniflex99** [comment] 2023-04-03 18:59
> Se vuoi applicare la curva a ventaglio PERSONALIZZATA (quella che hai sul grafico) devi fare clic manualmente su applica (la applicherà una volta) o selezionare "applica automaticamente" e quindi applicherà la curva PERSONALIZZATA ogni volta che viene selezionato il profilo
> 
> Se la casella di controllo è deselezionata / il pulsante non viene cliccato, si attiverà semplicemente la modalità con le ventole predefinite

Understood. So it's my fault, I didn't understand how to apply the custom curve to the profile. Now I tried what you suggested, and it works. Maybe in the next build, you could bring the fan rotation value back to 100%, and if it were possible, in the case of my Notebook model, have a maximum rotation in rpm of the fans, respectively of 6400(CPU), 6100(GPU) . Lastly, I would like to understand how it is possible for the fans to spin at 2900 rpm, when according to the custom curve, they should stay close to 2200 at that temperature. What do you think?

https://user-images.githubusercontent.com/121835112/229601806-12b52354-3d44-4f40-b6a3-fe73cf2abbb9.mp4

**Comment by seerge** [comment] 2023-04-03 19:15
For me it's very difficult to see exact points on your chart, but don't expect it to follow dots super precisely. As I mentioned multiple times - app doesn't control fans, your laptop (bios) does, and it doesn't always follow that percentages exactly. There is nothing I can do here. In armory scale is much less accurate than here anyway.

I'm closings this topic,. as your issue seem to be sorted out

**Closed by seerge** 2023-04-03 19:15 UTC
