### ISSUE TITLE
Hotkeys stopped working on the newest update.

### ISSUE THREAD

**Issue by BangDen24** [seerge/g-helper#3319] opened 2024-10-28 13:29 UTC
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The Hotkey stopped working on Asus TUF FX505DD (except volume control), the hotkeys only work if i turn on the fn lock features on GHelper App.

### How to reproduce the bug?

It's not working since i updated the ghelper to v.0.197.0 fromv.0.194, reinstalling the old one also doesnt seem to fix the problem. I also tried reinstalling myasus, asus control interface and even armory crate and it still not working.

### Logs

[log.txt](https://github.com/user-attachments/files/17543024/log.txt)

### Device and Model

ASUS TUF FX505DD

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.197

### OS

Windows 11 23H2

**Comment by seerge** [comment] 2024-10-28 13:47
@BangDen24 hello, as you have correctly spotted already - reason is not the new release (especially considering that there is nothing about hotkey changed there)

If app is not getting notifications about hotkeys pressed - they won’t work.

What else did you change recently in your system? Any windows updates?

Try to do a Hard Reser as explained in the Troubleshooting section?

**Comment by BangDen24** [comment] 2024-10-28 13:51
I haven't update the windows since i turned the update option off, and i just tried hard resetting the laptop and the problem still occurs

**Comment by seerge** [comment] 2024-10-28 13:54
@BangDen24 on TUF models hotkeys notifications come as WMI events. I don’t see a single one in the log.

Try to rebuild WMI repository https://github.com/seerge/g-helper/wiki/Troubleshooting#rebuilding-wmi-repository

And also check if windows has any corrupted files

**Comment by BangDen24** [comment] 2024-10-29 10:20
i think it's a hardware issue, i've tried hard reset, rebuilding the wmi, and even reinstalling the windows and it doesnt seem to solve the problem

**Comment by seerge** [comment] 2024-10-29 10:26
@BangDen24 looks like that (or rather a "firmware" issue). Especially since windows install doesn't help.

FN-Lock is a "software" emulation by G-Helper itself - it just starts catching F1-F11 clicks and runs corresponding actions. So that will work no matter what :)

Just for a sanity check, can you start asus services from `Extra` and test if hotkeys still don't work? Cause when services are running - they are handling hotkeys

**Comment by RamseyKal** [comment] 2024-10-29 13:24
Just want to add a little comment here. When I was using Armoury Crate before uninstalling it to use G-Helper, the customizable hotkeys would occasionally stop working. Nothing I would do in Windows would make them work.

Solution was to shut down Windows and reboot. Then, they would work. Restart did not work, I actually had to shut it down. Asus software is buggy. Other people confirmed the same bug on Asus forums. I have the G18.
The worst part is that the whole keyboard would eventually stop working once the bugs began. That's how bad their system is. I had to shut it down to restore it.

I haven't used G-Helper enough to know if the same bug exists but in case you haven't shut it down yet, you may want to give it a try.

**Comment by seerge** [comment] 2024-10-29 13:27
@RamseyKal you have ROG model, keyboard there identifies itself as USB device in windows and all hotkeys send special "events" about keypress via USB (that G-Helper / AsusOptimization service listens to).

And on TUF models it's different, all hotkeys produce a WMI events . And in OP's case - there are no WMI events at all.

**Comment by seerge** [comment] 2024-10-30 07:31
@BangDen24 did you try asus services ? Also try Hard reset again (pressing power button for 40 seconds). But do it when device is not only powered off but also unplugged.

**Comment by BangDen24** [comment] 2024-10-30 07:37
I have, but it's still not working. And i found something in the event viewer that says 'code 13', though I'm not sure if it's related to this issue.
![{E2DA442D-52A5-4280-86A3-AC68B793EACC}](https://github.com/user-attachments/assets/3aa63ef1-6a33-4c54-85dc-8034ea5971e1)

**Comment by seerge** [comment] 2024-10-30 07:39
@BangDen24 can you open this Error details ? It could be errors from Asus System Control Interface driver not being able to communicate with hardware

**Comment by BangDen24** [comment] 2024-10-30 07:49
here are the details (i'm not really sure if i'm sharing the details needed) :
![{03EF5AAF-78FE-457E-981E-328B61E7837E}](https://github.com/user-attachments/assets/73ee6b91-db73-4965-a22a-1ba28c5c68b7)
`+ System 

  - Provider 

   [ Name]  ACPI 
 
  - EventID 13 

   [ Qualifiers]  49157 
 
   Version 0 
 
   Level 2 
 
   Task 0 
 
   Opcode 0 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2024-10-30T07:42:09.7927433Z 
 
   EventRecordID 23646 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  4 
   [ ThreadID]  7820 
 
   Channel System 
 
   Computer BangDen 
 
   Security 
 

- EventData 

    
   0000C00001000000000000000D0005C0000000000000000000000000000000000000000000000000809698001228FFFF0000000000000000000000000000000000000000720019030000000000000000000000000000000000000000A20A400D000000000000000000000000000000000000000012288E0000000000000000000000000000000000000000006200050000000000000000000000000000000000000000005200FFFF00000000000000000000000000000000000000007200160300000000000000000000000000000000000000000000000000000000000000000000000000000000 


--------------------------------------------------------------------------------

Binary data:


In Words

0000: 00C00000 00000001 00000000 C005000D 
0010: 00000000 00000000 00000000 00000000 
0020: 00000000 00000000 00989680 FFFF2812 
0030: 00000000 00000000 00000000 00000000 
0040: 00000000 03190072 00000000 00000000 
0050: 00000000 00000000 00000000 0D400AA2 
0060: 00000000 00000000 00000000 00000000 
0070: 00000000 008E2812 00000000 00000000 
0080: 00000000 00000000 00000000 00050062 
0090: 00000000 00000000 00000000 00000000 
00a0: 00000000 FFFF0052 00000000 00000000 
00b0: 00000000 00000000 00000000 03160072 
00c0: 00000000 00000000 00000000 00000000 
00d0: 00000000 00000000 00000000 00000000 
00e0: 00000000 00000000   


In Bytes

0000: 00 00 C0 00 01 00 00 00   ..À.....
0008: 00 00 00 00 0D 00 05 C0   .......À
0010: 00 00 00 00 00 00 00 00   ........
0018: 00 00 00 00 00 00 00 00   ........
0020: 00 00 00 00 00 00 00 00   ........
0028: 80 96 98 00 12 28 FF FF   ..(ÿÿ
0030: 00 00 00 00 00 00 00 00   ........
0038: 00 00 00 00 00 00 00 00   ........
0040: 00 00 00 00 72 00 19 03   ....r...
0048: 00 00 00 00 00 00 00 00   ........
0050: 00 00 00 00 00 00 00 00   ........
0058: 00 00 00 00 A2 0A 40 0D   ....¢.@.
0060: 00 00 00 00 00 00 00 00   ........
0068: 00 00 00 00 00 00 00 00   ........
0070: 00 00 00 00 12 28 8E 00   .....(.
0078: 00 00 00 00 00 00 00 00   ........
0080: 00 00 00 00 00 00 00 00   ........
0088: 00 00 00 00 62 00 05 00   ....b...
0090: 00 00 00 00 00 00 00 00   ........
0098: 00 00 00 00 00 00 00 00   ........
00a0: 00 00 00 00 52 00 FF FF   ....R.ÿÿ
00a8: 00 00 00 00 00 00 00 00   ........
00b0: 00 00 00 00 00 00 00 00   ........
00b8: 00 00 00 00 72 00 16 03   ....r...
00c0: 00 00 00 00 00 00 00 00   ........
00c8: 00 00 00 00 00 00 00 00   ........
00d0: 00 00 00 00 00 00 00 00   ........
00d8: 00 00 00 00 00 00 00 00   ........
00e0: 00 00 00 00 00 00 00 00   ........

`

**Comment by seerge** [comment] 2024-10-30 08:13
@BangDen24 

> The embedded controller (EC) did not respond within the specified timeout period. This may indicate that there is an error in the EC hardware or firmware or that the BIOS is accessing the EC incorrectly. You should check with your computer manufacturer for an upgraded BIOS. In some situations, this error may cause the computer to function incorrectly.

EC (Embedded Controller) is what I call here "firmware". This is what responsible for all main hardware settings on your device, including hotkey notifications.

If it's not responding - it's a firmware issue.

What is strange that Hard reset does not help, did you try it again with device being unplugged ? May be try to download other (older?) version of BIOS from Asus website and try to install that instead?

**Comment by BangDen24** [comment] 2024-10-30 08:18
I'm currently on the latest bios, is it safe if i reinstall the same bios, or just rollback to the previous version using EZFlash?

**Comment by seerge** [comment] 2024-10-30 08:19
@BangDen24 i'm not a big expert in this, but as far as you use official BIOS from asus website it should be fine.

**Comment by BangDen24** [comment] 2024-10-31 12:24
Sadly asus doesn't provide the download link for the bios anymore :(, guess i'll have to stick with ghelper app to change modes and brightness. Slight update : Volume - (Fn + F2), Volume + (Fn + F3), and Display Mode (Fn + F9) Works. and i also checked the keyboard input on"keyboard-test*space" the Volume +, Volume -, and Display Mode's input is detected.

**Comment by seerge** [comment] 2024-10-31 12:28
@BangDen24 ok, it's strange. 

`FN+F2/F3` and `FN+F9` are emitting windows media-control commands directly on hardware level. So you don't need any apps running for them to work anyway.

As for WMI / ACPI events not working - I don't have any other ideas unfortunately to suggest you. I would still try one more hard reset with laptop being unplugged tho and by pressing power button for a very long time (40+ seconds)

I'm closing this as not planned, as this is not an issue with G-Helper. But please feel free to post an update if you will figure out a fix, I might add it to the Troubleshooting or FAQ sections :)

Thanks and good luck

**Closed by seerge** 2024-10-31 12:28 UTC
Labels: question

**Comment by BangDen24** [comment] 2024-10-31 16:40
UPDATE : Finally found the BIOS file and reinstalling the bios seems to fix the issue, thanks for the suggestion earlier.
