### ISSUE TITLE
Mouse  Spatha X

### ISSUE THREAD

**Issue by Troks01** [seerge/g-helper#2102] opened 2024-02-22 09:11 UTC
### Mouse / peripheral model and version

asus rog spatha x ( model: P707 )

### Armoury Crate Screenshots

![1](https://github.com/seerge/g-helper/assets/121764219/e38095cc-2feb-4d73-b355-10eaf5fe75ae)
![2](https://github.com/seerge/g-helper/assets/121764219/f5691f49-0441-475d-a971-370a6e2b1447)
![3](https://github.com/seerge/g-helper/assets/121764219/3ff17b0f-07a2-49d9-8508-fd0094edf30b)
![4](https://github.com/seerge/g-helper/assets/121764219/7a0a8ba6-b6d1-48c6-be28-1d0e619312e3)
![5](https://github.com/seerge/g-helper/assets/121764219/34a1a262-bab5-473d-8fb2-16a08a3f68a3)
![6](https://github.com/seerge/g-helper/assets/121764219/9e3c402d-4d6c-498f-add1-7981cea5db10)

### USB Details

 ======================== USB Device ========================

        +++++++++++++++++ Device Information ++++++++++++++++++
Device Description       : USB Composite Device
Device Path              : \\?\USB#Vid_0B05&Pid_1977#6&3c64fcb&0&02#{a5dcbf10-6530-11d2-901f-00c04fb951ed} (GUID_DEVINTERFACE_USB_DEVICE)
Kernel Name              : \Device\00000038
Device ID                : USB\VID_0B05&PID_1977\6&3C64FCB&0&02
Hardware IDs             : USB\Vid_0B05&Pid_1977&Rev_0119 USB\Vid_0B05&Pid_1977
Driver KeyName           : {36fc9e60-c465-11cf-8056-444553540000}\0007 (GUID_DEVCLASS_USB)
Driver                   : \SystemRoot\System32\drivers\usbccgp.sys (Version: 10.0.19041.3636  Date: 2023-12-02  Company: Microsoft Corporation)
Driver Inf               : C:\WINDOWS\inf\usb.inf
Legacy BusType           : PNPBus
Class                    : USB
Class GUID               : {36fc9e60-c465-11cf-8056-444553540000} (GUID_DEVCLASS_USB)
Service                  : usbccgp
Enumerator               : USB
Location Info            : ROG SPATHA X
Address                  : 2
Container ID             : {bdaab010-d0b6-11ee-9828-002522c3e4fb}
Manufacturer Info        : (Standard USB Host Controller)
Capabilities             : 0x84 (Removable, SurpriseRemovalOK)
Status                   : 0x0180400A (DN_DRIVER_LOADED, DN_STARTED, DN_REMOVABLE, DN_NT_ENUMERATOR, DN_NT_DRIVER)
Problem Code             : 0
Address                  : 2
Power State              : D0 (supported: D0, D1, D2, D3, wake from D0, wake from D1, wake from D2)

        ---------------- Connection Information ---------------
Connection Index         : 0x02 (Port 2)
Connection Status        : 0x01 (DeviceConnected)
Current Config Value     : 0x01 (Configuration 1)
Device Address           : 0x02 (2)
Is Hub                   : 0x00 (no)
Device Bus Speed         : 0x01 (Full-Speed)
Number of open Pipes     : 0x04 (4 pipes to data endpoints)
Pipe[0]                  : EndpointID=3  Direction=IN   ScheduleOffset=8  Type=Interrupt  wMaxPacketSize=0x40    bInterval=1   -> 718 Bits/ms = 89750 Bytes/s
Pipe[1]                  : EndpointID=3  Direction=OUT  ScheduleOffset=8  Type=Interrupt  wMaxPacketSize=0x40    bInterval=1   -> 718 Bits/ms = 89750 Bytes/s
Pipe[2]                  : EndpointID=1  Direction=IN   ScheduleOffset=8  Type=Interrupt  wMaxPacketSize=0xB     bInterval=1   -> 224 Bits/ms = 28000 Bytes/s
Pipe[3]                  : EndpointID=2  Direction=IN   ScheduleOffset=8  Type=Interrupt  wMaxPacketSize=0x15    bInterval=1   -> 317 Bits/ms = 39625 Bytes/s
Data (HexDump)           : 02 00 00 00 12 01 00 02 00 00 00 40 05 0B 77 19   ...........@..w.
                           19 01 01 02 00 01 01 01 00 02 00 04 00 00 00 01   ................
                           00 00 00 07 05 83 03 40 00 01 08 00 00 00 07 05   .......@........
                           03 03 40 00 01 08 00 00 00 07 05 81 03 0B 00 01   ..@.............
                           08 00 00 00 07 05 82 03 15 00 01 08 00 00 00      ...............

    ---------------------- Device Descriptor ----------------------
bLength                  : 0x12 (18 bytes)
bDescriptorType          : 0x01 (Device Descriptor)
bcdUSB                   : 0x200 (USB Version 2.0) -> but device is Full-Speed only
bDeviceClass             : 0x00 (defined by the interface descriptors)
bDeviceSubClass          : 0x00
bDeviceProtocol          : 0x00
bMaxPacketSize0          : 0x40 (64 bytes)
idVendor                 : 0x0B05 (ASUSTek Computer Inc.)
idProduct                : 0x1977
bcdDevice                : 0x0119
iManufacturer            : 0x01 (String Descriptor 1)
 Language 0x0409         : "ASUSTeK"
iProduct                 : 0x02 (String Descriptor 2)
 Language 0x0409         : "ROG SPATHA X"
iSerialNumber            : 0x00 (No String Descriptor)
bNumConfigurations       : 0x01 (1 Configuration)
Data (HexDump)           : 12 01 00 02 00 00 00 40 05 0B 77 19 19 01 01 02   .......@..w.....
                           00 01                                             ..

    ------------------ Configuration Descriptor -------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x02 (Configuration Descriptor)
wTotalLength             : 0x005B (91 bytes)
bNumInterfaces           : 0x03 (3 Interfaces)
bConfigurationValue      : 0x01 (Configuration 1)
iConfiguration           : 0x00 (No String Descriptor)
bmAttributes             : 0xE0
 D7: Reserved, set 1     : 0x01
 D6: Self Powered        : 0x01 (yes)
 D5: Remote Wakeup       : 0x01 (yes)
 D4..0: Reserved, set 0  : 0x00
MaxPower                 : 0xFA (500 mA)
Data (HexDump)           : 09 02 5B 00 03 01 00 E0 FA 09 04 00 00 02 03 00   ..[.............
                           00 00 09 21 11 01 00 01 22 22 00 07 05 83 03 40   ...!...."".....@
                           00 01 07 05 03 03 40 00 01 09 04 01 00 01 03 01   ......@.........
                           02 00 09 21 11 01 00 01 22 52 00 07 05 81 03 0B   ...!...."R......
                           00 01 09 04 02 00 01 03 00 00 00 09 21 11 01 00   ............!...
                           01 22 88 00 07 05 82 03 15 00 01                  .".........

        ---------------- Interface Descriptor -----------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x04 (Interface Descriptor)
bInterfaceNumber         : 0x00 (Interface 0)
bAlternateSetting        : 0x00
bNumEndpoints            : 0x02 (2 Endpoints)
bInterfaceClass          : 0x03 (HID - Human Interface Device)
bInterfaceSubClass       : 0x00 (None)
bInterfaceProtocol       : 0x00 (None)
iInterface               : 0x00 (No String Descriptor)
Data (HexDump)           : 09 04 00 00 02 03 00 00 00                        .........

        ------------------- HID Descriptor --------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x21 (HID Descriptor)
bcdHID                   : 0x0111 (HID Version 1.11)
bCountryCode             : 0x00 (00 = not localized)
bNumDescriptors          : 0x01
Data (HexDump)           : 09 21 11 01 00 01 22 22 00                        .!...."".
Descriptor 1:
bDescriptorType          : 0x22 (Class=Report)
wDescriptorLength        : 0x0022 (34 bytes)
Error reading descriptor : ERROR_GEN_FAILURE (due to a obscure limitation of the Win32 USB API, see UsbTreeView.txt)

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x83 (Direction=IN EndpointID=3)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0040 (64 bytes)
bInterval                : 0x01 (1 ms)
Data (HexDump)           : 07 05 83 03 40 00 01                              ....@..

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x03 (Direction=OUT EndpointID=3)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0040 (64 bytes)
bInterval                : 0x01 (1 ms)
Data (HexDump)           : 07 05 03 03 40 00 01                              ....@..

        ---------------- Interface Descriptor -----------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x04 (Interface Descriptor)
bInterfaceNumber         : 0x01 (Interface 1)
bAlternateSetting        : 0x00
bNumEndpoints            : 0x01 (1 Endpoint)
bInterfaceClass          : 0x03 (HID - Human Interface Device)
bInterfaceSubClass       : 0x01 (Boot Interface)
bInterfaceProtocol       : 0x02 (Mouse)
iInterface               : 0x00 (No String Descriptor)
Data (HexDump)           : 09 04 01 00 01 03 01 02 00                        .........

        ------------------- HID Descriptor --------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x21 (HID Descriptor)
bcdHID                   : 0x0111 (HID Version 1.11)
bCountryCode             : 0x00 (00 = not localized)
bNumDescriptors          : 0x01
Data (HexDump)           : 09 21 11 01 00 01 22 52 00                        .!...."R.
Descriptor 1:
bDescriptorType          : 0x22 (Class=Report)
wDescriptorLength        : 0x0052 (82 bytes)
Error reading descriptor : ERROR_GEN_FAILURE (due to a obscure limitation of the Win32 USB API, see UsbTreeView.txt)

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x81 (Direction=IN EndpointID=1)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x000B (11 bytes)
bInterval                : 0x01 (1 ms)
Data (HexDump)           : 07 05 81 03 0B 00 01                              .......

        ---------------- Interface Descriptor -----------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x04 (Interface Descriptor)
bInterfaceNumber         : 0x02 (Interface 2)
bAlternateSetting        : 0x00
bNumEndpoints            : 0x01 (1 Endpoint)
bInterfaceClass          : 0x03 (HID - Human Interface Device)
bInterfaceSubClass       : 0x00 (None)
bInterfaceProtocol       : 0x00 (None)
iInterface               : 0x00 (No String Descriptor)
Data (HexDump)           : 09 04 02 00 01 03 00 00 00                        .........

        ------------------- HID Descriptor --------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x21 (HID Descriptor)
bcdHID                   : 0x0111 (HID Version 1.11)
bCountryCode             : 0x00 (00 = not localized)
bNumDescriptors          : 0x01
Data (HexDump)           : 09 21 11 01 00 01 22 88 00                        .!...."..
Descriptor 1:
bDescriptorType          : 0x22 (Class=Report)
wDescriptorLength        : 0x0088 (136 bytes)
Error reading descriptor : ERROR_GEN_FAILURE (due to a obscure limitation of the Win32 USB API, see UsbTreeView.txt)

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x82 (Direction=IN EndpointID=2)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0015 (21 bytes)
bInterval                : 0x01 (1 ms)
Data (HexDump)           : 07 05 82 03 15 00 01                              .......

    ----------------- Device Qualifier Descriptor -----------------
Error                    : ERROR_GEN_FAILURE  (because the device is Full-Speed only)

      -------------------- String Descriptors -------------------
             ------ String Descriptor 0 ------
bLength                  : 0x04 (4 bytes)
bDescriptorType          : 0x03 (String Descriptor)
Language ID[0]           : 0x0409 (English - United States)
Data (HexDump)           : 04 03 09 04                                       ....
             ------ String Descriptor 1 ------
bLength                  : 0x10 (16 bytes)
bDescriptorType          : 0x03 (String Descriptor)
Language 0x0409          : "ASUSTeK"
Data (HexDump)           : 10 03 41 00 53 00 55 00 53 00 54 00 65 00 4B 00   ..A.S.U.S.T.e.K.
             ------ String Descriptor 2 ------
bLength                  : 0x1A (26 bytes)
bDescriptorType          : 0x03 (String Descriptor)
Language 0x0409          : "ROG SPATHA X"
Data (HexDump)           : 1A 03 52 00 4F 00 47 00 20 00 53 00 50 00 41 00   ..R.O.G. .S.P.A.
                           54 00 48 00 41 00 20 00 58 00                     T.H.A. .X.

**Comment by Kikimahe** [comment] 2024-02-22 18:59
Hi,

You should follow this topic. #900 

I believe that the Spatha X mouse is already supported by Ghelper, thanks to @icestormNG ;-)

**Comment by Troks01** [comment] 2024-02-23 06:13
Apparently there are differences between spatha and spatha x
What doesn't work:
The DPI settings are only on 2.4, they are not available via cable.
The backlight settings do not work on cable or without cable.
Button assignment worked only on m1 and m2, after installing ARMOURY CRATE, reassignment stopped working on all buttons.
ARMOURY CRATE has been completely removed.
I'm sorry for my English

**Comment by IceStormNG** [comment] 2024-02-23 22:38
I remember that there were some issues and the original requestor said it is "good enough" for them.
It is indeed the Spatha X that is implemented, but it has some weird behavior when comparing cable and 2.4Ghz, which is usually the same for mice, just not on this one. Likely due to the dock feature.

Button assignment is not implemented at all yet in GHelper, so this for sure will not work.

The lighting should work though, at least either wired or wireless.

This is a test build with additional logging enabled.

[GHelper.zip](https://github.com/seerge/g-helper/files/14390647/GHelper.zip)

Please try to change the DPI and the lighting and then hit the sync button after each step to let it read the mouse data again.
Please send me the GHelper log afterwards so I can check what is going on there.

**Comment by seerge** [comment] 2024-02-27 12:42
@Troks01 did you had a chance to try the build ?

**Comment by seerge** [comment] 2024-03-05 23:01
@Troks01 hello, did you had a chance to try the build with the fixes ? 
https://github.com/seerge/g-helper/files/14390647/GHelper.zip

**Comment by seerge** [comment] 2024-03-19 16:49
Closed as abandoned

**Closed by seerge** 2024-03-19 16:49 UTC
Labels: question

**Comment by SuperG8571** [comment] 2024-06-15 12:26
## Spatha X can not be identified correctly via cable

### Rules
I made myself familiar with the [Readme](https://github.com/seerge/g-helper?tab=readme-ov-file), [FAQ](https://github.com/seerge/g-helper/wiki/FAQ) and [Troubleshooting](https://github.com/seerge/g-helper/wiki/Troubleshooting).
I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?
My mouse Spatha X is identified via wireless and its settings is worked correctly, but is not identified via wired.

### How to reproduce the bug?
Plug in the 2.4Ghz Dongle regardless of whether pairing is completed or not, the control panel will display the mouse. And I can use the settings freely after pairing. Plug in the cable linked with the mouse directly, the control panel do not display the mouse.

### Logs
[log_unmodified.txt](https://github.com/user-attachments/files/15847583/log_unmodified.txt)
[log_modified.txt](https://github.com/user-attachments/files/15847585/log_modified.txt)

### Device and Model
Asus ROG Strix SCAR 17 G733ZX

### Additional information.
The origin G-Helper runs with Microsoft Windows Desktop Runtime - 7.0.19 (x64).
I originally tried to solve this issue on my own and I noticed that .NET 7 was no longer unsupported. Then I bulit the software with Microsoft .NET SDK 8.0.300 (x64) from Vsiual Studio. And I made the following changes.

1. SpathaX.cs: public SpathaX() : `base(0x0B05, 0x1979, "mi_00", true)` => `public SpathaX() : base(0x0B05, 0x1977, "mi_00", true)`
2. global.json: `"version": "7.0.406"` => `"version": "8.0.300"`
3. Logger.cs: `public static string logFile = appPath + "\\log.txt";` => `public static string logFile = appPath + "\\log_modified.txt";`

I found that the mouse was identified after point 1. Also, it was unidentified via wireless. For point 2, the G-Helper could be built and work both in the environment .NET 7 and .NET 8. I tried both of them. Because of the conflict of the log file names, I did point 3. The file log_modified.txt is the log with all the changes. log_unmodified.txt is original. And maybe I should contact @IceStormNG.

### Armoury Crate
Uninstalled

### Asus Services
0

### Version
0.176

### OS
Windows 11 23H2
