### ISSUE TITLE
iGPU undervolting doesn’t work in G14 2021 version

### ISSUE THREAD

**Issue by TomBonnot** [seerge/g-helper#645] opened 2023-06-18 15:40 UTC
**Describe the bug**
Log says "CMD_REJECTED_PREREQ" when setting undervolt for the iGPU. but "OK" for CPU undervolt, does it needs further reaserch that I can help for, in order to find a solution for that ?

**Clear scenario to Reproduce**
1. Go to Vents and Power, then CPU
2. Set iGPU undervolt to anything you want (in my case -10)
3. Check GHelper logs

**Expected behavior**
log saying "OK" for "iGPU UV"

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11781982/log.txt)

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/35734114/c10310f9-9b06-4103-b868-610517cfd6f5)

**Desktop (please complete the following information):**
 - OS: Windows 11, version 22H2
 - Laptop model : ROG Zephyrus G14 GA401QM

**Asus software**
Debloated completely

**Comment by seerge** [comment] 2023-06-18 15:43
@TomBonnot i think iGPU just can't be undervolted in your case (and from other reports it seem to be very frequent).

**Comment by seerge** [comment] 2023-06-18 16:25
Closing as it's not a bug :)

**Closed by seerge** 2023-06-18 16:25 UTC

**Comment by TomBonnot** [comment] 2023-06-18 16:38
yes of course, you are right ! 
Alright, I don’t know if we could help you in anyway to find a way. But maybe as you said it’s just impossible on many devices. 
Anyway, thank you for your time and your app !
