### ISSUE TITLE
Rog Strix Impact II side button support within ghelper.

### ISSUE THREAD

**Issue by arjun7809** [seerge/g-helper#3082] opened 2024-09-09 02:36 UTC
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Although, Ghelper supports my Rog Strix Impact II mouse but I want to use my side buttons ( for e.g I can use them for volume up & down or some custom in game action like changing weapon). Kindly, add the feature to customize the side buttons for customizable actions. 

### Describe the solution you'd like

I want that both of the side buttons can be customized for the action I'm gonna assign.

### Device and Model

Asus Rog Strix Impact II 

### Additional information.

![mouse](https://github.com/user-attachments/assets/8b0c5c9e-8349-44c7-8929-29ceded6ca5e)

**Comment by seerge** [comment] 2024-09-09 07:52
@arjun7809 hello, this is a duplicate of [an existing post here](https://github.com/seerge/g-helper/issues/2940). Please check response there. Thanks

**Closed by seerge** 2024-09-09 07:52 UTC
Labels: duplicate
