### ISSUE TITLE
Start-up sound

### ISSUE THREAD

**Issue by ItxWeird** [seerge/g-helper#1199] opened 2023-08-28 03:25 UTC
**Is your feature request related to a problem? Please describe.**
After updating my bios, the ROG startup sound has come back, and the only way I know of removing it is through armory crate

**Describe the solution you'd like**
Just like armory crate, implement a toggle for the startup sound

**Describe alternatives you've considered**
The easiest way to fix this would be to install armory crate, but g-helper is supposed to be a replacement for armory crate

**Comment by seerge** [comment] 2023-08-28 09:44
@ItxWeird  hello,

This is a duplicate of https://github.com/seerge/g-helper/issues/355 and https://github.com/seerge/g-helper/issues/261

I don’t know endpoint responsible for that :)

**Closed by seerge** 2023-08-28 09:44 UTC

**Comment by seerge** [comment] 2023-09-07 15:31
@ItxWeird added in https://github.com/seerge/g-helper/releases/tag/v0.120
