### ISSUE TITLE
No more rainbow option in the laptop keyboard section?

### ISSUE THREAD

**Issue by wyascorn** [seerge/g-helper#1050] opened 2023-08-10 23:28 UTC
Cant really find the option anymore instead its just these 4

Img; 
![image](https://github.com/seerge/g-helper/assets/84992554/6ff44e59-b1b7-45d3-8070-7dfe730d4ec0)

I used to have it before but after some ghelper update the options disappeared

**Comment by seerge** [comment] 2023-08-11 08:48
It’s a duplicate of https://github.com/seerge/g-helper/discussions/1033 just download latest v0.108

**Closed by seerge** 2023-08-11 08:48 UTC
