### ISSUE TITLE
Asus Two way Noice cancellation

### ISSUE THREAD

**Issue by fayizshaffaq** [seerge/g-helper#2726] opened 2024-06-13 08:49 UTC
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

armoury crate allows you to use the dedicated hardware for noice cancelation without using the cpu or gpu. but unfortunately its not available in ghelper..Yet? 

### Describe the solution you'd like

I'd love for way to turn on asus Noise cancellation. 
there used to be a standalone app for this but then they intergrated it into armoury crate . 
this is the standalone software that used to work. 

https://dlcdnets.asus.com/pub/ASUS/Accessory/Headset/AI_Noise-Canceling_Mic_Adapter/ASUS_AI_Noise-Cancelling_Mic_Adapter_v1.00.01.zip

### Describe alternatives you've considered

couldn't find any alternatives. 

### Device and Model

FX507ZE TUF 2022  12700H 3050ti 

### Additional information.

![image](https://github.com/seerge/g-helper/assets/66478077/ff893233-9c6b-4297-910c-0a4e4ea178b8)

**Comment by seerge** [comment] 2024-06-13 08:50
@fayizshaffaq hello, this is a duplicate of another topic https://github.com/seerge/g-helper/issues/18 

Please check it for more info

**Closed** 2024-06-13 08:50 UTC
Labels: duplicate
