### ISSUE TITLE
Rework update process

### ISSUE THREAD

**Issue by bel57** [seerge/g-helper#2251] opened 2024-03-19 20:02 UTC
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Please rework update process! My computer was idle for a few hours, I left it running with a stream tab open to snag a special drop. I came back to an unexpected dimmed with UAC prompt from none other than GHelper -so all tasks behind this overlay were frozen as is. You can't do that, Ghelper shouldn't trigger UAC without a user action first.
Please rework that process by **not triggering UAC prompts without warning/asking first**. Also change the way GHelper advertises a new update by **switching from random popup to normal Windows notification banner**. That would be great to add a setting/user preference checkbox for 1- update available alert 2-download and install update automatically. 0.154.0 > 0.158.0

### How to reproduce the bug?

Leave GHelper running while an update is available. UAC will get in the way out of nowhere.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14655689/log.txt)

### Device and Model

ROG Zephyrus G14 GA401IU

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.154.0 > 0.158.0

### OS

Windows 11 23H2 (22631.3296)

**Comment by seerge** [comment] 2024-03-19 20:14
@bel57 hello

App would ask for admin rights only if some of user actions require that (for example setting core clock offset for Nvidia). But this happens when you interact with the app, as it doesn't do anything in background

This is also not connected with update check anyhow

As for notification about available update - its windows native alert, and I think it does its job just fine. App uses alert in multiple different cases as well, and I don't see any point in replacing it only for updates

Thanks

**Comment by bel57** [comment] 2024-03-19 20:17
Hmm I assure you that I left the computer open with the browser open, didn't touch it for hours, and I came back to UAC prompt. I did nothing to trigger that, it happened all by itself.
When I accepted, behind it was the update popup, and the update launched instantly after that.
You don't see the issue with random popup alert? Why not use the normal Windows banner showing up in bottom right corner instead? Most apps do that.

**Comment by seerge** [comment] 2024-03-19 20:22
@bel57 as I have told admin access will be asked as a result of user action :) do you have any kind of automation software running?

**Comment by seerge** [comment] 2024-03-19 20:30
@bel57 update checker runs only on app start and when main window is shown (but not more often than once in 12 hours). So even alert won't pop up by itself, but as a result of user action

Any chance something in your system started app again while you were away?

Do you have any binding that would start app? 

Can you upload config.json here as well?

**Comment by seerge** [comment] 2024-03-19 20:37
@bel57 

```
19/03/2024 15:16:07: ------------
19/03/2024 15:16:07: App launched: ROG Zephyrus G14 GA401IU_GA401IU :0.154.0.0fr-FR.
```

Who started app at this time? This is BEFORE update prompt

**Comment by bel57** [comment] 2024-03-19 20:43
No binding/shortcut to GHelper, it runs automatically on startup and that's about it, I don't interact with it.
The icon sits in the tray area. Here's config file attached.
[config.json](https://github.com/seerge/g-helper/files/14656388/config.json)
Came back at 15:15:51 monitor power on is when I fired up the screen and jiggled mouse to wake up the computer from idle state. I repeat, I didn't click on GHelper shortcut. First thing on screen was UAC prompt taking full screen. I accepted because I thought GHelper had a good reason to ask for it. Then the update popup was there as well, which I accepted too. 🤔 Btw I checked my antivirus logs, nothing. Same for Windows events. I'm clueless.

**Comment by seerge** [comment] 2024-03-19 20:49
@bel57 

19/03/2024 15:15:51: Monitor Power On
19/03/2024 15:15:51: AutoSetting for Online
19/03/2024 15:15:51: Mode = 0 : OK
19/03/2024 15:15:51: Eco flag : -65536
19/03/2024 15:15:51:Mux flag : -65536
19/03/2024 15:15:51: GET CLOCK LIMIT: 0
19/03/2024 15:15:51: GET GPU CLOCKS: 0, 0
19/03/2024 15:15:51: SET GPU CLOCKS: 100, 100
19/03/2024 15:15:51: SET GPU CLOCKS: NVAPI_INVALID_USER_PRIVILEGE

I see that at 15:51 laptop was woken up (by something), and then G-Helper have re-set last used settings for current active mode (thats by design) , including gpu overclocking, which failed cause app was not running as admin - so that triggered UAC at 15.51 (otherwise it won't be possible to set clocks)

And as I have mentioned - its not related go update alert

Alert appeared AFTER you have restarted app as admin (cause on new start it checked for updates). And it is a consequence of a app restart, not a reason for UAC

**Comment by bel57** [comment] 2024-03-19 20:52
Interesting. No idea why the app wasn't running as admin. I have no other tool that could conflit with GHelper, that software is the only thing managing the computer behavior. I double checked and no ASUS process was detected.

**Comment by seerge** [comment] 2024-03-19 20:56
@bel57 ok, but to answer your main question - UAC popped up only after you interacted with laptop, and as a result of failed attempt to overclock according to your settings 

To make sure that startup task is with admin rights - just uncheck and check again startup checkbox while app is already running as admin. it would recreate it if by some reason it didn't happen automatically

**Comment by bel57** [comment] 2024-03-19 21:06
Alright, many thanks for the tip and thorough explanations, I've done as instructed, hopefully that will fix it. 👍
I'd really like an alternative to the update popup, don't think I'm the only user bothered by that. But I understand if you'd rather not change it.

**Comment by seerge** [comment] 2024-03-19 21:08
@bel57 native alert is more prominent and doesn't disappear with time, so I would prefer to keep it.

After all I'm trying to push new auto updates only each 3-4 weeks

Closing as resolved as whole issue was not caused by update in a first place

**Closed by seerge** 2024-03-19 21:08 UTC
Labels: answered
