### ISSUE TITLE
Custom fan curve GPU Fans Not Spinning When XG Mobile Connected

### ISSUE THREAD

**Issue by jurecapuder** [seerge/g-helper#1123] opened 2023-08-18 16:18 UTC
**Description**
I am encountering a perplexing issue with the G-Helper tool on my Asus ROG Flow X13 (2022 model) laptop when connecting my external GPU, the XG Mobile (RX 6850M XT). The G-Helper tool is intended to act as a lightweight control alternative for Asus laptops, facilitating effective management of the hardware components. However, it's failing to activate the GPU fans when the external GPU is connected to the system.

**Clear scenario to Reproduce**
1. Connect the XG Mobile (RX 6850M XT) external GPU to the Asus ROG Flow X13 laptop.
2. Launch the G-Helper tool.
3. Monitor the GPU temperature and fan behavior through the G-Helper interface.

**Expected behavior**
Upon connecting the external GPU, the G-Helper tool should promptly detect its presence and initiate the spinning of the GPU fans at an appropriate speed, regardless of the current temperature. This proactive fan control is crucial to maintain optimal thermal conditions and prevent overheating.

**Actual behavior**
Unfortunately, the G-Helper tool is not effectively starting the GPU fans when the external GPU is connected. This oversight results in the GPU fans remaining inactive until the temperature reaches a critical threshold, which can potentially lead to severe thermal throttling or, in some cases, an automatic system shutdown.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12381209/log.txt)

**Desktop:**
 - OS: Windows 11
 - Laptop model: ROG Flow X13 GV301RC

**Asus software**
- G-Helper with 0 serices running in the background
- MyASUS installed

**Additional context**
While the issue doesn't consistently occur upon connecting the XG Mobile, it appears to happen intermittently. In recent instances, I noticed that the GPU fans failed to engage even though the XG Mobile was connected, leading to rising temperatures within a short span. For example, during one occurrence, I had only connected an HDMI cable to the XG Mobile. After approximately half an hour to an hour of usage, I observed that the GPU temperature had climbed to the mid-80s Celsius, despite the fans remaining inactive.

Another noteworthy incident involved launching a game. Upon starting the game, I noticed an abrupt spike in GPU temperatures, which escalated rapidly. This ultimately led to the GPU disconnecting, likely due to reaching a critical thermal threshold. Unfortunately, the logs provided don't extend beyond yesterday's date, limiting the available information for diagnosis.

This variable behavior indicates that the issue isn't tied to a specific trigger, but rather occurs intermittently during different usage scenarios. It's worth noting that during these instances, I had ensured the G-Helper tool was active and running, yet the GPU fan control remained inactive.

This additional context highlights the sporadic nature of the issue and provides specific examples of scenarios where the problem occurred. It also emphasizes the observations you made during different situations, further aiding the maintainers in understanding the issue's complexity and potential triggers.

**Comment by seerge** [comment] 2023-08-18 16:21
@jurecapuder hello,

G-Helper doesn't start or stop your fans, they are controlled by hardware and bios. It's same for all cases. Maximum it can do - is to set a different performance mode or set a custom fan curve.

How does your XG Mobile behave when you have AC running ?

**Comment by jurecapuder** [comment] 2023-08-18 16:33
@seerge Hi,

Apologies on missunderstanding the fan controls.

1. The XG Mobile behaves normally

**Comment by jurecapuder** [comment] 2023-08-18 16:42
Reopening this issue due to an accidental misclick.

The XG Mobile operates as expected during normal usage. The custom fan curve I've configured serves the specific purpose of cooling both my laptop and XG Mobile after terminating resource-intensive tasks. I rarely employ this configuration, and aside from these instances, the G-Helper functions without any hitches. The problem I'm highlighting only came to my attention last week when I encountered the issues.

In order to prevent a recurrence of the issue, I will diligently follow the steps outlined in [#881](https://github.com/seerge/g-helper/issues/881).

Thank you for your understanding and assistance.

**Comment by seerge** [comment] 2023-08-18 16:49
@jurecapuder so it's only when you set a custom curve it stops? with default one it runs fine ?

**Comment by jurecapuder** [comment] 2023-08-18 16:54
@seerge Based on the information provided in the [#881](https://github.com/seerge/g-helper/issues/881) issue, it appears that connecting the XG Mobile with the custom fan curve active results in the described behavior. In this scenario, altering the fan modes does not alleviate the situation. As far as I'm aware, the options to prevent any adverse outcomes are either to quickly disconnect the XG Mobile if feasible, or to wait for its unfortunate malfunction.

Thank you for your attention to this matter. Your insight is greatly appreciated.

**Comment by seerge** [comment] 2023-08-18 17:15
@jurecapuder try this build

It will send a reset fans command to XGM every time it's disconnected or connected. So every time XGM will be shut down- it will be disconnected with default fans.

It probably won't fix already problematic state, but I wonder if it will prevent it from happening.

[GHelper.zip](https://github.com/seerge/g-helper/files/12381555/GHelper.zip)

**Comment by jurecapuder** [comment] 2023-08-18 17:19
@seerge Thank you so much for your quick response and the effort you've put into addressing this issue. I really appreciate your suggestion to try the new build with the reset fans command for the XG Mobile. I'll definitely give it a shot and test it thoroughly over the next few days. Your proactive approach to finding a solution is truly commendable.

I'll keep you updated on the results after the testing period. Once again, thank you for your time and assistance. It means a lot to have your support in resolving this matter.

**Comment by AudreyAP** [comment] 2023-08-18 19:48
> This additional context highlights the sporadic nature of the issue and provides specific examples of scenarios where the problem occurred. It also emphasizes the observations you made during different situations, further aiding the maintainers in understanding the issue's complexity and potential triggers.

Are you using chatgpt? This is really not helpful... It's just making your messages extremely long and difficult to read.

**Comment by jurecapuder** [comment] 2023-08-18 20:11
Yes :)

**Comment by Mikealll** [comment] 2023-08-20 00:25
I have this issue only if a custom fan curve is applied. If I connect the Xgm default fan curves will work as expected but custom fan curves will result in 0 fan spin. However, once I shutdown and power back on (or hibernate) custom fan curves work as intended. 

Interstingly I have found that closing G-helper and opening it again (clicking exit on taskbar icon and reopening) can also fix this issue after Xgm is connected.

Using 2022 X13 with newest Bios and 3080Xgm with newest firmware. Will test custom build and get back some time today thanks @seerge

**Comment by seerge** [comment] 2023-08-20 08:16
@Mikealll if restarting the app “helps” does unchecking and checking apply in fans help as well?

**Comment by Mikealll** [comment] 2023-08-20 23:01
Hi @seerge I have just ran through everything.

* Computer on and connect Xgm toggling lock
* Switch from Eco to Standard and then toggle Xgm
* Xgm connects, however GPU temp still displays iGPU temp not XGM
* No fan spin (in silent mode where xgm is set to run at 1% with custom fan curve)
* Tried toggling off apply custom fan curve. Xgm fan will ramp up (as temp at this point is above 57c for default fan curve)
* Upon toggling back on Xgm fan turns off again
* Exiting G Helper (ending task in task manager) and reoppening does not fix the issue but does display the correct GPU temp|
* Hibernating or shutting down resolves the issue (restarting and sleep do not, believe as Xgm is still in a powered state?)
* Custom build exhibits the same behavior with no changes

Tested on Build 112 (same behavior on prior builds) and custom build from earlier in this thread). Sorry for the hassle I know the Xgm is just spaghetti code and weird behavior. Mine also sometimes oscilates fan rpm rather than staying constant at random on boot, but it also did this with armoury crate and hibernating and shutting down also fixes that so I am used to it.

**Comment by seerge** [comment] 2023-08-20 23:11
@Mikealll so restarting app actually doesn't help in contrary to what you thought originally ? 

If it's indeed the case, it's probably some unknown to me initialisation payload that AC can send to XGM to "wake it up" for custom modes as I assumed in https://github.com/seerge/g-helper/issues/881#issuecomment-1652427829 The only way to get it - is to intercept it via USB monitoring. But cause I don't have a device (neither X13/X16 nor XGM itself) i can't do that :)

**Comment by Mikealll** [comment] 2023-08-20 23:33
@seerge Yeah with the restarting thing, I believe I must of decided to play a game or something after (where I used balanced with default fan curve) and not connected that it wasnt a custom fan curve. I am happy to try take some usb log file for you but am good with hardware not software haha.

**Comment by seerge** [comment] 2023-09-03 16:19
@Mikealll if you want to help - you can try to follow instruction that I have listed here https://github.com/seerge/g-helper/issues/729#issuecomment-1704314691 (it's different case, but reasons are same)

**Comment by seerge** [comment] 2023-09-04 14:22
@jurecapuder @Mikealll I have added a special "initialization" commands to XGM thanks to @Wolper321 .

App would send them on start + every time you actually activate XGM

Can you check this build and see if it solves your issues ? 

[GHelper.zip](https://github.com/seerge/g-helper/files/12514554/GHelper.zip)

**Comment by jurecapuder** [comment] 2023-09-04 16:54
@seerge Using this latest build, I tried a few times connecting the XGM with the custom fan curves and hitting the GPU and to me it seems that the issue is solved!

**Comment by seerge** [comment] 2023-09-04 17:03
@jurecapuder glad to hear!

**Closed** 2023-09-06 08:09 UTC
Labels: help wanted, question

**Comment by moritzbeck01** [comment] 2023-09-08 19:10
I'm gonna hijack this since many XG Mobile owners are here: Do you also sometimes have the problem that the fans keep ramping up and down? This only happens when I apply a fan curve, default ones don't seem to do this. I'm assuming the error is on my end, but I can't figure out where.

**Comment by jurecapuder** [comment] 2023-09-08 19:26
The mentioned problem hasn't happened to me. Maybe check if you have any conflicting files that would fight over the fan control.

**Comment by moritzbeck01** [comment] 2023-09-08 20:05
Thing is, it also used to happen with AC, but only sometimes, so I'm really at a total loss here.

**Comment by jurecapuder** [comment] 2023-09-08 20:54
@moritzbeck01  I only have one custom and it's literally just putting fans to max from the lowest temp

**Comment by Wolper321** [comment] 2023-09-09 08:30
I have it from time to time and not only on custom curve. The AC had exactly the same problem and I am not sure what was causing it. Turbo mode and fans are lound and XGM sits at 40ish °C while it suppose to be silent. Switching to balance and the fans are off, going back to turbo and the fans remain off. My only suspicion is that the Windows standby messes with it.

**Comment by jurecapuder** [comment] 2023-09-09 11:48
@Wolper321 I think in the past BIOS updates the modern standby was really messed up and it would always make my laptop crash after putting it up sleep and then opening it up. The fix I found was to find a guide on how to disable it, ever since I did that I had no troubles with it.

**Comment by Wolper321** [comment] 2023-09-09 14:32
ASUS optimization service wouldn't allow me to turn off the sleep. But now I have the problem that hibernate after doesn't work. In general, I have noticed that the system is overall more stable with XGM when the sleep is off. The Freesync monitor is not black screening and no need to hard reboot since there is no sleep.
