### ISSUE TITLE
GPU fan not working on G15 2022 (3070 ti) model

### ISSUE THREAD

**Issue by JDevMen** [seerge/g-helper#114] opened 2023-03-21 01:14 UTC
**Describe the bug**
GPU fan won't work after uninstalling Armoury Crate and installing G-helper

**To Reproduce**
1. Uninstall Armoury Crate
2. Fresh install G-helper
3. Change PPT higher than default settings.
4. Open a GPU intensive app

**Expected behavior**
GPU fan should spin accordingly to the fan curve set.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Windows 11 v22H2 64bit
 - Asus ROG G15 3070Ti (2022) model
 - G-helper version 0.32
 
**Additional context**
I uninstalled Armoury create and installed G-helper. Restarted the laptop and started using it when I noticed my GPU performance was sub-par. Checked on G-helper interface and looked like GPU fan was not spinning which meant that it was thermal throttling. Tried going back to default settings after changing PPT and fan curve for the CPU but still nothing. I checked by placing my hands on both exhaust ports and confirmed only CPU fan was working.

**Comment by seerge** [comment] 2023-03-21 01:19
Did you apply any fan curves ? try rest to defaults and apply only PPTs (keep fan apply checkbox empty)

**Comment by HamzaYslmn** [comment] 2023-03-21 11:41
Try this configuration.
[config.zip](https://github.com/seerge/g-helper/files/11027783/config.zip)


<img width="291" alt="image" src="https://user-images.githubusercontent.com/78810304/226595188-d5fb8190-b883-4981-8cd4-4c817f6e7947.png">

The fan curve options don't work properly on my computer either. 
The 1st fan curve button does nothing. The fans start working on 3rd and onwards.

For example, in the curve I posted, it should work normally until the cpu drops to 20 degrees, but it shuts off at 49. Button 2 acts like button 1.
In the gpu part, the 3rd button acts like the 1st button.
In the example I posted, normally the fan should turn off when the Gpu reaches 55 degrees, but it doesn't :D, it turns off when it drops below 59 degrees. The speed curve between 55-59 does not work. normally it should have RPM values like 2400-2200-2000-1800-1600-800-0. But it works like this. 2400-0

**Comment by luckyth13teen** [comment] 2023-03-23 19:46
Note:
I also had this same issue when I initially installed, issue was temporarily resolved with restart, unable to reproduce consistently but seemed to trigger after some time if I had toggled between iGPU and dGPU modes. 

Have not been able to reproduce since 0.38

**Comment by seerge** [comment] 2023-03-23 19:49
@luckyth13teen ok, same question to you - do you apply any fan profiles ? (as soon as you tick "auto apply" or click "apply" button asus bios considers that as a "custom" fan profile, no matter how similar it is to defaults)

**Comment by luckyth13teen** [comment] 2023-03-23 19:53
I am almost positive I had a custom profile by those definitions on all three profiles (pretty sure I toggled the auto apply on as a first step when setting up)

I as a quick fix attempted to change the fan curves manually while the issue was in effect. 

With the auto apply toggled on:
no change

with the auto apply toggled off and pressing the apply button:
no change

Clicking the factory defaults:
no change

**Comment by seerge** [comment] 2023-03-23 19:55
For me it's very difficult to judge. May be your bios has a bug when a custom fan profile was applied? I would try to keep fan profiles default then (when nothing applied - bios uses defaults).

**Comment by luckyth13teen** [comment] 2023-03-23 19:58
Like I said before haven't seen it since but maybe a nice feature for ease of mind could be an alert of some sort:
if gpu temp >84f 
if gpu fan = 0 
alert
else

that would be a nice safety net?

**Comment by seerge** [comment] 2023-03-23 20:04
Currently app doesn't check / monitor GPU temps unless it's windows is open (to be resource savvy as much as possible).
If you will find any specific pattern that leads to gpu fan not working on your laptop - let me know, then we can try to think about a solution.

General note : g-helper is not a low level system monitoring tool. It even doesn't control fan speeds. It just can (optionally) set a custom fan curve (consisting of 8 points) to asus bios via same endpoint as armoury crate does. The rest is on bios (and that's a good thing in general).

**Comment by seerge** [comment] 2023-04-04 14:53
Seems like author of original post have disappeared + there is no clear reproduction scenario - therefore i'm closing this issue.
Feel free to make a new post if you will find specific pattern to reproduce, and please include log from ``%AppData%\GHelper``

**Closed by seerge** 2023-04-04 14:53 UTC
