### ISSUE TITLE
Keep GPU enable in Optimized mode when connected to External GPU.

### ISSUE THREAD

**Issue by MrxSiN** [seerge/g-helper#1228] opened 2023-08-31 16:36 UTC
Is it possible to keep GPU Enable in Optimized mode when connected to External GPU after unpluged the charger?

Also, if possible, when on battery in Optimized mode, when connected to external display, automatically enable GPU?

**Comment by seerge** [comment] 2023-08-31 18:08
@MrxSiN what is External GPU ? XG-Mobile or eGPU in a container ?

**Comment by MrxSiN** [comment] 2023-09-01 00:39
Ah typo. I mean when connected with external monitor

**Comment by seerge** [comment] 2023-09-01 06:55
@MrxSiN no, that's not doable and it's a duplicate of https://github.com/seerge/g-helper/issues/909 sorry

**Closed by seerge** 2023-09-01 06:55 UTC
Labels: question
