### ISSUE TITLE
Custom Fan Profiles Not Working Correctly

### ISSUE THREAD

**Issue by XyKER1** [seerge/g-helper#683] opened 2023-06-26 18:00 UTC
**Describe the bug**
Exactly what the title says.  In my case, I created a fan profile to be able to run the laptop without the fans on until the CPU temp hits 65 C so I can watch videos without any background noise.  I have the manual mode enabled in config.json and both custom fan curve and custom power limits are checked.  However, the fans turn on at 57 C, which I believe is the same as either the Balanced or Silent profile.  I'd also like to add that Armoury Crate allowed the fans to stay off until 70 C, while your fan curve editor won't let me go above 65 C without turning the fans on.

**Clear scenario to Reproduce**
1. Create a custom fan curve
2. Set it to 0% fan speed until 65 C
3. Do something that causes the CPU to heat up (like watching YouTube videos)

**Expected behavior**
The fans should not turn on until 65 C like the fan curve shows, but they are turning on at 57 C.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11872250/log.txt)

**Screenshots or screencasts**
![fan curve](https://github.com/seerge/g-helper/assets/135291286/5e174e19-861b-4d18-858a-ba7597a405ae)
![throttlestop](https://github.com/seerge/g-helper/assets/135291286/f446ee9d-467a-43d0-bd6e-861ef26fb3af)
Notice that Throttlestop shows the max temperature reached was 61 C, so the fans never should've turned on.

**Desktop (please complete the following information):**
Windows 11, FX507ZM

**Asus software**
No ASUS services running, I think MyASUS was reinstalled through Microsoft Store at some point but I haven't opened it.

**Comment by seerge** [comment] 2023-06-26 19:13
@XyKER1 hello, from log i see that fan profile is accepted 
``` 
6/26/2023 1:05:57 PM: Manual Mode = 4 : OK
6/26/2023 1:05:57 PM: FanCPU = 26-41-46-47-4D-4F-51-62-00-00-0B-16-1D-2F-34-45 : OK
6/26/2023 1:05:57 PM: FanGPU = 14-3A-3D-40-48-4D-51-62-00-00-16-1D-26-2D-34-4A : OK
```
The rest is up to your BIOS and how to interpret it :) app doesn't control your fans.

Do exactly same fan profile work if you set it in Armoury Crate?

**Comment by XyKER1** [comment] 2023-06-27 00:02
I made the exact same profile in Armoury Crate, and it works correctly, so this seems to be an issue with G-Helper.  Maybe one of the ASUS services you have stopped (that Armoury Crate restarted when installing) allows this?  I can record a video of both with the fan speeds and temps if you want me to.  Also, Throttlestop shows the same or very similar temperatures to AC and G-Helper, so I think they use the same sensors.

**Comment by norwayman22** [comment] 2023-06-27 07:36
I'm experiencing something similar. My custom fan profiles on my 3080 XG Mobile and my CPU don't match with what's reported. 
In the picture, you can see there is a point in my CPU fan profile that's mapped to 77C and 4600RPM, while CPU temp is reported at 67C and the fan is running at 5300RPM.
![image](https://github.com/seerge/g-helper/assets/79989412/6080d4d3-4fe6-4ff9-8bdd-191cb7765b6c)

**Comment by seerge** [comment] 2023-06-27 08:04
@XyKER1 the only thing i can assume, is that it's due to the special fix for power limits I was setting for your specific models according to https://github.com/seerge/g-helper/issues/405 (by request from @Xaymar) .  

Can you try this build W/O a "fix" and see if it makes a difference ? and also if power limits still work ?

[GHelper.zip](https://github.com/seerge/g-helper/files/11879299/GHelper.zip)

**Comment by seerge** [comment] 2023-06-27 08:07
@norwayman22 I don't think that your case is related. Fan curve is not set in stone for the bios, it's free to interpret it as it wants, with delays, shifts from desired fan RPM %, etc :) 

Also keep in mind that Y-axis showing RPM in fan curves is something that I manually did to just illustrate approximate fan speeds, they may vary from model to model (even more in AC it shows only % there, and it's a wrong % ... as 1% immediately means 1800RPM for asus)

**Comment by seerge** [comment] 2023-06-28 21:54
@XyKER1 did you had a chance to check a build ?

**Comment by XyKER1** [comment] 2023-06-29 00:41
I currently don't have my laptop (vacation) but I should be able to test it on Saturday at the latest.

**Comment by envyska** [comment] 2023-06-29 05:29
Oh we have same issue :(. Fans started to ignore my custom settings after updating .91.

fixed fanrate some temp then never move till uncheck custom  fan curve option.

I tried to use older version. .87 was ok but update alerts(which i cant turn off) bothered me a lot so i ve almost forced to use .91 rn.

![fan](https://github.com/seerge/g-helper/assets/136965993/5e1616ea-301a-420d-875c-2f9103e8fcfa)
![f1](https://github.com/seerge/g-helper/assets/136965993/02690fc5-d6c8-42cc-8131-3e543fe04e7f)
![f2](https://github.com/seerge/g-helper/assets/136965993/22037f2d-79e9-4336-bb95-8c660923ed45)

**Comment by seerge** [comment] 2023-06-29 09:01
@envyska hi, but looking at your screenshots it seem to be ok? :) And please don't expect it to follow curve super precisely (in AC that curve shows only % not RPM even ...)

**Comment by envyska** [comment] 2023-06-29 09:41
if i move fan curve, it always fixed on 70~72 Celcius fanrate.  no matter what temp or shape the curve has

![ff1](https://github.com/seerge/g-helper/assets/136965993/031d3dd6-01c9-4cd7-91a0-bb7787859d89)
![ff2](https://github.com/seerge/g-helper/assets/136965993/f0a8af85-d8d3-4441-aadd-c1bf763a397b)

look at this. fixed or moves opposite way :(

**Comment by seerge** [comment] 2023-06-29 09:45
@envyska if you would  set fan curve to 100% all the time, or to OFF - would it follow?

**Comment by envyska** [comment] 2023-06-29 09:50
seems not. :P 
![ff3](https://github.com/seerge/g-helper/assets/136965993/59680c54-ca3f-4d41-b7cb-6dd2734bae3d)
![ff4](https://github.com/seerge/g-helper/assets/136965993/70274767-cb1d-470d-a68e-e6f24ae2f215)

I cant set off over 65. and following same rpm of  that temp KEK

**Comment by seerge** [comment] 2023-06-29 09:54
@envyska well, it's clearly lower RPM than before, so i think it follows something. I assume if you would set to 100% it would ramp up.

On this stage I can refer you to this FAQ question https://github.com/seerge/g-helper#how-does-g-helper-control-my-fan-speeds

App doesn't control your fans, it can only set a fan curve, the rest is up to bios :) There is literally nothing i can do for you. If you want you can try to set same curves in AC and see how do they work there.

**Comment by Xaymar** [comment] 2023-06-29 22:06
> @seerge: by request from @Xaymar

I apologize if I messed anything up, I only have this ASUS device for testing. It was working on my device - and still does. As for the fan curve on the device, I actually do see similar results since the last few Armoury Crate (Driver) updates:

- The GPU fan always shows 0%, and doesn't spin anymore.
- Fan curves no longer work if the curve is not like [this](https://share.xaymar.com/view/5fc22a48-0eba-4f40-9ae0-7f46349621d5). It is not possible to make S-shaped curves anymore.
- When more than two points are set at 100%, the entire curve is either treated as 100% or 0%. 
- Some curves are offset by as much as 30°C, so the value set at 50°C is applied at 70°C.

Doubt any of these are caused by G-Helper, and are just ASUS messing things up. Wouldn't be the first time...

**Comment by seerge** [comment] 2023-06-29 22:09
@Xaymar in a build that I linked here (above) I have actually removed "manual" (added in #405 for you), so it's back to silent / balanced / turbo. You can try it (or just download 0.92). But if even if then your fans don't behave I'm out of ideas :)

**Comment by Xaymar** [comment] 2023-06-29 23:21
> You can try it (or just download 0.92). But if even if then your fans don't behave I'm out of ideas :)

Results:

- Needed to update BIOS with a BIOS that isn't even available on ASUS site - MyASUS had it, and it "fixed" the GPU Fan.
- If "Apply Custom Fan Curve", the GPU Fan is no longer working. Still, at least better than before where it wasn't working no matter what.
- CPU Fan Curve still needs to be this half-C shape to work. Not that it matters since turning on Custom Fan Curves turns off the GPU Fan.

I guess I'll be mixing ASUS Armoury Crate and G-Helper, if any of this even works. Doesn't seem like ASUS is done messing with things for a while.

**Comment by seerge** [comment] 2023-06-30 09:18
@Xaymar well, given amount of your problems - indeed try to set exact same fan settings in AC :) as if it's same there, it's probably something with device itself.

**Comment by XyKER1** [comment] 2023-07-01 22:54
I tried your build and the same thing is still happening.  My only guess is that maybe it has something to do with the fan speeds also displaying incorrectly (maybe each model has a different offset or something).  I guess I can just use AC to set a fan curve profile for silent when I want it and then use G-Helper for everything else.

**Comment by seerge** [comment] 2023-07-01 23:00
@XyKER1 fans speeds you can compare by checking what g-helper and ac show (should be close). 

Just to make a check, can you make screenshots of a CUSTOM fan curve that you set in AC (i assume you use manual mode) and in G-Helper ?

Also please keep in mind that in general in AC Manual mode is Turbo with customisations. So for the clean test you should also "customize" turbo mode in g-helper :))

**Comment by seerge** [comment] 2023-07-02 14:54
@XyKER1 PS: Something that came to my mind: from previous request about PPTs, I think you have added ``manual : 1,`` to your config.json - please remove it :) (as it will still force a "manual" mode, which by my assumption could be affecting your system follows or doesn't follow custom fan curves)

**Comment by XyKER1** [comment] 2023-07-02 21:08
Nevermind, I was confused, and G-Helper is reporting the correct fan speeds.  I created a new profile from the Turbo mode and the fans still turn on at 59 C instead of 65 C.  Meanwhile the Armoury Crate profile works correctly.  Removing manual mode from the config file didn't make a difference.  Here are the images of the fan profiles (yes, the G-Helper image here was created from turbo mode):
![armoury crate silent fan profile](https://github.com/seerge/g-helper/assets/135291286/57ed0adc-e140-4ecf-afbe-d262f05895fd)
![g helper silent fan profile](https://github.com/seerge/g-helper/assets/135291286/2856f054-7702-443d-b1ca-29cc2b3dab68)

It would also be nice if you could let me set the max temp up to 69 C before fans turn on like Armoury Crate does.
Just an FYI, I will be on vacation for the next two weeks and so I won't be able to do any testing.

**Comment by seerge** [comment] 2023-07-02 22:14
@XyKER1 hello, fan curves in AC and G-helper look absolutely different :) And it possible that in some models, first dots / their number are important :) 

Try to set **exact same curve** (or as close as possible) in the app as you use in AC

Or for simplicity you can just replace your current fan curve in ``config.json`` with this lines (just carefuly replace _3 with correct profile ID that you have for "YouTube Silent"

```
  "fan_profile_cpu_3": "28-32-3B-45-48-4F-5A-64-00-00-00-00-22-28-28-28",
  "fan_profile_gpu_3": "28-32-3B-45-49-50-59-64-00-00-00-00-22-27-27-27",
```

**Comment by XyKER1** [comment] 2023-07-03 02:12
Alright, I will test that in two weeks when I get back.  If you want to set this to closed for now, that's up to you.

**Comment by seerge** [comment] 2023-07-03 07:46
Ok, I'm closing it for now, feel free to re-open when you will have a chance to test same fan curve on both apps :)

**Closed by seerge** 2023-07-03 07:46 UTC
Labels: not reproducible
