### ISSUE TITLE
FN-lock on doesn't work properly

### ISSUE THREAD

**Issue by hsrizvi** [seerge/g-helper#1508] opened 2023-10-23 01:53 UTC
**Describe the bug**
When turned on, FN-lock is on but holding FN and pressing a function key to use that function (F1, F2, etc) doesn't work. Just causes the media controls again.

**Clear scenario to Reproduce**
1. Enable FN-lock
2. Press any function key to test FN-lock is enabled
3. Hold FN key and press the previously pressed FN key to activate the normal function (not the asus specific function)
4. Key acts as if FN key was never held down 

**Expected behavior**
With FN-lock on, Pressing F1 without holding FN key should mute. With FN-lock off, pressing F without holding FN key should do normal F1 function (not mute).

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``

[log.txt](https://github.com/seerge/g-helper/files/13065385/log.txt)

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model Asus Zephyrus G16 GU603VV-G16.I74060

**Asus software**
- MyASUS installed, not running
- Asus Hotplug Controller
- Asus Monitor Controller

**Additional context**

**Comment by seerge** [comment] 2023-10-23 08:39
@hsrizvi this is a duplicate of https://github.com/seerge/g-helper/issues/509 (and couple of other issues)

It's not doable, as whole fn-lock is software emulation

**Closed by seerge** 2023-10-23 08:39 UTC
