### ISSUE TITLE
Replace ASUS optimization for hotkeys

### ISSUE THREAD

**Issue by lucidnx** [seerge/g-helper#397] opened 2023-05-16 22:05 UTC
**Is your feature request related to a problem? Please describe.**
It's not actually problem with G-Helper, but I am having issues with laptop going to sleep/hibernation state when It's closed in vertical stand and playing games/heavy usage. Reason according to event viewer is ASUS Optimization service and somebody mentioned on reddit that ASUS is doing this to prevent overheating. That's weird because it's even cooler than normally (up to 80 celsius in vertical stand, 96 celsius open in air, there's definitely some throttling but usable a lot)

**Describe the solution you'd like**
Please implement hotkeys for all functions with OSD if it's possible so we will be able to completely disable all asus services.

**Describe alternatives you've considered**
Disabling service while it's on external monitor/dock closed, but that's not perfect and introduce another bugs

**Additional context**
thread on reddit with same issue:
https://www.reddit.com/r/ZephyrusG14/comments/p98gmq/computer_is_forced_to_sleephibernate_when_gaming/

**Comment by seerge** [comment] 2023-05-16 22:18
@lucidnx current problem that the way to get events from pressed hotkeys (via WMI) that asus optimization service has to be running ... :|

**Comment by lucidnx** [comment] 2023-05-16 22:34
hmm I am not sure how it is working but in past, I helped dev of HWInfo to get some low level data from GA402RK to implement fan speed reading for CPU and GPU, maybe if I ask, he will help us with that...

**Comment by seerge** [comment] 2023-05-16 22:36
@lucidnx for fan reading you don't need asus optimization :) i also read them directly via acpi (same as most of other things), but events are a bit different thing atm :)

**Comment by lucidnx** [comment] 2023-05-17 00:24
sure, but he may know something... :) maybe it's worth a try.

**Comment by seerge** [comment] 2023-05-17 12:56
@lucidnx sure. I have spent a lot of time today trying to catch ACPI events (for keypresses / etc) directly without WMI
https://github.com/seerge/g-helper/commit/7117b58746c868911b1174247138500d2dd5d55c#diff-cf80c6167d5b46bbc633700339db07861c16aa21dd78b0b1c207b6d1e8fd9db7

But event that thing still works only when Asus Optimization is running. I guess it does something under the hood that is needed for events to work.

**Comment by lucidnx** [comment] 2023-05-18 19:02
well, he have a lot other work to do, so not going to help in this case.. Maybe somebody else can help..

**Comment by lucidnx** [comment] 2023-05-18 19:04
> @lucidnx for fan reading you don't need asus optimization :) i also read them directly via acpi (same as most of other things), but events are a bit different thing atm :)

I don't need fan readings (this is done outside of optimization service in hwinfo, not related to this) but I need hotkeys as lid close, Fn+Fx keys and other stuff if it's doing anything else.

**Comment by seerge** [comment] 2023-05-20 18:57
@lucidnx no one was offering you "fan readings", you have mentioned them by yourself :)

I have managed to get reading from hotkeys via USB protocol from keyboard.

You can try this build that supports all main hotkeys + even shows some basic OSD for them. App processes hotkeys only if on start it sees that Asus Optimization Service is not running (it checks for process name), otherwise - it will behave in an "old" way

[GHelper.zip](https://github.com/seerge/g-helper/files/11523017/GHelper.zip)

**Comment by lucidnx** [comment] 2023-05-20 19:45
It seems to be mis-understanding. That's great, I will try it :)

**Comment by seerge** [comment] 2023-05-20 21:11
@lucidnx a bit updated version with better OSD icons is live as https://github.com/seerge/g-helper/releases/tag/v0.65

**Comment by AudreyAP** [comment] 2023-05-21 00:21
This is really amazing. It seems that no Asus services are required anymore?

I have one request though - is it possible to use windows OSD when possible? Right now it seems that display brightness is being controlled by your custom OSD instead of by the integrated brightness OSD - volume uses the integrated one, which is great. 

Thank you so much for all of your work on this. I'm blown away by how much better g-helper works than armory crate did.

**Comment by seerge** [comment] 2023-05-21 08:26
@AudreyAP correct, it can work without asus services.

I can't trigger window's OSD. You see windows osd for volume because app doesn't handle those keys and windows intercepts them. For the rest - app does what it can :)

**Comment by lucidnx** [comment] 2023-05-21 13:26
I am trying it right now, seems to be working except backlight controls after resuming from hibernation (at least that's what I am seeing now). Backlight is on 1/3 and does not respond. Restarting GHelper won't help. Also blocking touchpad is not working right now.

It will show OSD, button press is registered in logs:
21. 5. 2023 15:18:06: Key:197
21. 5. 2023 15:18:07: USB-KB 0x19B6:5D-BA-C5-C4-00
21. 5. 2023 15:18:07: Key:197
21. 5. 2023 15:18:07: USB-KB 0x19B6:5D-BA-C5-C4-00
21. 5. 2023 15:18:07: Key:197
21. 5. 2023 15:18:07: USB-KB 0x19B6:5D-BA-C5-C4-00
21. 5. 2023 15:18:07: Key:197
21. 5. 2023 15:18:07: USB-KB 0x19B6:5D-BA-C5-C4-00
21. 5. 2023 15:18:07: Key:197
21. 5. 2023 15:18:07: USB-KB 0x19B6:5D-BA-C5-C4-00
21. 5. 2023 15:19:37: Key:196
21. 5. 2023 15:19:37: USB-KB 0x19B6:5D-BA-C5-C4-01
21. 5. 2023 15:19:37: Key:196
21. 5. 2023 15:19:37: USB-KB 0x19B6:5D-BA-C5-C4-02

**Comment by lucidnx** [comment] 2023-05-21 13:26
It seems that backlight timeout is not applied this way right now?

**Comment by seerge** [comment] 2023-05-21 14:03
@lucidnx i can't reproduce neither hibernate issue, nor touchpad. It works for me :|

**Comment by lucidnx** [comment] 2023-05-21 14:25
Maybe try to set backlight timeout, there's chance it started after setting value there.

**Comment by seerge** [comment] 2023-05-21 14:26
@lucidnx backlight timeout setting won't do anything w/o optimization service. That setting in the app will only change registry entry :) it doesn't do anything on hardware level

**Comment by seerge** [comment] 2023-05-21 15:21
@lucidnx probably something has hanged keyboard. My assumption would be multiple apps / services trying to communicate with it at the same moment, but I couldn't recreate something like that even by forsing optimization service / g-helper at the same time :)

**Comment by lucidnx** [comment] 2023-05-21 15:26
but it's weird that it started working when i started asus optimization service and stopped it.

**Comment by seerge** [comment] 2023-05-21 16:07
@lucidnx it could be that optimization service has some (unknown) keyboard init procedure, that resets it.

**Comment by seerge** [comment] 2023-05-21 17:12
@lucidnx I have figured out what could be a reason. If Asus service is not running, on COLD start (i.e. when you completely turn Off computer and start it again) keyboard backlight won't work at all. It has to be initialized. That also explains your hibernate issue (as it's also power off)

I have added initialization in this build - and it should be ok now

[GHelper.zip](https://github.com/seerge/g-helper/files/11525108/GHelper.zip)

**Comment by AudreyAP** [comment] 2023-05-21 17:51
@seerge 

> I can't trigger window's OSD. 

Damn! Is that due to lack of documentation on how to interface with it, or is it by design in windows? Would be really nice to be able to click and drag the slider as you are able to in the volume OSD. 

Even if not possible... still better than running asus' stuff lol!

**Comment by seerge** [comment] 2023-05-21 22:34
All changes are live as part of v0.66. Closing as completed

**Closed by seerge** 2023-05-21 22:34 UTC
Labels: enhancement
