### ISSUE TITLE
Power and Temperature limits not working properly

### ISSUE THREAD

**Issue by SodaSyrup** [seerge/g-helper#2823] opened 2024-07-10 02:49 UTC
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Im trying out different "Power Profiles" and i set one up with very extreme limits, now when i make a new profile with more power to it, the stricter limits are still applied. 

### How to reproduce the bug?

1. Create Profile "Extra Silent"
2. Set Platform Limit 18w and CPU 10w and Temp Limit 75c
3. Run Cinebench and see in HWInfo it looks fine
4. Create new Profile "Testing"
5. Set Platform Limit 80w and CPU 10w and Temp Limit default
6. Run Cinebench and see that power package still is limited like before and temperature too

I made sure to triple check if i clicked on apply and all that, at first the fan curve didnt want to work but that one did after a while.

### Logs

[log.txt](https://github.com/user-attachments/files/16154500/log.txt)

### Device and Model

ROG Zephyrus G14 GA402RJ

### Armoury Crate

Uninstalled

### Asus Services

none

### Version

0.178.0

### OS

Windows 10 22H2

**Comment by seerge** [comment] 2024-07-10 06:36
@SodaSyrup hello, every time you set a new mode - all your limits are being reset by BIOS (this is how your device works)
I checked the log and it happens all the time.

What exactly are you measuring in HWinfo ? Can you post screenshots?

**Comment by SodaSyrup** [comment] 2024-07-10 14:53
I started spamming the mode button towards the end mostly because i was just confused and was stalling time lol.
Here is the screenshot:
![image](https://github.com/seerge/g-helper/assets/130868903/df75d1b1-c7f4-4535-a11e-1f2e27b245a9)


when i first set the temp limit to 75c, the numbers turned red in hwinfo when coming close to 75 and the power wattage never went above 28w, switching to another custom mode it was the same, even tho it shouldnt.

**Comment by SodaSyrup** [comment] 2024-07-10 14:57
a restart fixed this tho, and i didnt try hard, but i couldnt reproduce it yet.

**Comment by seerge** [comment] 2024-07-10 14:59
@SodaSyrup 

CPU PPT (or CPU package power) will show currently used power, not the limit.

I also see that since you are "modifying" ``Silent`` mode, corresponding Windows ``Power mode`` (under `Fans + Power`) is set to `Best battery efficiency`. That by itself also restricts how windows can utilize CPU.  So highly likely it won't go to 50W.

Try to change ``Power mode`` to `Balanced` or `Best performance` or use `Balanced`\`Turbo` mode at as base for more powerful profile.

**Comment by SodaSyrup** [comment] 2024-07-10 15:10
i know the cpu ppt does show the currently used power, but before experimenting with extra silent it went to 50-70w when running cinebench on stock balanced mode. once i made a new custom profile (extra silent) it never went above 30w, even when i made another custom mode that didnt have the same power limits. a pc restart fixed the issue and i wasnt able to reproduce it yet, and if i cant anymore thats also totally fine, just thought if its a bug that pesists that i should report it, ill do some more testing and come back here if something like this happens again

**Comment by seerge** [comment] 2024-07-10 15:29
@SodaSyrup i just did some benchmark / hwinfo run

And `Silent` profile by itself also sets lower Temp limit (i think around 85C) , while in `Turbo` default is 96C .
Both this values are just hardcoded in BIOS.

**Comment by seerge** [comment] 2024-07-11 07:34
Ok, since it's not happening again - I'm closing this as resolved (also due to the way modes work on firmware level and cause i can't reproduce it)

If you will have some clear scenario to trigger something like that, feel free to post.

Thanks

**Closed by seerge** 2024-07-11 07:34 UTC
Labels: question
