### ISSUE TITLE
"Laptop Screen: 144Hz" even when screen off

### ISSUE THREAD

**Issue by LoreAPC** [seerge/g-helper#847] opened 2023-07-22 09:10 UTC
**Describe the bug**
I mostly use the notebook connected to an external monitor. Some versions ago the Hz indicator in the main window would detect that the internal screen was off and return "screen off" or something similar.
Now (ver 0.98.0.0) it says 60hz or 144hz+od regardless of the internal monitor being on or off.
The change between 60hz and 144+od is reactive to the laptop being plugged/unplugged.

I just noticed that also the external monitor switches from 60/144hz while plugging/unplugging. Did it always do that?

**Expected behavior**
Line in main window should read like "Laptop Screen: off" like it did some versions ago.

Win 10 with no Armoury Crate.

Thank you very much

[log.txt](https://github.com/seerge/g-helper/files/12136058/log.txt)

![Immagine 2023-07-22 110704](https://github.com/seerge/g-helper/assets/128968377/8caaf5ff-97ca-4d09-b807-c27cdee9babb)

**Comment by seerge** [comment] 2023-07-22 09:34
@LoreAPC hello, this is something i have fixed in 0.99/0.100 :) just update an app

And a duplicate of https://github.com/seerge/g-helper/issues/825 :)

**Closed by seerge** 2023-07-22 09:34 UTC
