### ISSUE TITLE
Disable FN Lock on External Keyboard

### ISSUE THREAD

**Issue by lgarlati** [seerge/g-helper#3241] opened 2024-10-09 14:57 UTC
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

When using an external keyboard, the function keys remain mapped to the built-in keyboard's functions. IE, pressing F11 for full screen on my wireless keyboard puts the computer to sleep. Further, because external keyboards tend to not have a Fn key, it's quite annoying to open ghelper and toggle Fn lock via mouse. 

### Describe the solution you'd like

If input is from an external keyboard, or an external keyboard is connected, disable Fn lock. 

### Describe alternatives you've considered

A shortcut that doesn't require the Fn key to toggle Fn lock.

### Device and Model

Asus Zephyrus G16 GU605MZ

**Comment by seerge** [comment] 2024-10-09 15:24
@lgarlati  hello, this is a duplicate of https://github.com/seerge/g-helper/issues/918 (and couple of other issues).

I was answering this already and it's not possible. Sorry

Thanks

**Closed** 2024-10-09 15:24 UTC
