### ISSUE TITLE
XG Mobile Fan

### ISSUE THREAD

**Issue by privacyonly** [seerge/g-helper#301] opened 2023-04-29 11:06 UTC
**Is your feature request related to a problem? Please describe.**
I only saw 2 fan cpu and gpu for my flow z13, can we have XG mobile fan?

**Describe the solution you'd like**
gpu temperature and fan display for XG mobile.

**Describe alternatives you've considered**

**Additional context**

**Comment by seerge** [comment] 2023-04-30 11:46
I don't own neither Z/X series laptop nor XG Mobile so can't test / discover how fan is controlled there, if you do know - i can add it of course :)

**Comment by KamistixX** [comment] 2023-05-03 04:43
That would be really great.

Get this man an XGM!

**Comment by privacyonly** [comment] 2023-05-05 13:28
I also found able to control the XG mobile fan but did not display the current fan speed.
https://github.com/JamesCJ60/Armoury-Control/commits/master

**Comment by Samer1FL** [comment] 2023-05-16 15:59
Can you refer back to Armory Control? 
He referred back to your project too :)

also can you advise the Bios settings 

https://github.com/JamesCJ60/Armoury-Control#readme

**Comment by seerge** [comment] 2023-05-19 17:16
@privacyonly @KamistixX @Samer1FL 
You can check this build , it should allow setting XG Mobile fan curve if it's connected. 

Keep in mind : default fan curve that you see for XGM is not a read one (i'm not aware if it's even possible to read it), it's just a template

[GHelper.zip](https://github.com/seerge/g-helper/files/11519046/GHelper.zip)

**Comment by Samer1FL** [comment] 2023-05-20 17:19
It didn’t adjust anything for me, sometimes when i adjust the CPU fan boost while I’m plugging XGM it also doesn’t adjust anything, i have to restart or reconnect the XGM.

**Comment by seerge** [comment] 2023-05-20 17:29
@Samer1FL how do you check if fan curve is adjusted or not? What is "cpu fan boost" ?

And in general, it would be good if you would attach an app log from %appdata%/ghelper here, cause I have lost my telepathic skills :)

**Comment by Samer1FL** [comment] 2023-05-20 18:18
> 

I set the fan on max but nothing change you literally can hear the XGM fan noise 2 block away LOL, what i meant by CPU fan boost is the CPU Boost option, i dunno why i wrote fan. I will share you the Logs ASAP, is just i feel like adjustments are made after rebooting or reconnecting XGM. I dunno if that is because AtlasOS somehow or Bloat and Debloate files are shouldn’t work for XGM

**Comment by seerge** [comment] 2023-05-20 18:51
@Samer1FL it sends fan curve to XGM, when you adjust in editor / or click apply. XGM has to be connected ofc.

**Comment by moritzbeck01** [comment] 2023-05-20 20:42
Seems to work for me!

**Comment by moritzbeck01** [comment] 2023-05-20 23:01
I spoke too soon: The selected fan curve doesn't actually get applied. I chose a too generic one to test.

**Comment by privacyonly** [comment] 2023-05-21 09:56
I can confirm it doesn't work, like not being applied
[log.txt](https://github.com/seerge/g-helper/files/11524193/log.txt)

few bugs
![xg mobile fan](https://github.com/seerge/g-helper/assets/72265774/a7ea4aee-2e97-4735-ada5-7eb48753e762)
![xg mobile fan 2](https://github.com/seerge/g-helper/assets/72265774/9597a2a7-d146-472f-944f-765a3c0978fe)
xg mobile fan can goes up to 7780rpm(not confirmed)

**Comment by seerge** [comment] 2023-05-21 10:15
@privacyonly your log doesn't contain anything, you seem  to be trimming it for some reason.

Please check this build and post a full log. 

[GHelper.zip](https://github.com/seerge/g-helper/files/11524244/GHelper.zip)

**Comment by privacyonly** [comment] 2023-05-21 10:31
nope I just delete %appdata%/ghelper and start running new ghelper as to not pollute new log.
[log.txt](https://github.com/seerge/g-helper/files/11524259/log.txt)

**Comment by seerge** [comment] 2023-05-21 10:41
@privacyonly well, it clearly finds device and sends payload. 

Try this one then 
[GHelper.zip](https://github.com/seerge/g-helper/files/11524273/GHelper.zip)

**Comment by privacyonly** [comment] 2023-05-21 10:53
> @privacyonly well, it clearly finds device and sends payload.
> 
> Try this one then [GHelper.zip](https://github.com/seerge/g-helper/files/11524273/GHelper.zip)

this one is clearly changing the fan speed but... can you display the fan speed for XG Mobile?

**Comment by seerge** [comment] 2023-05-21 10:56
@privacyonly i don't know how to do that

**Comment by moritzbeck01** [comment] 2023-05-21 11:08
Since the fan speed is calculated in Armoury Crate, you would probably have to do something like this:
lower = point[temp-1]
upper = point[temp+1]
speed = ceil(lower.speed + ((temp - lower.temp) / (upper.temp - lower.temp)) * (upper.speed - lower.speed), 100)

**Comment by privacyonly** [comment] 2023-05-21 11:09
just an idea, find out the gpu temperature and display the speed based on fan curve?

**Comment by seerge** [comment] 2023-05-21 11:10
@moritzbeck01 what i meant, i'm not aware about how to read current fan speed from XG Mobile :)  But Does last build here work for you?

@privacyonly  Showing "incorrect" fan speed based on curve is a bad idea (keep in mind that 'default' curve is just a hardcoded template that i took from my G14 and not "actual" curve even).

**Comment by moritzbeck01** [comment] 2023-05-21 11:15
> @moritzbeck01 what i meant, i'm not aware about how to read current fan speed from XG Mobile :)

Yeah I don't think it's possible, that's what the formula does. It's basically what @privacyonly suggested in pseudo code.
I agree that it's not the best idea and doesn't work if no custom fan curve is set, but better than nothing imo.

**Comment by seerge** [comment] 2023-05-21 11:19
@moritzbeck01 it is possible to read (cause armoury does read it somehow :) I don't posess XG Mobile at all, so can't debug and discover that anyhow.

If someone knows correct "payload" to query & get temp readings - let me know :) May be via Nvidia API? Does HWInfo show temps / fan speeds there?

I won't be adding fake RPMs, as app also doesn't know XGM temp. Whole reason of that readings - is to be able to verify if curve is working or not :)

**Comment by privacyonly** [comment] 2023-05-21 11:25
> @moritzbeck01 what i meant, i'm not aware about how to read current fan speed from XG Mobile :) But Does last build here work for you?
> 
> @privacyonly Showing "incorrect" fan speed based on curve is a bad idea (keep in mind that 'default' curve is just a hardcoded template that i took from my G14 and not "actual" curve even).

Yes it works, ok.

> @moritzbeck01 it is possible to read (cause armoury does read it somehow :) I don't posess XG Mobile at all, so can't debug and discover that anyhow.
> 
> If someone knows correct "payload" to query & get temp readings - let me know :) May be via Nvidia API? Does HWInfo show temps / fan speeds there?
> 
> I won't be adding fake RPMs, as app also doesn't know XGM temp. Whole reason of that readings - is to be able to verify if curve is working or not :)

XGM Temp is showing at GPUZ, HWINFO, also I don't know how you do the CPU GPU FAN speed but... No the fan speed is not read by HWINFO.

**Comment by moritzbeck01** [comment] 2023-05-21 11:33
I'm pretty sure Armoury Crate also calculates the fan speed.

**Comment by seerge** [comment] 2023-05-21 11:46
@moritzbeck01 its possible to read fan speeds for all other fans, why would it calculate.

Does the last build in this thread work for you as well? If so i will push it into next release and consider fan thing completed :)

**Comment by privacyonly** [comment] 2023-05-21 11:55
is this for fan? https://github.com/KastB/asus_wmi

**Comment by moritzbeck01** [comment] 2023-05-21 11:57
The fan speed for the XG Mobile in Armoury Crate  seems to fluctuate a lot more than the others and doesn't represent the actual speed very well. It also isn't rounded to the next 100 RPM.

**Comment by seerge** [comment] 2023-05-21 17:21
@privacyonly 
> is this for fan? https://github.com/KastB/asus_wmi

It  contains standard fan endpoints, same as I use.

**Comment by seerge** [comment] 2023-05-21 17:22
Closing as completed, as fan contol seem to work now.

**Closed by seerge** 2023-05-21 17:22 UTC

**Comment by Wolper321** [comment] 2023-05-27 15:09
The latest version of G-helper 0.69 doesn't change LED status on my XG Mobile 6850M XT and doesn't change fan curve. But the version uploaded here works as intended

> @privacyonly well, it clearly finds device and sends payload.
> 
> Try this one then [GHelper.zip](https://github.com/seerge/g-helper/files/11524273/GHelper.zip)

The latest version of G-helper 0.69 doesn't change LED status on my XG Mobile 6850M XT and doesn't change fan curve. But the version uploaded here works as intended

**Comment by seerge** [comment] 2023-05-27 15:46
@Wolper321 but they are the same :) Can you you try again zip version and 0.69 and upload a log here?

**Comment by Wolper321** [comment] 2023-05-28 02:46
[log.txt](https://github.com/seerge/g-helper/files/11583536/log.txt)
I have tried 0.67, 0,69 and the released 0.66 and they all don't change the fan curve and LED for XG mobile. I came back to the one you posted here and... it's working again.

**Comment by Wolper321** [comment] 2023-05-28 02:49
Also on the other versions CPU curve are working fine. And if I switched to the 0.66 posted here it showed me XG Mobile was on default curve.

**Comment by seerge** [comment] 2023-05-28 08:50
@Wolper321 can you try this one ? 

[GHelper.zip](https://github.com/seerge/g-helper/files/11584107/GHelper.zip)

**Comment by Wolper321** [comment] 2023-05-28 12:10
> @Wolper321 can you try this one ?
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/11584107/GHelper.zip)
> 
> or just 0.70 https://github.com/seerge/g-helper/releases/tag/v0.70 (that has same changes) ?

This one works! Both LED and fan curves! Thx a lot

**Comment by seerge** [comment] 2023-05-28 12:10
@Wolper321 great :)

**Comment by seerge** [comment] 2023-05-28 12:12
@Wolper321 can you post a log here (from 0.70) ? i wanted to double check something ...

**Comment by Wolper321** [comment] 2023-05-28 12:16
[log.txt](https://github.com/seerge/g-helper/files/11584516/log.txt)
Sure thing!

**Comment by seerge** [comment] 2023-05-28 12:17
@Wolper321 ok, thanks. Can you check if this version still works ? (led / fans / etc)
[GHelper.zip](https://github.com/seerge/g-helper/files/11584526/GHelper.zip)

**Comment by Wolper321** [comment] 2023-05-28 12:25
> @Wolper321 ok, thanks. Can you check if this version still works ? (led / fans / etc) [GHelper.zip](https://github.com/seerge/g-helper/files/11584526/GHelper.zip)

This one also seems to be fine. Log just in case.
[log.txt](https://github.com/seerge/g-helper/files/11584539/log.txt)

**Comment by seerge** [comment] 2023-05-28 12:27
@Wolper321 good :) Just in a previous log I have noticed devices that were looking like XGM, and now I have narrowed them down to 1
