### ISSUE TITLE
Making the tray app auto close while clicking outside.

### ISSUE THREAD

**Issue by Vishvesh1542** [seerge/g-helper#2324] opened 2024-03-28 16:16 UTC
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

No it is not related to any problem. It is just a thing I thought would be basic instinct. So whenever you open a tray app, it usually (almost every time) does not have any (x) button and auto closes when you just click out of the app's space. I cant tell you how many times I have tried to do that with G-Helper but it just stays there and I need to close the button. Usually I just have to look at my settings or just change one setting. So closing the app everytime is annoying.

### Describe the solution you'd like

A solution would be to just make the app an actual system tray app which closes on clicking outside, or atleast make a full app along with a system tray app which quickly allows you to glance at some frequent settings for example. I do not know a lot about C# Programming but I am going to assume that the first option is going to be easier to implement. A toggle to switch between these would be nice as users who are already familiar with this behavior would not feel uncomfortable.

### Describe alternatives you've considered

The alternative is to just close the program every time I need to glance at some info.

I know this might be a silly request but maybe if you are free and took the time to implement it, I would be very happy

### Device and Model

Asus TUF F15

**Comment by seerge** [comment] 2024-03-28 17:20
@Vishvesh1542 hello, this is a duplicate of a similar question https://github.com/seerge/g-helper/issues/1802

There is no event as "click outside", but there is such as losing focus. But that also happens when you select other G-Helper's window (for example Fans+Power) . If i start handling all of that it would create lots of other unwanted side effects. 

You already have a right-click context menu that behaves exactly as you expect (it hides on click outside).

I would prefer when main window still behaves as a normal window.

So I don't plan to do it. Sorry and thanks.

**Closed** 2024-03-28 17:21 UTC
Labels: duplicate
