### ISSUE TITLE
Add separate power limits (PL1 & PL2 instad of PL1+PL2)

### ISSUE THREAD

**Issue by Delma-developer** [seerge/g-helper#1729] opened 2023-12-12 10:17 UTC
Hi!

I'd like to be able to set PL1 and PL2 separately, as in the Armory Crate app, instead of a single slider on my 13th gen H processor, since they took the much needed ability to undervolt away, and I need a way to control temps/battery usage.

I've read on a previous thread that the sliders have been combined for the sake of simplicity, but I think users knowledgeable enough to use G-Helper are also tech savvy enough to google what the various power levels are for, and less technical user will just leave it alone anyway.
This is a case where more is more in my book; I used G-Helper with my last two laptops, I'd love for it to be the only software that's needed for everything.

I could use ThrottleStop, but changing the profile twice when the problem is just UI on G-Helper feels kinda silly.
Also, can I also ask how PL1 and PL2 are calculated? What is the standard ratio between the two?

Thank you for this fantastic software

**Comment by seerge** [comment] 2023-12-12 10:29
@Delma-developer hello, it's not actually +, it's just same value for both limits (i.e. if you limit your power to 50W your CPU shouldn't use more than 50W)

What is the real practical scenario to set separate values ?

**Comment by Delma-developer** [comment] 2023-12-12 11:01
@seerge In my specific case, I have one very low power profile I use for university work.
The common power limit set at 10 watts works ok enough most of the times but for some bursty work like decompressing material or launching an application I'd like to be able to have a higher power limit (something like 20-35 I guess).

Kinda same situation for gaming: this thing runs very hot, I'd like to keep PL2 at 125 but move PL1 to something like 60-80

If I'm not mistaken, the PL2 tau is something like 28 seconds on this processor and surely some tinkering can be done to mitigate the lack of undervolting support and have it running cooler and for longer without compromising performance too much.

I know this can take some time to implement, but I've read people felt some benefit from this. I could check out if it makes a difference with ThrottleStop and get back to you with my own findings if you'd like

**Comment by ChromeModz** [comment] 2023-12-12 21:47
On my Strix Scar 17 2022 Laptop w/ a 12950HX CPU G-Helper displays max PL as 150w when in armory crate its 170w max for PL1 and 175w max for PL2

**Comment by seerge** [comment] 2023-12-12 22:52
@ChromeModz I can raise slider limit, but can your CPU actually reach 170W? it just sounds unrealistic :)

**Comment by seerge** [comment] 2023-12-13 16:17
@Delma-developer you can try this build

Also inviting @AudreyAP 

[GHelper.zip](https://github.com/seerge/g-helper/files/13663074/GHelper.zip)

**Comment by Delma-developer** [comment] 2023-12-13 16:49
> @Delma-developer you can try this build
> 
> Also inviting @AudreyAP
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/13663074/GHelper.zip)

Cheers, I will try it out during the weekend and get back to you!

**Comment by seerge** [comment] 2023-12-14 15:12
@Licht555 G-Helper is not  suppressing your CPU anyhow. There are 3 modes hardcoded in your BIOS (coming with own power limits) and app (same as AC) lets you switch between them

Unless you don't apply power limits manually, they have no effect on you

**Comment by Licht555** [comment] 2023-12-14 17:13
So GH refers to ready-made schematics stored in the device's BIOS, the same as AC? And what then initiates the BD PROCHOT command, which is passed in the BIOS like a sentence, because it cannot be revoked. 
BD PROCHOT limits the CPU a lot.

**Comment by seerge** [comment] 2023-12-14 17:27
@Licht555 not G-Helper for sure

**Comment by AudreyAP** [comment] 2023-12-14 18:44
@Licht555 that's all drivers and acpi/bios. Ghelper has absolutely nothing to do with any of this, and neither does AC.

**Comment by tdbe** [comment] 2023-12-15 21:24
> @Delma-developer you can try this build
> 
> Also inviting @AudreyAP
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/13663074/GHelper.zip)

I was searching for the same issue, found this, and it runs as intended. The annoying thing I'd like to learn more about: my laptop limits the upper wattage for PL1 at ~40% lower than PL2, regardless of what I give it in ghelper. Lower values work but there is an invisible asymmetric ceiling.

So in sustained full load, my laptop runs at 82 degrees celsius instead of going to 95 and boosting like PL2. 😑 I would beat the M3 Max in benchmarks if it wasn't for this 😅 Otherwise no complaints, I guess I got good cooling....

**Comment by seerge** [comment] 2023-12-15 21:57
@tdbe do you use Turbo mode as a base ? as it usually has highest "hidden" limits :)

Closing this as completed, as PL1/PL2 sliders are live in 0.138

**Closed by seerge** 2023-12-15 21:57 UTC
Labels: question

**Comment by tdbe** [comment] 2023-12-15 23:27
Nice 🙌. Yeah I do. And Best Performance, Aggressive. Pretty sure it's smth that ghelper or armoury crate can't solve. CPU's an intel 13th gen non-K part, nothing special in the bios, so prolly limited via bios and driver. Maybe a ThrottleStop wizard could find some loophole idk.

I have a good stand. If I put it flat on a table it def stabilizes at 90+ degrees instead of 82. I just never had a laptop that would not thermal throttle under all possible circumstances including the fridge lol
