### ISSUE TITLE
Incorrect offset limits on TUF Gaming F15

### ISSUE THREAD

**Issue by KitsunedFox** [seerge/g-helper#2104] opened 2024-02-22 17:17 UTC
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

On TUF Gaming F15 (FX507ZC4) (i7 12700H, RTX 3050), The maximum gpu clock offsets on both core and memory are much higher than the limits from Armoury Crate.

The maximum core clock offset should be 200mhz, and Memory clock offset 300Mhz. Any value above this causes stuttering and game crashes.

Also, the CPU power limits are incorrect.
On armoury crate, the maximum PL1 is 90W, and PL2 is 135W.

![Screenshot 2024-02-22 142332](https://github.com/seerge/g-helper/assets/103902727/971fa40b-23a3-4591-99cb-ab05974fca75)
![Screenshot 2024-02-22 142346](https://github.com/seerge/g-helper/assets/103902727/faa5084c-f3f2-4b50-ba05-a5bf600a9a4c)
![Screenshot 2024-02-20 220305](https://github.com/seerge/g-helper/assets/103902727/a346d59b-923f-47a0-a4fc-89effb6c9835)
![Screenshot 2024-02-20 220312](https://github.com/seerge/g-helper/assets/103902727/505c5c07-8658-499d-8fa8-e2bfcaa63840)

### How to reproduce the bug?

Check Fans + Power menu from G-Helper and try increasing the gpu clock offet and cpu power limits to any value above the ones from Armoury Crate

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14377191/log.txt)

### Device and Model

TUF Gaming F15 (FX507ZC4)

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.154.0

### OS

Windows 11 23H2 22631.3155

**Comment by seerge** [comment] 2024-02-22 17:26
@KitsunedFox hello, offset limits are universal :) as often you can set higher values if you want. Especially if you limit gpu clocks next to that.

As for power limits, there is usually a limit on bios level that will just ignore values higher than what is allowed by design, so if slider in AC can't go above 135w, probably your CPU won't go higher as well. But you can also set them within ranges you had I AC :)

Closing this, as there is nothing to fix here

**Closed by seerge** 2024-02-22 17:26 UTC

**Comment by KitsunedFox** [comment] 2024-02-22 17:31
not planned why?

**Comment by seerge** [comment] 2024-02-22 17:46
@KitsunedFox by the way, for the experiment.

Can you try to set power limits higher than 135w and tun cinebench23 + monitor actual power draw in HWInfo?

Cause for example on my G14 2022 formal limit for CPU is 80w, but you can set it a bit higher - up to 90w (with almost no real life improvements tho)

But after 90w it won't go any higher cause there is a hardcoded limit in bios for that.

**Comment by Kikimahe** [comment] 2024-02-22 18:50
Hi, 

>Can you try to set power limits higher than 135w and run cinebench23 + monitor actual power draw in HWInfo?

You right Seerge. The 12700h limit is a hardcoded in bios (PL1 90W / PL2 115W)
With cinebench + Hinfo, we can't go more than 115W... 117W when you're lucky. :)

**Comment by seerge** [comment] 2024-02-22 20:20
@Kikimahe yeah, so i guess AC shows those 135w just to make device looking more serious than it is or something like that ...

Honestly, based on my personal experience with 13900h - something like 100w is more than enough anyway
