### ISSUE TITLE
Type in text and display on animetrix

### ISSUE THREAD

**Issue by thduc87** [seerge/g-helper#1212] opened 2023-08-29 05:26 UTC
**Is your feature request related to a problem? Please describe.**
This is a suggestion to allow user to enter text and display the text on the animetrix panel

**Describe the solution you'd like**
Basically i'd imagine to have a text editor or a small input text panel so that user can enter any text/ character and display it on the animetrix panel accordingly

**Describe alternatives you've considered**

**Additional context**

**Comment by seerge** [comment] 2023-08-29 08:25
@thduc87 this is a duplicate of https://github.com/seerge/g-helper/issues/706

**Closed by seerge** 2023-08-29 08:25 UTC
