### ISSUE TITLE
Not detecting AniMe Matrix

### ISSUE THREAD

**Issue by Teskh** [seerge/g-helper#1066] opened 2023-08-12 20:52 UTC
My Zephyrus M16 (GU604VY) stopped recognizing that I have Anime Matrix. It worked right out of the box but after some driver updates it stopped working. The problem is that it is now on by default and I want to turn it off.
G-Helper seems to ask the system and, being told it doesn't have the feature, doesn't display controls for it. Is there any way to override this? 

<img width="328" alt="image" src="https://github.com/seerge/g-helper/assets/142120466/2e8f45b4-1ef6-4657-a3ed-90ddc7e371e1">

**Comment by IceStormNG** [comment] 2023-08-12 21:12
Can you check device manager whether there is a device with a warning symbol? Maybe there is a driver issue.
You can also a) post a log here so maybe it tells what went wrong and b) check USBTreeViewer whether you can find an ASUS ITE Device there (this is the AniMeMatrix).

<img width="338" alt="image" src="https://github.com/seerge/g-helper/assets/12786283/7e707f70-3d4c-4fc6-adbb-9c08c14f3f96">

**Comment by seerge** [comment] 2023-08-12 22:21
@Teskh as @IceStormNG said - check device manager for the anime matrix device.

As I remember from reddit, it was someone else also complaining about losing anime matrix everywhere. You can try to completely power off laptop and boot again or even do hardware reset https://github.com/seerge/g-helper#how-do-i-do-a-hardware-reset-on-a-laptop , mb it will resurrect it :)

**Comment by Teskh** [comment] 2023-08-12 23:26
> Can you check device manager whether there is a device with a warning symbol? Maybe there is a driver issue. You can also a) post a log here so maybe it tells what went wrong and b) check USBTreeViewer whether you can find an ASUS ITE Device there (this is the AniMeMatrix).
> 
> <img alt="image" width="338" src="https://user-images.githubusercontent.com/12786283/260260833-7e707f70-3d4c-4fc6-adbb-9c08c14f3f96.png">

Indeed there is a problem with the driver you mention:
<img width="658" alt="image" src="https://github.com/seerge/g-helper/assets/142120466/70652a1b-b055-484f-8d4f-f57493e37120">

Do you have any suggestions on how fix this?

**Comment by IceStormNG** [comment] 2023-08-13 07:44
@Teskh  You could go to device manager, and find the HID Device there (it should also have a yellow warning symbol), uninstall that, and let it scan for devices. If it goes right into error state again, uninstall all USB Hostcontroller and reboot. Keep in mind that uninstalling the host controller will render all USB devices unusable until the machine rebooted. So external mice will not work. After the reboot, windows will re-install the USB controller.
If this also doesn't work, there is likely a hardware/connection issue with the AniMeMatrix.

**Comment by Teskh** [comment] 2023-08-13 14:07
@IceStormNG tried removing as many USB drivers as it would let me, restarted & reinstalled, but to no avail. Also tried the long 'hardware reset' @seerge suggested.
Worst part is that it worked right out of the box (as in, the AniMe Matrix could be successfully customized from AC) and the lid displayed it properly.
Even now the AniMe Matrix is successfully displaying its default behavior  (ROG logo when on, goodbye on shut down etc), so the hardware seems fine other than not being recnognized.
Honestly I would be content with a way to force it off, since my main problem is that I find it too flashy for work related stuff. Can you think of any ways?
I tried doing a soft reset of the computer (keeping files and config) but that didn't work either. I'm not really looking forward to a complete factory reset.

Thanks for the help so far.

**Comment by IceStormNG** [comment] 2023-08-13 14:15
I mean: you could turn it off via hardware (that means, unplugging it). Though you might want to request warranty as it sounds like there is an issue with the USB Connection.

Just for reference. I have the same machine and already had to open it due to ASUS being ASUS (aka: incompetent).
The blue marker here is the Matrix connection

![image](https://github.com/seerge/g-helper/assets/12786283/d80d7876-2784-4da5-8244-98c7e631a241)

The green marked is the socket, the white plug is the cable of the matrix.
![IMG_1665](https://github.com/seerge/g-helper/assets/12786283/ad1b7594-ddf6-4fe4-9138-39e90523b23e)

I doubt that connection comes loose on its own as it was a pain to get it out.

Though if you do not want to send it in and just want to get rid of it altogether, you can unplug it (and tape the connector to the board with electrical tape so it doesn't move around).

I doubt a full reset is gonna fix this, as it does not use a special driver. What does the device manager say for this device? There should be one under either USB devices or HID Devices with an warning icon. If you open that, it should show a description and an error code to why the devices does not function.

**Comment by Teskh** [comment] 2023-08-13 14:26
I bought the device through Best Buy in Miami, FL and I'm located in Chile, South America. If sending it out wasn't risky enough as it is, it's just about impossible given the distance.

I was thinking (hoping?) for a software approach to turn it off. Some old reddit threads suggested changing the name of Lighting Services, but that didn't work for me. https://www.reddit.com/r/ZephyrusG14/comments/pfncix/how_to_turning_off_anime_matrix_permanently_it/

This is what my devices folder looks like:
<img width="719" alt="image" src="https://github.com/seerge/g-helper/assets/142120466/eda1b731-cb6e-45fe-b692-49697b26833c">
<img width="751" alt="image" src="https://github.com/seerge/g-helper/assets/142120466/17a71175-c294-443b-913e-1ea07a0cbaa6">

What type of issue did you have which required you to open it?

**Comment by IceStormNG** [comment] 2023-08-13 14:30
> What type of issue did you have which required you to open it?

The liquid metal, as always.


You can try to disable Windows fast boot and restart the machine. That sometimes causes this issue. 

Aside from that, such issues usually require unplugging and re-plugging the device which is a little tricky with the anime matrix.

**Comment by seerge** [comment] 2023-08-13 14:32
@Teskh did you try to unplug and power off completely ? (i have an assumption that in that case it would power off "matrix" device completely, mb that will reset it status), or even discharge laptop in that state ?

**Comment by Teskh** [comment] 2023-08-13 17:16
> You can try to disable Windows fast boot and restart the machine. That sometimes causes this issue.
Tried that.

Sadly didn't work either.

> Aside from that, such issues usually require unplugging and re-plugging the device which is a little tricky with the anime matrix.

Dreading that this may be the only way forward... Does error 43 hint at anything?

>@Teskh did you try to unplug and power off completely ?
I'm perhaps misunderstanding what powering it off completely means. I tried the 'hardware reset' suggested above (holding down the power button 30-40 sec). I haven't tried unplugging and discharging to full. Do you mean something else by powering it off completely?

**Comment by seerge** [comment] 2023-08-13 17:30
@Teskh by unplugging -  i mean literally keep it on battery and then turn off. In that state laptop for example would unpower USB ports (so you can't charge anything via them). 

So my assumption was that it will unpower anime matrix as well (as it technically also usb device, just internal).

**Comment by Teskh** [comment] 2023-08-13 19:14
> @Teskh by unplugging - i mean literally keep it on battery and then turn off. In that state laptop for example would unpower USB ports (so you can't charge anything via them).

I understand. It's a fair hypothesis, but it doesn't seem to work either I'm afraid.
I'm really hoping there's something other than having to physically unplug it...

**Comment by seerge** [comment] 2023-08-14 22:14
Did you had any luck resetting your matrix?

Anyway, since the problem is obviously not on the app side, besides wishing you best and trying to give random advices I can't help much.

I can either move this topic to discussions (in case you have found a solution) or just close it here probably :)

**Comment by seerge** [comment] 2023-08-15 21:53
Closing for now then

**Closed by seerge** 2023-08-15 21:53 UTC
Labels: question

**Comment by Teskh** [comment] 2023-08-16 18:21
> @Teskh Did you had any luck resetting your matrix?
> 
> Anyway, since the problem is obviously not on the app side, besides wishing you best and trying to give random advices I can't help much.
> 
> I can either move this topic to discussions (in case you have found a solution) or just close it here probably :)


Sorry hadn't checked. I didn't manage to reset it sadly, though I did try the suggestions.
On the app side: does G-Helper automatically check if the laptop has AniMe Matrix to see whether to display the commands?
If so: isn't there a way to force it to display the commands even if the laptop is saying that there is no AniMe Matrix display? I ask because the hardware works just fine (the lights work and it runs the default routine on waking up, sleep, shut down, etc) but it just seems like the software can't seem to realize that it's connected to it.

**Comment by seerge** [comment] 2023-08-16 18:32
@Teskh G-Helper automatically checks for Anime Matrix by checking if USB device with given ID is connected. Since device is not "connected" in your case (it shows error in device manager), there is no way to send any commands to it unfortunately, even to turn it off.
