### ISSUE TITLE
GA605 Undervolt

### ISSUE THREAD

**Issue by Adamusuta** [seerge/g-helper#3005] opened 2024-08-21 11:37 UTC
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The undervolt option for the GA605 is missing. Is the Ryzen AI not supported? What does "cpu_uv_2" do?

### How to reproduce the bug?

1. Go to Fans + Power
2. Click on Advanced tab

### Logs

[log.txt](https://github.com/user-attachments/files/16690907/log.txt)

### Device and Model

Asus Zephyrus G16 GA605WV

### Additional information.

Undervolting with UXTU works

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.184.0

### OS

Windows 11 24H2

**Comment by CodingGenius0001** [comment] 2024-08-21 14:47
Did you install the plugin?

For new users, this option shows. I didn't enable over and undervolting so it asks me to download the plugin

![image](https://github.com/user-attachments/assets/2cfe0880-2020-4042-bc0e-ceb94d187d4a)

**Comment by Adamusuta** [comment] 2024-08-22 03:58
Yes I have, it only shows the temperature limits

**Comment by seerge** [comment] 2024-08-22 09:51
@Adamusuta hello, can you try this build (and post a log from it after)?

[GHelper.zip](https://github.com/user-attachments/files/16708706/GHelper.zip)

**Comment by Adamusuta** [comment] 2024-08-24 11:20
Hi sorry for the late reply, was busy with work. Here you go!
[log.txt](https://github.com/user-attachments/files/16736360/log.txt)

**Comment by seerge** [comment] 2024-08-24 11:22
@Adamusuta so does it work for you, i.e. do you get better scores in cinebench23 or so ?

From the log it looks like it's accepted 
```
8/24/2024 7:18:38 PM: UV: -20 OK
```

Cpu temp limiter is not supported by this CPU btw (so if you want limit there, just limit power instead with same effect)
```
8/24/2024 7:18:38 PM: CPU Temp: 75 BAD
```

**Comment by Adamusuta** [comment] 2024-08-24 17:25
I don't have the time to test it right now, but thank you!

**Comment by seerge** [comment] 2024-08-24 18:12
@Adamusuta ok, no worries. Someone else has confirmed that it's working so I'm closing this as resolved. Feel free to post any updates tho

**Closed by seerge** 2024-08-24 18:12 UTC
Labels: question

**Comment by seerge** [comment] 2024-09-10 19:21
@FelixvdDonk someone else has mentioned to me that it was working on GA605. 

Try to run Cinebench23 or so without and with benchmarks (and same other settings, like power limits and obviously turned on boost) and compare scores. But don't expect miracles :) On mine G14 2022 i get something like 2% better score.

**Comment by FelixvdDonk** [comment] 2024-09-20 22:36
Thanks, want to confirm this is in fact working :). Effect unfortunately is extremely minimal on performance

**Comment by seerge** [comment] 2024-09-21 07:53
@FelixvdDonk glad to hear. Don't expect miracles here. 

On my G14 2022 (Ryzen 6900HS) i get like 1-2% performance boost at best :)
