### ISSUE TITLE
Some problems with screen readers

### ISSUE THREAD

**Issue by anmi2004** [seerge/g-helper#2035] opened 2024-02-06 12:05 UTC
Hello Dear Developer, I have some feature requests that still stem from the trouble I'm having with the screen reader.

There are some other toggle notifications when power is plugged in or unplugged or when the touchpad is switched on or off, could I be notified in some way of the mode switch that the program makes.
The methods I have in mind are utilizing ui automation notifications or toast notifications.

Another issue is that when I switch graphics card modes, if I click on the auto switch function for the 2nd time, the mode is changed directly to standard mode without any notification of this process. Can you find a way to remind me of this or provide a place to display the current mode like the mode switch above.

Another problem that is difficult to reproduce is that after you have opened a software window and closed it, after a while your screen reader focus automatically goes to the software, even if the software window has been closed. 

Can accessibility support be added to the Bios and software driver update functions. For example write the ability to go to download updates into the button properties.

**Comment by seerge** [comment] 2024-02-06 12:40
@anmi2004 hello,

For all the notifications you mention - it can be difficult to integrate them with a narrator. Cause what app does right now - it shows a "toast" windows in the center of the screen that often contains only icon (and sometimes text). This window doesn't receive focus from windows intentionally, so I can imagine narrator doesn't pick it up.

Do you know how to force narrator to read some text ?

**Comment by anmi2004** [comment] 2024-02-06 13:36
> @anmi2004 hello,
> 
> For all the notifications you mention - it can be difficult to integrate them with a narrator. Cause what app does right now - it shows a "toast" windows in the center of the screen that often contains only icon (and sometimes text). This window doesn't receive focus from windows intentionally, so I can imagine narrator doesn't pick it up.
> 
> Do you know how to force narrator to read some text ?

I'm asking the developers I know about this.

My second question about viewing the GPU is, is there any way to do it, like switching to quiet performance mode, that kind of notification?This only needs to be visible in the program.

**Comment by seerge** [comment] 2024-02-06 13:45
@anmi2004 i'm the developer. And what I try to explain here, that I'm not aware about easy way to force narrator to read notifications :)

As for GPU mode - I just checked, all buttons in GPU section can get focus, and narrator reads them. You don't need to click on Optimized mode each time you want to make it active, if it's already selected :)

**Comment by anmi2004** [comment] 2024-02-06 14:16
@seerge I mean on my side if I click auto switch twice in a row in GPU mode then it goes back to standard mode.

I checked the information, you can refer to the following link, because I am not the relevant developer, so there are some things I do not understand.

https://learn.microsoft.com/en-us/windows/win32/winauto/entry-uiauto-win32

**Comment by seerge** [comment] 2024-02-06 14:23
@anmi2004

When you click on Optimized second time - it would switch to current "real" mode, i.e. to Standard (or Eco if you have GPU disabled). This is actually by design.

You can try following build

I have added narrator support for "BIOS and Driver Updates" section, and also added a new "groupping" panel for GPU buttons, so narrator should read currently active mode when you switch to this section as well

[GHelper.zip](https://github.com/seerge/g-helper/files/14181509/GHelper.zip)

As for reading "notifications" about performance mode changes or touchpad, as I have mentioned there is no easy way to do that without setting windows focus on that notification. And I can't do that cause it will break usage for all other users :)

**Comment by anmi2004** [comment] 2024-02-06 14:28
> @anmi2004
> 
> When you click on Optimized second time - it would switch to current "real" mode, i.e. to Standard (or Eco if you have GPU disabled). This is actually by design.
> 
> You can try following build
> 
> I have added narrator support for "BIOS and Driver Updates" section, and also added a new "groupping" panel for GPU buttons, so narrator should read currently active mode when you switch to this section as well
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/14181509/GHelper.zip)
> 
> As for reading "notifications" about performance mode changes or touchpad, as I have mentioned there is no easy way to do that without setting windows focus on that notification. And I can't do that cause it will break usage for all other users :) 

Can you directly use the native notification method to directly pop up the notification of switching mode in the lower right corner? You can add a switch in the settings to decide whether to use this method, which is the simplest and most profitable way. Of course, it must be admitted that he is not elegant enough.

**Comment by cary-rowen** [comment] 2024-02-06 15:54
Hi @seerge,

To be honest, I haven't used this project yet, but I took a quick look and it is a .net project. In this case, implementing this request becomes extremely simple.

You can call UIA notification events:
https://learn.microsoft.com/zh-cn/dotnet/api/system.windows.forms.accessibleobject.raiseautomationnotification


This is a new feature added in .net4.8:
https://learn.microsoft.com/en-us/dotnet/framework/whats-new/whats-new-in-accessibility

Thank you for your support of accessibility.
Hope this will be useful


Best,
Cary

**Comment by seerge** [comment] 2024-02-06 17:21
@anmi2004 @cary-rowen ok, I have added a ``AccessibleObject.RaiseAutomationNotification`` call to all app's toast notifications. Main problem is they work only if G-Helper window has focus and (obviously) visible , otherwise it seem to be ignored.

You can try this build, that includes all previously mentioned updates and this notification

[GHelper.zip](https://github.com/seerge/g-helper/files/14184064/GHelper.zip)

**Comment by anmi2004** [comment] 2024-02-07 06:38
@seerge As you said. Notifications can only be read when the application is running in the foreground and the focus is in the application, otherwise they cannot be read.

However, the reading of the GPU mode is basically available, and the current state can be read when the packet is switched, which is the same as switching the performance mode.

One small feature that you would like to do if you have time is to let us also read the power consumption of the CPU and GPU and the fan speed and so on. The basic CPU temperature and fan speed can be read at the tray icon. Thank you very much.

**Comment by seerge** [comment] 2024-02-07 11:16
@anmi2004 

> One small feature that you would like to do if you have time is to let us also read the power consumption of the CPU and GPU and the fan speed and so on. The basic CPU temperature and fan speed can be read at the tray icon. Thank you very much.

App doesn't monitor power consumption, so can't report that. As for fan speeds and basic temperatures - I didn't really get you. How do you want to trigger that reading ? By setting focus on specific UI element or somehow else ?

**Comment by anmi2004** [comment] 2024-02-07 14:51
@seerge That's it. It works now. I can read the fan speed or something in the tray area.

**Comment by seerge** [comment] 2024-02-07 14:53
@anmi2004 ok, good to know :) currently app outputs temps / fans speeds and discharge ratio (when applicable) into system-tray tooltip text. I assume your narrator picks that up.

Then, it seems all main things are covered - i.e. Updates section / GPU mode section / and performance mode notifications when it was possible :) 

Closing as completed then

**Closed by seerge** 2024-02-07 14:53 UTC
Labels: question

**Comment by anmi2004** [comment] 2024-02-07 15:03
@seerge I would like to express my sincere thanks to you. Thank you very much indeed.Thank you for your patience and effort in developing these features.Every time I see your timely reply, I can feel the love and warmth in it. Thank you very much.
