### ISSUE TITLE
Fully updated, still shows Asus Control Interface is out of date (it isnt).

### ISSUE THREAD

**Issue by marcanthonynoz** [seerge/g-helper#2865] opened 2024-07-19 12:01 UTC
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

![gheper issue](https://github.com/user-attachments/assets/acfada7a-134c-4ca5-82a5-c5e365a91d33)

this has been updated 3 times yet it still says its due for an update :)

### How to reproduce the bug?

attempt to download new software 

install new software

restart

still says i require new software

### Logs

[log.txt](https://github.com/user-attachments/files/16311534/log.txt)

### Device and Model

Asus Zepheryus G16 2024 RTX 4090 model - GU605MY 

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.179.0

### OS

Windows 11 newest update

**Comment by seerge** [comment] 2024-07-19 12:03
@marcanthonynoz this is a duplicate of https://github.com/seerge/g-helper/issues/2848 please check that issue for an answer

**Closed by seerge** 2024-07-19 12:03 UTC
Labels: duplicate
