### ISSUE TITLE
FN key is always locked unless is pressed with Proart P16 (H7606)

### ISSUE THREAD

**Issue by Cudacke** [seerge/g-helper#3012] opened 2024-08-22 19:00 UTC
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

FN works fine with myAsus running.
However if myAsus is uninstalled or service is disabled.
FN key is act like is pressed.

### How to reproduce the bug?

uninstall myAsus restart computer.

### Logs

[log.txt](https://github.com/user-attachments/files/16716385/log.txt)

### Device and Model

Proart P16 (H7606)

### Armoury Crate

Uninstalled

### Asus Services

myAsus

### Version

0.184

### OS

Windows 11 24H2

**Comment by seerge** [comment] 2024-08-23 11:16
@Cudacke hello,

I think reason is that you had hardware FN-lock toggled before uninstalling :) and g-helper couldn't turn it off as it was not supported before.

I have recently discovered how that toggle works [in other issue ](https://github.com/seerge/g-helper/issues/2973)

So try this build and check if toggle works here (and post a log from it)
[GHelper.zip](https://github.com/user-attachments/files/16727858/GHelper.zip)

**Comment by Cudacke** [comment] 2024-08-23 17:14
[log.txt](https://github.com/user-attachments/files/16731783/log.txt)

Hi Seerge,

I tried the build.  the FN key and FN lock work exact opposite of what normally do.
If FN is locked the keys are F1-F12
If FN is unlocked the keys are function key.

I also found that in v0.184.0. If I only enabled the service "ASUS optimization" with myASUS unstalled.
FN key works fine.

**Comment by seerge** [comment] 2024-08-23 17:21
@Cudacke hello,

It's strange, cause 2 other people in other thread (including one with exactly same device) reported it's working fine.

In your log i see that you start app with FN-Lock enabled.
``
2024/8/23 上午 10:03:24: FnLock = 1 : OK
2024/8/23 上午 10:03:24: USB FnLock 19B6|63: 5A-D0-4E-01
```
Just to clarify  when FN-lock is enabled - pressing `F1` will mute, and pressing `FN+F1` will do F1. And this is intended behavior. When FN-lock is enabled corresponding button in G-Helper UI should be blue.

Do you by any chance have any asus services that could interfere ?

**Comment by seerge** [comment] 2024-08-23 18:50
Quick question to @lazer15 since you have same device. Is FN-Lock inverted for you (in the latest build) or does it work correctly ?

**Comment by lazer15** [comment] 2024-08-23 19:40
@seerge 
Pressing FN and F3 (F3 is also volume up) results in F3 being pressed not volume up.

Pressing FN+ESC (turning on FN lock) -> then pressing F3 --- results in F3 being pressed (volume up is not triggered).

With FN+ESC not pressed and FN not pressed ---- volume up is triggered when pressing the same F3/volume+ key.

**Comment by seerge** [comment] 2024-08-23 19:43
@lazer15 ok, so it's also inverted then ?

**Comment by lazer15** [comment] 2024-08-23 19:56
@seerge 
I disabled g-helper, started asus services and rebooted.

The way it should work according to the Asus pop-ups is 'FN+ESC' turns on the lock and the alternate functions on the F# keys become active like volume up/down not F2/F3.

Turning on 'FN+ESC' shows a popup that the keys will act like normal F# keys.

So yes, it is inverted with g-helper. Correct with asus services.

![lock_off](https://github.com/user-attachments/assets/8b85dce8-f603-404e-8380-7b0f17f11cb4)
![lock_on](https://github.com/user-attachments/assets/f0a52eed-940e-45b2-bb65-4707d3a77d72)

**Comment by seerge** [comment] 2024-08-23 20:27
@lazer15 @Cudacke ok, thanks

Try this build then, it should behave same as Asus service (i.e. I have inverted fn-lock back)
[GHelper.zip](https://github.com/user-attachments/files/16733384/GHelper.zip)

**Comment by lazer15** [comment] 2024-08-24 15:35
@seerge 
That's working like the Asus service now. No inversion.

Turning FN-Lock on enables volume control/brightness control. Turning off FN-Lock makes them normal F# keys.

**Comment by seerge** [comment] 2024-08-24 15:37
@lazer15 Amazing, closing as resolved then

Thanks for helping

**Closed by seerge** 2024-08-24 15:37 UTC
Labels: question

**Comment by lazer15** [comment] 2024-08-24 15:40
Do you know if flicker free dimming is supported on the proart?

I don't see it in the ghelper settings but it is present in my Asus.

**Comment by seerge** [comment] 2024-08-24 18:11
@lazer15 try this build [GHelper.zip](https://github.com/user-attachments/files/16737590/GHelper.zip)

**Comment by Cudacke** [comment] 2024-08-24 18:51
The new one worked after I reinstalled MyASUS, disable the services and the. uninstall MyASUS.

**Comment by seerge** [comment] 2024-08-24 21:44
@Cudacke you don't have to reinstall myasus to disable services. You can just stop them in `Extra`. But glad to hear.

**Comment by lazer15** [comment] 2024-08-25 02:27
@seerge 
Flicker free dimming slider appeared and it works.
![flicker free](https://github.com/user-attachments/assets/1914a29e-c56a-4267-9c3a-3e3d70a01562)
[logflicker.zip](https://github.com/user-attachments/files/16738760/logflicker.zip)

**Comment by Cudacke** [comment] 2024-08-25 04:06
@seerge 
Tflicker free dimming slider is also woking on my side. 

Thanks.
