### ISSUE TITLE
[Feature Request] Command line for g-helper

### ISSUE THREAD

**Issue by Shayviri** [seerge/g-helper#1565] opened 2023-11-05 14:57 UTC
Hi,

I would like to be able to use some external app to control the battery limitation via command line.
With g-helper, we have a GUI which allow this modification, but I didn't find anything about commands that would allow us to do it though command line.
By having such option, it would make easy the change of parameters via command line without using other tools which might conflict with g-helper.
I am sorry if it's already possible and missed it

Thanks anyway for this super nice tool!

**Comment by seerge** [comment] 2023-11-05 16:42
@Shayviri hello, this is a duplicate of https://github.com/seerge/g-helper/issues/652 

If you want to set different battery charge limit, you can do it via powershell directly (where 80 is desired limit)

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00120057, 80)
```

**Closed by seerge** 2023-11-05 16:42 UTC
Labels: duplicate
