### ISSUE TITLE
XG Mobile not detected by G-helper

### ISSUE THREAD

**Issue by TheMattMercy** [seerge/g-helper#2944] opened 2024-08-08 01:23 UTC
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

G-Helper does not detect 4090 XG Mobile and button to activate/switch to it does not appear. Devices plugged into the XG Mobile via USB & USB-C ports are recognizied, but external display is not detected (when it is plugged in), and the PC does not switch to the eGPU.

### How to reproduce the bug?

1. Turn on PC
2. Run Ghelper
3. Plug in XG Mobile

### Logs

[log.txt](https://github.com/user-attachments/files/16536407/log.txt)

### Device and Model

2023 ROG Flow x16

### Additional information.

I wiped my system & did a clean windows install, tried it without Armoury Crate, tried it with Armoury crate, and at least Armoury crate will have the XG mobile activation pop up sometimes.

I've gone through the FAQ, done all the "troubleshooting" steps (except the last one because the process couldn't be stopped), and I've edited the config file to add the "xgm_special" : 1 line, but it just disappears when re-opened.

I've tried all this with ASUS's drivers and with the OEM Intel & NVIDIA drivers.
I've tried it with the barrel jack plugged in, and unplugged.

### Armoury Crate

Installed

### Asus Services

8 & 0 (I've tried both)

### Version

0.181.0

### OS

Windows 11 Pro 23H2

**Comment by seerge** [comment] 2024-08-08 08:26
@TheMattMercy hello,

I don't see any signs of XGM in the log. If it's not reported by the actual device - G-Helper won't show it :) Please keep in mind that G-Helper doesn't monitor it in realtime, it checks if it's available only when you start app or when you open it's main window.

How does it work with AC ? Do I understand that it's not appearing there as well ? If so - looks like something is wrong with actual device or a cable ?

**Comment by TheMattMercy** [comment] 2024-08-08 10:30
With AC it the prompt will automatically show up when plugged in or if plugged in on boot (about half the time), and when I try to activate it, it says my DDS settings are wrong & need to be set to "Optimus", which I do but Nvidia Control Panel seems to switch back on its own.

OR even more likely it will seemingly detect the XG, then ask me if I want to activate it. ~1/4 times it will ask about killing processes, and sometimes it will not - but either way the red bar on "processing" fills up, but then the screen just never goes away.

Side note: I also always see the icon for the GPUTrayIcon.exe pop up on boot for half a second, then disappear.

Sometimes when I plug it in, the icon shows up, sometimes it doesn't. It seems like the event numbers (event 127, event 136, etc) are the XGM being plugged in and unplugged, no?

**Comment by seerge** [comment] 2024-08-08 10:45
@TheMattMercy so to clarify, in AC also doesn't show it and sometimes does ? Does it activate XGM after and does it work correctly?

G-Helper (same as AC) checks if XGM is connected via Asus endpoint:
https://github.com/seerge/g-helper/blob/1efda38ccf9971f593f9ca1219ced0744a68f16e/app/AsusACPI.cs#L72

It returns 1 if device is connected, and 0 if not. If you don't see it in UI - it means that endpoint always says it's not connected.

--

Try to quit app, add following line to `%appdata%\GHelper\config.json`
```
"debug": 1,
```

Then save it, start app again, go to `Extra` and click on `Zoom Glass` icon there. It will run a scan over all endpoints and open a log from it.

Check if ``0x00090018`` is there and if it's 0 or 1

---

**Comment by seerge** [comment] 2024-08-08 10:50
P.S. Try to do first 2 steps from https://github.com/seerge/g-helper/wiki/Troubleshooting - hardware reset and reinstall asus system control interface. May be it will help somehow.

**Comment by TheMattMercy** [comment] 2024-08-08 19:19
Trying what you said, I'd like to mention when I re-ran the System Control Interface, it said something like "this version doesn't support some function for your device", and sent me here: https://www.asus.com/support/faq/1045676/

**Comment by seerge** [comment] 2024-08-08 19:29
@TheMattMercy [Asus System Control interface](https://dlcdnets.asus.com/pub/ASUS/GamingNB/Image/Software/SoftwareandUtility/16031/ASUSSystemControlInterfacev3_ASUS_Z_V3.1.32.0_16031.exe?model=ROG%20Flow%20X16%20(2023)%20GV601) from [official drivers page](https://rog.asus.com/laptops/rog-flow/rog-flow-x16-2023-series/helpdesk_download/) for your model should install w/o any issues. If it refuses - there is probably some underlying problem with the device.

**Comment by TheMattMercy** [comment] 2024-08-08 19:32
Also, for the record, while most of the time the AC popup for the XGM just freezes on "processing" (activation popup), sometimes it will ask me if I want to. Close apps running on the dGPU, and when it loads, the AC XGM activation window does go away (around ⅘ full), and the system acts like it is plugged in, warning me I have to click the tray icon before disconnecting (it's not visible)

BUT the XGM LED never turns red no matter what I have done

**Comment by seerge** [comment] 2024-08-08 19:33
@TheMattMercy so XGM is not activating in AC at all?

**Comment by TheMattMercy** [comment] 2024-08-08 19:34
> @TheMattMercy so XGM is not activating in AC at all?

No, but it is showing the XGM LED controls.

I'm wondering if it's an issue with this XGM or my laptop - but I don't know how to figure out which one it is and I feel like the guys at "geek squad" won't be able to figure it out, either.

**Comment by seerge** [comment] 2024-08-08 19:35
@TheMattMercy well, if it's not activating - then as I have mentioned a very first reply, something is wrong with the device itself. Either XGM or even the laptop (considering the System Control Interface refuses to install)

**Comment by seerge** [comment] 2024-08-08 19:36
Good step would be try other XGM on same device, or other device with same XGM and then send a malfunctioning part for warranty :)

**Comment by TheMattMercy** [comment] 2024-08-08 19:39
> @TheMattMercy well, if it's not activating - then as I have mentioned a very first reply, something is wrong with the device itself. Either XGM or even the laptop (considering the System Control Interface refuses to install)
> 
> Obviously in this circumstances G-Helper won't solve anything, as the problem is not in AC or G-Helper in a first place :)

To clarify, it does install the SCI - it just gives me that weird popup. Maybe I need to install myASUS, as that's what it links me to.

Thank you for your help so far. I figured you might be able to tell by the code if it's the laptop or the XGM that's messing up. 

Also, do you have a discord for this project?

**Comment by TheMattMercy** [comment] 2024-08-08 19:40
> @TheMattMercy well, if it's not activating - then as I have mentioned a very first reply, something is wrong with the device itself. Either XGM or even the laptop (considering the System Control Interface refuses to install)
> 
> Obviously in this circumstances G-Helper won't solve anything, as the problem is not in AC or G-Helper in a first place :)

To clarify, it does install the SCI - it just gives me that weird popup. Maybe I need to install myASUS, as that's what it links me to.

Thank you for your help so far. I figured you might be able to tell by the code if it's the laptop or the XGM that's messing up. 

Also, do you have a discord for this project?

**Comment by seerge** [comment] 2024-08-08 19:44
@TheMattMercy 

> To clarify, it does install the SCI - it just gives me that weird popup. Maybe I need to install myASUS, as that's what it links me to.

It shouldn't give any warnings. If it does - it sniffs that something is wrong with the system.  You don't need MyASUS for Asus System Control interface :) (rather vice versa)

>Thank you for your help so far. I also hoped you might be able to tell by the code if it's the laptop or the XGM that's messing up.

From what i see laptop just don't see XGM connected and therefore can't activate it neither. I don't know why. The "connecting" progress bar in AC that you see - is just an UI solution to conceal actual activation, that is in fact an instant command to an endpoint in Asus Control Interface.

>Also, do you have a discord for this project?

No, Github is the only official resource + i'm active on reddit a bit :) 

I'm closing this as not planned as the issue is not connected with the app itself.

Good luck with troubleshooting. Thanks.

**Closed by seerge** 2024-08-08 19:44 UTC
Labels: question
