### ISSUE TITLE
Working fan curves for the ROG Ally

### ISSUE THREAD

**Issue by molnizzle** [seerge/g-helper#802] opened 2023-07-18 04:42 UTC
Currently, Ghelper doesn't seem to work with the ROG Ally. Setting manual fan curves to the lowest possible setting and I'm still seeing the "GPU" fan locked in at 85% just idling on the desktop at 40c. Armoury Crate services are disabled, only ghelper is live. It would be nice if the fan curves worked on the Ally like they do on the laptops.

**Comment by seerge** [comment] 2023-07-18 06:28
@molnizzle on my Ally it works. Can you post logs from ``%appdata%/ghelper`` and all debug info that was originally asked in the issue?

How does exactly same fan curve behave if you set it in AC ?

**Comment by vladimir-tutin** [comment] 2023-07-18 19:09
I am having this issue too to an extent. AC services are disabled yet my fan does not seem to always follow the profile set in GHelper. It does appear to work for a while but then eventually the fan ramps up and no longer follows the profile. Changing the profiles appears to work as it'll ramp up on turbo and then back down on balanced but eventually it stops following the profile. Log attached. I cannot seem to find a rhyme or reason for it. Earlier the Ally was just sitting in a dock and it ramped up after I hadn't touched it for 15+ minutes. Please let me know if additional details are needed or will help.
[log.txt](https://github.com/seerge/g-helper/files/12088200/log.txt)

**Comment by seerge** [comment] 2023-07-18 19:20
@vladimir-tutin even from your log i see that at least asus optimization service is running. I can presume you didn't uninstall AC as well? it can be overwriting profiles somewhere in background.
```
7/18/2023 2:35:51 PM: Optimization service is running
```

Anyway, app doesn't control your fans, BIOS does. From log I see that app sets curve and it's accepted :)

**Comment by vladimir-tutin** [comment] 2023-07-18 20:11
I've disabled all services via GHelper now and rebooted. The fan curve still isn't being followed, its ramping up high occasionally without the temperatures rising to what would match in the profile. AC is not uninstalled, but services are stopped from starting. GHelper now is showing 0 Asus services running.
![PoVocxp](https://github.com/seerge/g-helper/assets/14234678/f5
![jFzP9k4](https://github.com/seerge/g-helper/assets/14234678/bdfd031e-2f0a-4f67-84b1-1c6a6ed6f601)
2ba6f4-974f-45eb-af9c-5deb15d49b96)
![RCQ4aY5](https://github.com/seerge/g-helper/assets/14234678/bd1d773a-d223-4efe-8466-6baee80feae2)

**Comment by seerge** [comment] 2023-07-18 20:14
@vladimir-tutin g-helper doesn't stop Armoury services as that is left for AC uninstaller :) (it only stops the ones that come with windows update/myasus). 

I assume that something from armoury still runs and overwrites (check windows -> Services)

**Comment by seerge** [comment] 2023-07-19 09:48
@molnizzle any updates on the matter?

**Comment by vladimir-tutin** [comment] 2023-07-20 03:58
I did have AC disabled already. I've been doing some playing, and one thing I'm noticing is that the RPM on the graph aren't matching up exactly but also if I keep the fan curve above 6800 RPM it will not change. If the fan curve would have the RPM below 6800 it'll change. I also switched my view from RPM to percentage and it's showing 85/86%. 
![image](https://github.com/seerge/g-helper/assets/14234678/9a8c41fb-8d1b-4d6a-a5a6-84f07d105352)
![image](https://github.com/seerge/g-helper/assets/14234678/dfe9280a-199b-463c-a451-2fcd9dcbd601)
![image](https://github.com/seerge/g-helper/assets/14234678/3a7a7fd1-ad61-4cdd-816e-e1b238d0b381)
![image](https://github.com/seerge/g-helper/assets/14234678/7c2f6994-6c5a-46ef-bdfe-8b126a2486e0)

**Comment by vladimir-tutin** [comment] 2023-07-20 05:14
Figured it out. This is caused by BIOS 322 which doesn't allow for under 74% fan speed when >60C. It seems like a visual bug in the discrepancy, but the BIOS is what was causing this. I rolled back to 319 and fan curve are sticking.

**Comment by seerge** [comment] 2023-07-20 09:57
@vladimir-tutin I'm glad that it has worked out for you.

I'm closing issue as initial topic-starter ignored all questions, and doesn't answer / provide any information.

**Closed by seerge** 2023-07-20 09:57 UTC
Labels: question, not reproducible
